### ISSUE TITLE
Empire not catching connections back to it..

### ISSUE THREAD

**Issue by wifiuk** [EmpireProject/Empire#1002]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)
Kali latest 2018

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
payload created
tried windows/launcher
tried multi/launcher

for a nice powershell payload

## Screenshot of error, embedded text output, or Pastebin link to the error

i get the powershell.exe running on the target system, ican see it in the taskmanager
manually executing the command or via the .bat file

i can see the inbound request on my firewall, but empire doesnt seem to be able to register the connection in?
i can see that the port i have setup in my listener is listening awaiting connections...

i have tried different 80 vs 443 with and without certs, i get the same results.

**Comment by wifiuk** [comment]
sometimes after a while i get this

`xception happened during processing of request from ('195.171.18.175', 62641)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
`

**Comment by DakotaNelson** [comment]
This is almost certainly a problem with your connection, and not with Empire.

See: https://stackoverflow.com/questions/11866792/how-to-prevent-errno-32-broken-pipe
