### ISSUE TITLE
 stager/windows/macro syntax error

### ISSUE THREAD

**Issue by antonianis** [EmpireProject/Empire#1005]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)
Kali Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Hello, I am using the stager/windows/macro module with Obfuscation enabled. After I embed it to an Office document and attempt to run it I get a syntax error. I manage to fix this by escaping the double quotes that are part of the obfuscated code. After that stager run properly and a session was initiated.

**Comment by xorrior** [comment]
@antonianis I'm not sure what kind of response you're looking for? It looks you were able to resolve the issue? A PR for this would be greatly appreciated. Thanks
