### ISSUE TITLE
ImportError: No module named netifaces

### ISSUE THREAD

**Issue by Skyw3lker** [EmpireProject/Empire#1006]
Kali 17.3 X64  $$  python 2.7.14+

root@kali:~/Empire# ./empire 
Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/empire.py", line 29, in <module>
    import helpers
  File "/root/Empire/lib/common/helpers.py", line 53, in <module>
    import netifaces
ImportError: No module named netifaces

**Comment by xorrior** [comment]
@Skyw3lker did any errors occur during the install?

**Comment by xorrior** [comment]
@Skyw3lker also try a standalone install with pip.

**Comment by Dockmaster87** [comment]
Experiencing the same error. I did not notice any errors during install, and a stand alone pip says:
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages

**Comment by xorrior** [comment]
@Dockmaster87 what version of python is being used with Empire??

**Comment by Dockmaster87** [comment]
@xorrior Python 2.7.14+ on Kali

**Comment by Dockmaster87** [comment]
Full Error:

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Tools/Empire/lib/common/empire.py", line 29, in <module>
    import helpers
  File "/root/Tools/Empire/lib/common/helpers.py", line 53, in <module>
    import netifaces
ImportError: No module named netifaces

**Comment by Dockmaster87** [comment]
@xorrior After I did the pip uninstall and install I ran reset.sh and now it has started successfully.

**Comment by xorrior** [comment]
@Skyw3lker can you try @kylesmithit's solution?

**Comment by xorrior** [comment]
I'm going to close this out for lack of activity. @Skyw3lker feel free to comment if the above solution doesn't work for you.
