### ISSUE TITLE
obfuscate vbs error

### ISSUE THREAD

**Issue by gearcapitan** [EmpireProject/Empire#1016]
!] PowerShell is not installed and is required to use obfuscation, please install it first.
[!] Exception: 'NoneType' object has no attribute 'replace'

![kaligearcapitan-2018-03-05-02-05-53](https://user-images.githubusercontent.com/13740942/36963662-c1ab7982-2019-11e8-9c31-16afb82b67d8.png)

└─[$] <git:(master*)> apt install libssl1.0.0
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
El paquete libssl1.0.0 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

E: El paquete «libssl1.0.0» no tiene un candidato para la instalación
┌─[root@Gear] - [~/Empire/setup] - [lun mar 05, 02:12]

**Comment by DakotaNelson** [comment]
So, uh... is powershell installed on that machine?

**Comment by gearcapitan** [comment]
when i tryed to install powershell .deb y have conflic with this packet libssl1.0.0

**Comment by DakotaNelson** [comment]
I don't think we really have the bandwidth here to solve dependency problems, especially installing powershell on non-Windows systems.

The problem with Empire is that you don't have powershell, and I don't really think we can help you get that, so I'm going to close this.

Possible workarounds:
 - google around a bit about installing powershell on Linux
 - switch over to Windows when generating payloads
 - use a payload that doesn't use obfuscation
