### ISSUE TITLE
Error in lines 13, 29, 53

### ISSUE THREAD

**Issue by GreenSales** [EmpireProject/Empire#1025]
Hello, i'm using Kali Linux with the 2.3.0 Empire version and this error always comes up: 
![untitled](https://user-images.githubusercontent.com/37221785/37349503-3e58edd6-26df-11e8-9985-d001dd6a3c04.png)

Can someone tell me how to fix it? Thanks in advance :)

**Comment by xorrior** [comment]
@GreenSales Can't say that I've seen that specific error before. Looks like there is an issue with the netifaces library. Are you using another python install? https://stackoverflow.com/questions/11878666/python-undefined-symbol-pyunicodeucs2-decodeutf8

**Comment by GreenSales** [comment]
Everything i use is preinstalled in Kali and than updated. With the new 2.5 version of empire this shows up:
I really don't understand because there was no error at the installation process.
![untitled](https://user-images.githubusercontent.com/37221785/37514657-3317808e-2911-11e8-9e58-ace4a7b5fca2.png)

**Comment by xorrior** [comment]
@GreenSales can you try starting empire with just sudo ./empire ?

**Comment by DakotaNelson** [comment]
If I had to guess, I'd say either your python binary or one of the Empire module binaries was built wrong.

See: https://stackoverflow.com/questions/16871799/trying-to-import-a-module-undefined-symbol-pyunicodeucs4-decodeutf8

I'd double check and try to reinstall python and Empire, making sure all pre-compiled binaries are built on this system and not moved over from another one.

**Comment by GreenSales** [comment]
@xorrior  I tried.. you can see in the screenshot

**Comment by GreenSales** [comment]
@DakotaNelson thanks, i'll give it a try :)

**Comment by GreenSales** [comment]
@DakotaNelson  I reinstalled python and the same error appared.. I tried to install it in backbox but still..

![untitled](https://user-images.githubusercontent.com/37221785/37567098-a11100fa-2aca-11e8-8fae-f6d856f7b1e4.png)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Same error on Ubuntu 16.04, solved with
`apt-get --auto-remove --yes python-openssl`
`pip install pyopenssl`

**Comment by xorrior** [comment]
@GreenSales Can you try @ThePirateWhoSmellsOfSunflowers' suggestion?

**Comment by GreenSales** [comment]
It worked :D Thanks @ThePirateWhoSmellsOfSunflowers and @xorrior

**Comment by xorrior** [comment]
👍
