### ISSUE TITLE
Exception: global name 'stager' is not defined

### ISSUE THREAD

**Issue by day1player** [EmpireProject/Empire#1030]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Kali 2018.1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Agent is not connecting back to Empire. Fresh install of Kali, updated and upgraded. Fresh install of Empire. 

## Screenshot of error, embedded text output, or Pastebin link to the error
<img width="614" alt="screen shot 2018-03-17 at 10 25 17 am" src="https://user-images.githubusercontent.com/37482972/37558450-bbeafd1c-29d1-11e8-9ec8-3f5b001f4418.png">

## Any additional information

**Comment by xorrior** [comment]
@day1player That error is fixed in the master branch and the hta is confirmed working.
