### ISSUE TITLE
Error download file

### ISSUE THREAD

**Issue by LIZySARA** [EmpireProject/Empire#1031]
## Empire Version

2.5
## OS Information (Linux flavor, Python version)
Ubuntu 16.04.4 LTS

## Screenshot of error, embedded text output, or Pastebin link to the error
![screenshot_1](https://user-images.githubusercontent.com/22563762/37600422-2f46677a-2b7f-11e8-969a-5a2bdac9d2b2.png)

## Any additional information
Where does the problem come from,?
Even when I try to 
download C:\Users\Public\passlist.txt
It's the same

**Comment by mr64bit** [comment]
This is addressed in #1034.

**Comment by xorrior** [comment]
#1034 Merged in dev and master.
