### ISSUE TITLE
BypassUac

### ISSUE THREAD

**Issue by GreenSales** [EmpireProject/Empire#1035]
Hello, i tried bypassuac on windows 10 and it didn't work.. can anyone tell me why? 
![untitled](https://user-images.githubusercontent.com/37221785/37631506-b0a78c36-2bf2-11e8-93ea-cf734b8984dc.png)

**Comment by xorrior** [comment]
@GreenSales I would suggest doing some research into bypassuac and how it works. There are several methods that have been released that work for different versions of Windows. Some have been definitely been fixed on Windows 10.
