### ISSUE TITLE
the frame work fails to start

### ISSUE THREAD

**Issue by eqhaleel** [EmpireProject/Empire#1058]
this is the error in question,help offered would be very much appreciated

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/root/Empire/lib/common/helpers.py", line 53, in <module>
    import netifaces
ImportError: No module named netifaces

**Comment by import-au** [comment]
Have you tried `pip install netifaces` with the version of Python you're using?

**Comment by eqhaleel** [comment]
yes, and i further encountered another problem...here is the problem

Traceback (most recent call last):
  File "./empire", line 5, in <module>
    from flask import Flask, request, jsonify, make_response, abort, url_for
ImportError: No module named flask

**Comment by eqhaleel** [comment]
@import-au yes, and i further encountered another problem...here is the problem

Traceback (most recent call last):
File "./empire", line 5, in
from flask import Flask, request, jsonify, make_response, abort, url_for
ImportError: No module named flask

**Comment by eqhaleel** [comment]
@xorrior  Attached is the screenshot of the error i encountered during installation
![screenshot from 2018-04-08 19-05-52](https://user-images.githubusercontent.com/29148605/38473606-9605480a-3b60-11e8-9aa6-07f9ae3d09a6.png)

**Comment by xorrior** [comment]
@eqhaleel can you try apt-get install python-dev?

**Comment by eqhaleel** [comment]
i just tried it...thesame error pops up

**Comment by eqhaleel** [comment]
thanks for your support @import-au @xorrior
