### ISSUE TITLE
Persistence on Mac (with Parallels installed) no longer working

### ISSUE THREAD

**Issue by jens1966** [EmpireProject/Empire#1059]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Mac 10.13.3
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When using the stager osx/launchdaemonexecutable the message "Persistence has been installed: ... and "Empire daemon has been written to ... appears but i dont get a new connected Agent. Also when restarting the target no connection is made.

## Screenshot of error, embedded text output, or Pastebin link to the error
There is no errror message.

**Comment by jens1966** [comment]
I just reinstalled Empire v 2.3 and with this version persistence is working just fine.

**Comment by jens1966** [comment]
Workarround: i copied alle the version 2.3 modules in the directory python/collection/osx/  to the corresponding version 2.5 directory and this is working just fine in version 2.5 ... including the new record_mic module

**Comment by jens1966** [comment]
Accedialy closed the issue.

**Comment by xorrior** [comment]
Fixed in dev and master.
