### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by usmarine2141** [EmpireProject/Empire#1073]
stupid question... 

how to update the framework?

is it git pull?

Could you add an option to check for and update and if there is update?

**Comment by DakotaNelson** [comment]
`git pull` will update, yes, and you can use `git checkout <branch>` to choose between stable (master) and development (dev) versions of the framework. (Remember to run `git pull` again after you've checked out a new branch.)

As for the option to check for an update - sounds like a great candidate for a contribution. :)
