### ISSUE TITLE
Docker image failing to start

### ISSUE THREAD

**Issue by battlecl0ud** [EmpireProject/Empire#1076]
## Empire Version
Latest

## OS Information (Linux flavor, Python version)
ubuntu

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Starting empire using `docker run -it empireproject/empire`

## Screenshot of error, embedded text output, or Pastebin link to the error
```bash
~ ❯❯❯ docker run -it empireproject/empire
/usr/bin/env: 'python': No such file or directory

```

## Any additional information
This was tried on multiple docker hosts (virtualbox, play-with-docker, aws)

**Comment by PierrickV** [comment]
Hi,

This issue should have been fixed, see : *Docker fails to run - "python - no such file or directory" #1033*

Unfortunately, the new image version has not been pushed on docker hub.

You can build it yourself :

```
git clone https://github.com/EmpireProject/Empire.git
cd Empire/
docker build -t empire .
docker run -it empire
```

**Comment by xorrior** [comment]
@battlecl0ud I would reach out to @killswitch-GUI to get a new image uploaded
