### ISSUE TITLE
question: powershell/privesc/ask 

### ISSUE THREAD

**Issue by harem234** [EmpireProject/Empire#1084]
how can i change the launcher script in the last line of module 
/////////
.
.
.
.
.
.
''' %(encLauncher)
                if obfuscate:
                    script = helpers.obfuscate(self.mainMenu.installPath, psScript=script, obfuscationCommand=obfuscationCommand)
return script

//////////////////

script: how can i alter the launcher script 
because antivirus don't let any script start with the word 'powershell' in it.

**Comment by mr64bit** [comment]
You can change the "Launcher" property on your listener to whatever you like.
I don't know what AV you're up against, but you may be able to just be able to copy powershell.exe to something else, and then change your launcher option in the listener to call that executable instead.
If that's still blocked, then you'll have to get more creative.
