### ISSUE TITLE
Powershell agents stop responding

### ISSUE THREAD

**Issue by just1fi3d** [EmpireProject/Empire#1089]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)
Ubuntu 
Python 2.7.12

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

After a few hours powershell agents stop responding. This has happened many times and does not appear to be associated with reboots or any events on the remote system that I can discern. The amount of time seems to vary but they always stop responding. I've run empire in debug mode and looked at the empire and agent debug logs but saw nothing that would indicate a agent failure. Is there any way to write debug logs for the agent to a file on the system the agent is installed on? I need to figure out why the agents stop executing but at this point I'm not sure how to troubleshoot that.

**Comment by mr64bit** [comment]
Are your agents running in a powershell.exe, or have you injected into another process? If the latter, it's possible the process has simply stopped. There's no much an agent can do to prevent it.

The easiest way to get debug info on an agent is to comment out $ErrorActionPreference="SilentlyContinue" in the agent stager code.
https://github.com/EmpireProject/Empire/blob/master/data/agent/stagers/http.ps1#L59
This will stop Powershell from suppressing errors. If you run your agent in a powershell console (just paste the non-Base64'd agent code and run it) you'll see the errors in the console when they occur.

You can also do Unix style output redirection, like so:
<agent code here> 2>> agent-errors.txt
Seems the file will only be written when the agent actually exits though, (or the buffer is filled, I assume, no clue how large it has to be though) so may not be a complete solution if you don't have access to an actual Powershell console.

**Comment by just1fi3d** [comment]
I've just been using multi/launcher without injecting further into any processes. I'll give output redirection a shot and see what I see.

**Comment by just1fi3d** [comment]
No luck with output redirection, just ended up with blank files. I'll have to give changing the error action thing a try.

**Comment by mr64bit** [comment]
Sorry, should have been clearer.
You need to remove the $ErrorActionPreference line either way. When set to "SilentlyContinue", Powershell will just not output any uncaught errors when they occur.

**Comment by just1fi3d** [comment]
Ah I see now, I'll try that with redirection and the SilentlyContinue flag set.  Obviously didn't think that through before 😄

**Comment by just1fi3d** [comment]
I'm still troubleshooting this. I typically install agents via wmi but its hard to get error output from that so I was RDPing in to a server and starting agents as recommended above but then I realized that processes started that way die after being disconnected from rdp. So I just started some local agents on my laptop and hopefully they will die and I'll get some errors back soon. I'm open to ideas for troubleshooting this though.

**Comment by just1fi3d** [comment]
Looks like the actual issue (or maybe I'm having multiple) is with the listener itself dying. All my agents stopped responding at once and I can't get any new agents deployed they get the following error:

```Exception calling "DownloadData" with "1" argument(s): "The underlying connection was closed: An unexpected error
occurred on a send." At line:1 char:1752
+ ... VQi1aMZPtGRSN7CH1z+CQzGGsQ=");$DatA=$WC.DOWNLoaDDaTa($sER+$t);$IV=$DA ...
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Cannot index into a null array.
At line:1 char:1784
+ ... 1z+CQzGGsQ=");$DatA=$WC.DOWNLoaDDaTa($sER+$t);$IV=$DAta[0..3];$DATa=$ ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At line:1 char:1800
+ ... oaDDaTa($sER+$t);$IV=$DAta[0..3];$DATa=$DaTa[4..$DATA.LengtH];-jOIN[C ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

¹ : The term '¹' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ¹
+ ~
    + CategoryInfo          : ObjectNotFound: (¹:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException 
```



I don't see much of anything in the empire debug log, just the empire agents stop responding

```018-05-02 13:05:53 Agents : [*] handle_agent_data(): sessionID D5718LHS issued a TASKING_REQUEST
2018-05-02 13:05:54 listeners/http : [*] GET request for *.com:9865/get.php from *.*.*.*
2018-05-02 13:05:54 listeners/http : [*] GET cookie value from *.*.*.* : session=******
2018-05-02 13:05:54 Agents : [*] handle_agent_data(): sessionID XN1D49MA issued a TASKING_REQUEST
2018-05-02 15:38:54 Agents : [*] Tasked D5718LHS to run TASK_CMD_WAIT
```
I tried killing and restarting the listener but got a 


```2018-05-02 16:11:11 listeners/http : [!] Listener startup on port 9865 failed: [Errno 98] Address already in use```

**Comment by jeffmcjunkin** [comment]
Looks like this happened to me yesterday. Somehow the listener was no longer responsive, but still bound to the port from Linux's perspective. I couldn't gracefully exit Empire, so I instead `kill`'d it from another terminal and re-launched it successfully.

**Comment by jeffmcjunkin** [comment]
For reference, I'm using latest dev branch on Ubuntu 16.04 x64, Flask version 1.0.2.

**Comment by just1fi3d** [comment]
@jeffmcjunkin  Were you able to find anything in the logs that would indicate why the listener died? I looked in mine but wasn't able to spot any likely culprits.

**Comment by xorrior** [comment]
@just1fi3d @mr64bit @jeffmcjunkin I'm going to run a test with two agents overnight and see what happens.

**Comment by xorrior** [comment]
@just1fi3d So I tested a powershell agent on Win 10 for roughly 17 hrs and did not have any issues with the agent or the listener. This was a fresh Empire install on a DO Ubuntu host.

**Comment by xorrior** [comment]
@just1fi3d I wasn't able to replicate the issues you were having in a 2nd test. I'm going to close this out for now. If you are able to obtain any additional information, please feel free to comment here.
