### ISSUE TITLE
install.sh error dependencies

### ISSUE THREAD

**Issue by johnjohnsp1** [EmpireProject/Empire#1091]
## Empire Version
empire 2.5 thru command git clone executed on 04/25/2018 at 06.32 (GMT+2) 

## OS Information (Linux flavor, Python version)
Linux VMKALI20173 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux
root@VMKALI20173:~/empire/setup# python -V
Python 2.7.15rc1
root@VMKALI20173:~/empire/setup# python3 -V
Python 3.6.5rc1
root@VMKALI20173:~/empire/setup# 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
....
Requirement already satisfied: xlrd>=0.7.2 in /usr/local/lib/python2.7/dist-packages (from xlutils->-r requirements.txt (line 17)) (1.1.0)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from pefile>=2017.8.1->pyinstaller->-r requirements.txt (line 10)) (0.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->-r requirements.txt (line 15)) (2.18)
rekall 1.7.1 requires rekall-agent<1.8,>=1.7.0rc1, which is not installed.
rekall 1.7.1 requires rekall-core<1.8,>=1.7.0rc1, which is not installed.
s3transfer 0.1.12 requires botocore<2.0.0,>=1.3.0, which is not installed.
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
Trovato:1 http://security.debian.org/debian-security wheezy/updates InRelease
Trovato:2 http://deb.debian.org/debian experimental InRelease                                                                                  
Trovato:3 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease                                                 
Trovato:4 http://kali.mirror.garr.it/mirrors/kali kali-rolling InRelease                                                         
Trovato:5 http://kali.mirror.garr.it/mirrors/kali kali-bleeding-edge InRelease
...
until the end this was the only error marked

## Any additional information
if I try to pip manually what's asked and missing thru command botocore,rekall-agent,rekall-core followed by pip install recall and s3transfer and do it again the ./install.sh the output point at 
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from pefile>=2017.8.1->pyinstaller->-r requirements.txt (line 10)) (0.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->-r requirements.txt (line 15)) (2.18)

rekall-agent 1.7.1 has requirement requests==2.18.1, but you'll have requests 2.18.4 which is 
incompatible.

Installing collected packages: requests
  Found existing installation: requests 2.18.1
    Uninstalling requests-2.18.1:
      Successfully uninstalled requests-2.18.1
Successfully installed requests-2.18.4
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

program is working but that missing requirement make it work unstable ?

thanks

**Comment by xorrior** [comment]
@johnjohnsp1 are you using python v2 or v3?

**Comment by johnjohnsp1** [comment]
thanks for the reply, seems by default on my system is python2, for the installation I use the file install.sh and have no chance to tell it to use python v2 or 3 elsewhere when I try to pip manually the missing packages I get the same error on the same package either if I'm using python v2 or 3

**Comment by xorrior** [comment]
@johnjohnsp1 try using python 2 pip to install all of the dependancies shown in the requirements.txt file.

**Comment by johnjohnsp1** [comment]
if I try use python2 with pip2 install -r requirements.txt I get this as output:

root@VMKALI20173:~/empire/setup# pip2 install -r requirements.txt 
Requirement already satisfied: urllib3>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (1.21.1)
Requirement already satisfied: requests==2.18.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (2.18.4)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (38.4.0)
Requirement already satisfied: iptools in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (0.6.1)
Requirement already satisfied: pydispatcher in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (2.0.5)
Requirement already satisfied: flask in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6)) (0.12.2)
Requirement already satisfied: macholib in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7)) (1.9)
Requirement already satisfied: dropbox in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8)) (8.5.0)
Requirement already satisfied: pyOpenSSL==17.2.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9)) (17.2.0)
Requirement already satisfied: pyinstaller in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10)) (3.3)
Requirement already satisfied: zlib_wrapper in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11)) (0.1.3)
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12)) (0.10.6)
Requirement already satisfied: M2Crypto in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13)) (0.27.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14)) (2.10)
Requirement already satisfied: cryptography in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15)) (2.2.2)
Requirement already satisfied: pyminifier==2.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16)) (2.1)
Requirement already satisfied: xlutils in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17)) (2.0.0)
Requirement already satisfied: pycrypto in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18)) (2.6.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests==2.18.4->-r requirements.txt (line 2)) (2018.1.18)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests==2.18.4->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests==2.18.4->-r requirements.txt (line 2)) (2.5)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt (line 6)) (0.14.1)
Requirement already satisfied: click>=2.0 in /usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt (line 6)) (6.7)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt (line 6)) (0.24)
Requirement already satisfied: altgraph>=0.15 in /usr/local/lib/python2.7/dist-packages (from macholib->-r requirements.txt (line 7)) (0.15)
Requirement already satisfied: six>=1.3.0 in /usr/local/lib/python2.7/dist-packages (from dropbox->-r requirements.txt (line 8)) (1.11.0)
Requirement already satisfied: dis3 in /usr/local/lib/python2.7/dist-packages (from pyinstaller->-r requirements.txt (line 10)) (0.1.1)
Requirement already satisfied: pefile>=2017.8.1 in /usr/local/lib/python2.7/dist-packages (from pyinstaller->-r requirements.txt (line 10)) (2017.11.5)
Requirement already satisfied: typing in /usr/local/lib/python2.7/dist-packages (from M2Crypto->-r requirements.txt (line 13)) (3.6.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from jinja2->-r requirements.txt (line 14)) (1.0)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 15)) (1.11.5)
Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 15)) (1.1.6)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 15)) (0.24.0)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 15)) (1.0.19)
Requirement already satisfied: xlwt>=0.7.4 in /usr/local/lib/python2.7/dist-packages (from xlutils->-r requirements.txt (line 17)) (1.3.0)
Requirement already satisfied: xlrd>=0.7.2 in /usr/local/lib/python2.7/dist-packages (from xlutils->-r requirements.txt (line 17)) (1.1.0)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from pefile>=2017.8.1->pyinstaller->-r requirements.txt (line 10)) (0.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->-r requirements.txt (line 15)) (2.18)

all fine but this package get the issue

rekall-agent 1.7.1 has requirement requests==2.18.1, but you'll have requests 2.18.4 which is incompatible.

**Comment by xorrior** [comment]
@johnjohnsp1 have you tried installing that specific version of requests?

**Comment by johnjohnsp1** [comment]
yes tried also that way but ending in a loop where some packages cannot be installed due to incompatible version like:

rekall-agent 1.7.1 has requirement requests==2.18.1, but you'll have requests 2.18.4 which is incompatible.
Installing collected packages: requests
  Found existing installation: requests 2.18.1
    Uninstalling requests-2.18.1:
      Successfully uninstalled requests-2.18.1
Successfully installed requests-2.18.4

this example I remove requests-2.18.4 manually with:
pip uninstall requests
then pip install requests to get the 2.18.1 but once I try with pip install -r requirements.txt will end up like the above text with installing the most recent version

thanks

**Comment by winnie22** [comment]
Hi, @johnjohnsp1. This really looks like problem (broken pip installation) with rekall only not Empire. Could you please remove rekall (pip2 uninstall rekall rekall-agent rekall-core rekall-lib rekall-layout-expert rekall-capstone rekall-efilter) and then try install.sh again?

**Comment by johnjohnsp1** [comment]
Hi, this is the output after uninstalled rekall and tried install.sh again

Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (10.0.1)
rekall-core 1.7.1 requires rekall-capstone==3.0.5.post1, which is not installed.
rekall-core 1.7.1 requires rekall-efilter<1.7,>=1.6, which is not installed.
rekall-core 1.7.1 requires rekall-lib, which is not installed.
Requirement already satisfied: urllib3>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (1.21.1)
Requirement already satisfied: requests==2.18.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (2.18.4)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (38.4.0)

Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->-r requirements.txt (line 15)) (2.18)
rekall-core 1.7.1 requires rekall-capstone==3.0.5.post1, which is not installed.
rekall-core 1.7.1 requires rekall-efilter<1.7,>=1.6, which is not installed.
rekall-core 1.7.1 requires rekall-lib, which is not installed.
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

that's all the items with issues

thanks

**Comment by johnjohnsp1** [comment]
~/empire/setup# pip2 search rekall
rekall (1.7.1)                      - Rekall Memory Forensic Framework
rekall-agent (1.7.1)                - Rekall Incident Response Agent
rekall-core (1.7.1)                 - Rekall Memory Forensic Framework
  INSTALLED: 1.7.1 (latest)
rekall-lib (1.7.1)                  - Rekall Support Libraries
rekall-layout-expert (1.5.0.post4)  - Rekall Layout Expert
rekall-capstone (3.0.5.post2)       - Capstone disassembly engine
rekall-efilter (1.6.0)              - EFILTER query language
pyrekall (0.0)                      - A wrapper for the Rekall framework
rekall_gui (1.5.0.post4)            - Rekall Memory Forensic Framework

**Comment by winnie22** [comment]
Please uninstall rekall-core (pip2 uninstall rekall-core). Errors should disappear.

**Comment by johnjohnsp1** [comment]
pip2 uninstall rekall-core
Uninstalling rekall-core-1.7.1:
  Would remove:
    /usr/local/bin/rekal
    /usr/local/bin/rekal.py
    /usr/local/bin/rekall
    /usr/local/lib/python2.7/dist-packages/rekall/*
    /usr/local/lib/python2.7/dist-packages/rekall_core-1.7.1.dist-info/*
    /usr/local/resources/.gitignore
    /usr/local/resources/MacPmem.kext.tgz
    /usr/local/resources/OSQuery.license
    /usr/local/resources/WinPmem/winpmem_x64.sys
    /usr/local/resources/WinPmem/winpmem_x86.sys
    /usr/local/resources/api.yaml
    /usr/local/resources/artifacts/memory.yaml
    /usr/local/resources/nssm.exe
    /usr/local/resources/rekall-agent-windows.bat
    /usr/local/resources/rekall-agent.yaml
Proceed (y/n)? y
  Successfully uninstalled rekall-core-1.7.1

then,finally, after ./install.sh no error were reported.

thanks you and everyone for the help!!
