### ISSUE TITLE
QUESTION: Can Empire agents do multiple call home domains/IP?

### ISSUE THREAD

**Issue by ceramicskate0** [EmpireProject/Empire#1113]
Can Empire agents do multiple call home domains/IP?
For example 10.0.0.1,10.0.0.2,10.0.0.3 (kind cobalt strike like)

**Comment by xorrior** [comment]
@ceramicskate0 I believe it can be done but the implementation isn't there. You can see in the generate_comms code that there was some consideration for it but the logic isn't there.

**Comment by ceramicskate0** [comment]
which file contains that btw?
