### ISSUE TITLE
Broken pipe Error happens after sometimes

### ISSUE THREAD

**Issue by johncole2017** [EmpireProject/Empire#1122]
## Empire Version
Empire 2.5

## OS Information (Linux flavor, Python version)
Kali - Python 2.7.15rc1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Broken pipe Error after passing few hours is happens , everything stop and when client want connect to C&C  server nothing happens and its not get any connection.
Port is open but nothing get establish.
## Screenshot of error, embedded text output, or Pastebin link to the error
https://pastebin.com/Jkie4zZw

## Any additional information
Please fix this issue or give me some way to fix that.
thanks

**Comment by xorrior** [comment]
@johncole2017 What I can ascertain from the information you have provided is that the client disconnected from the server. Can you provide any additional context?

**Comment by xorrior** [comment]
Closing for lack of response.

**Comment by johncole2017** [comment]
I'm sure client is Online , because after restarting Empire and listeners they will back again
