### ISSUE TITLE
searchmodule > [!] Exception: 'NeedsAdmin'

### ISSUE THREAD

**Issue by leesoh** [EmpireProject/Empire#1124]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Ubuntu 18.04, Python 2.7.15rc1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When typing `searchmodule` with no search parameters, a few modules are returned before an exception is raised.

## Screenshot of error, embedded text output, or Pastebin link to the error
[!] Exception: 'NeedsAdmin'

## Any additional information
This happens pretty early and appears to be consistent. I expect there is some malformed module code in there.

**Comment by xorrior** [comment]
Merged #1125
