### ISSUE TITLE
Run Empire over SOCKS

### ISSUE THREAD

**Issue by johncole2017** [EmpireProject/Empire#1130]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Kali - python 2.7.15rc1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Hi,
I wanna know how can i use SOCKS Proxies in powershell empire?
I know how use HTTP Proxies but not SOCKS . I want use this for all agents not for 1 agent (not use AlmondRocks for example).
thanks a lot ...

## Any additional information
i must say this too , i using powershell agent

**Comment by xorrior** [comment]
@johncole2017 Currently, we don't have any socks capabilities for the powershell agent.
