### ISSUE TITLE
New dbx agents error

### ISSUE THREAD

**Issue by alex-bergman** [EmpireProject/Empire#1136]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Linux 3.13.0-87-generic #133-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.12

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Empire crashed with 2 different dbx listeners.

## Screenshot of error, embedded text output, or Pastebin link to the error
(Empire: agents) > [*] New agent 6DE4RHXP checked in

(Empire: agents) > [*] Uploading key negotiation part 2 to /emp0001/staging/6DE4RHXP_2.txt for 6DE4RHXP

(Empire: agents) > 
(Empire: agents) > [*] New agent EA61HLNG checked in
[!] Exception in agents.handle_agent_staging() for 6ME4RHXP : Invalid ciphertext received.
[*] Agent 6DE4RHXP deleted
[*] Uploading key negotiation part 2 to /emp0002/staging/EA61HLNG_2.txt for EA61HLNG
[!] Exception in agents.handle_agent_staging() for EA61HLNG : Invalid ciphertext received.
[*] Agent EA61HLNG deleted
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/emp2.5/lib/common/helpers.py", line 900, in __run
    self.__run_backup()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/emp2.5//lib/listeners/dbx.py", line 983, in start_server
    dataResults = self.mainMenu.agents.handle_agent_data(stagingKey, stageData, listenerOptions)
  File "/opt/emp2.5/lib/common/agents.py", line 1541, in handle_agent_data
    dataToReturn.append((language, self.handle_agent_staging(sessionID, language, meta, additional, encData, stagingKey, listenerOptions, clientIP)))
  File "/opt/emp2.5/lib/common/agents.py", line 1386, in handle_agent_staging
    sessionKey = self.agents[sessionID]['sessionKey']
KeyError: '6ME4RHXP'

(Empire: agents) > 
(Empire: agents) > Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/emp2.5/lib/common/helpers.py", line 900, in __run
    self.__run_backup()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/emp2.5//lib/listeners/dbx.py", line 983, in start_server
    dataResults = self.mainMenu.agents.handle_agent_data(stagingKey, stageData, listenerOptions)
  File "/opt/emp2.5/lib/common/agents.py", line 1541, in handle_agent_data
    dataToReturn.append((language, self.handle_agent_staging(sessionID, language, meta, additional, encData, stagingKey, listenerOptions, clientIP)))
  File "/opt/emp2.5/lib/common/agents.py", line 1386, in handle_agent_staging
    sessionKey = self.agents[sessionID]['sessionKey']
KeyError: 'EA67HLNG'

(Empire: agents) >

**Comment by benichmt1** [comment]
The prevailing wisdom, according to Slack, is to clear out those entries manually in your dropbox and then restart the listener. This seems to take care of whatever conflict arises.

**Comment by xorrior** [comment]
@alex-bergma Did this error occur during the staging process or immediately after starting the listener?

**Comment by xorrior** [comment]
@alex-bergman Can you provide the debug output? I wasn't able to reproduce this issue. I was able to stage both a powershell and python agent with the dbx listener.

![image](https://user-images.githubusercontent.com/9156069/40618504-abd071ca-625f-11e8-9f8f-b16e27bee74e.png)

**Comment by xorrior** [comment]
@alex-bergman I would also recommend trying @benichmt1's suggestion. If you are still having this issue, please feel free to comment here.

**Comment by daniellukas12** [comment]
same issue
this is my output 
Empire: listeners) > [*] Sending POWERSHELL stager (stage 1) to x.x.x.x
[*] New agent D5LFPK7R checked in
[!] Exception in agents.handle_agent_staging() for D5LFPK7R : Invalid ciphertext received.
[*] Agent D5LFPK7R deleted
[!] Error returned for results by x.x.x.x : Error: Exception in agents.handle_agent_staging() for
 D5LFPK7R : Invalid ciphertext received.
>
