### ISSUE TITLE
Setting additional Cookies for the http listener with python

### ISSUE THREAD

**Issue by WickdDavid** [EmpireProject/Empire#1142]
## Empire Version 
2.5

## OS Information 
OS: Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux
Python: 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

While it is possible to set out different Headers in setting DefaultProfile, when setting the field 'Cookie' there are different problems.
Let's suppose we provide a new profile with this command:

`set DefaultProfile URI | UA | Cookie: key1=value1;`

The provided cookie will be one provided for, let's say, additional authentication.
During stage 1, each new field will be added with this line:

`req.add_header('FIELD X',"VALUE X");`

But since a Cookie will be added anyway by default by the following instruction:

`req.add_header('Cookie',"session=Y");`

The next instruction that will add our Cookie will overwrite the first definition of the Cookie field (check urllib2 docs for headers here https://docs.python.org/3/library/urllib.request.html#urllib.request.Request.add_header)

So, to add a custom Cookie, we should add a session cookie along the cookie we want to add, like this:

`set DefaultProfile URI | UA | Cookie: session=value_SESSION;key1=value1;`

But that's not all.
In fact, on different parts of the code eventual additional Cookies are not correctly parsed, throwing different exceptions at lines 84 in  Empire/data/agent/agent.py and 52 in Empire/data/agent/stagers/http.py.

Finally, in the definition of the send_message directive for python language in Empire/lib/listeners/http.py at line 836, only the session cookie will be used in the urllib2 requests, ignoring other cookies that may be required for the HTTP request itself (as auth Cookies).

## Screenshot of error, embedded text output, or Pastebin link to the error

It is hard to show the error, since both listener and stager will keep working, but the additional cookies won't be used in the requests following the highlighted instructions.

**Comment by xorrior** [comment]
Thanks for pointing this out @WickdDavid ! I'll take a look when I get a chance.

**Comment by xorrior** [comment]
@WickdDavid This should be fixed. Can you test the fix-for-1142 branch?

**Comment by WickdDavid** [comment]
I'll check it out and get back to you asap.

**Comment by WickdDavid** [comment]
Ok, the cookie error seems to be solved (I have used the Cookie option while setting up the listener, is that right?)
Thus, I'm getting new errors.
Maybe this problem is just related to what I'm trying to do. Just to be sure, I'm attaching it here.

![screenshot 2018-06-05](https://user-images.githubusercontent.com/18442485/40973176-92f3d07e-68c3-11e8-8541-61ae0214161b.png)

I have already faced these errors, but I thought they were cause by wrong authentication due to cookies. I don't know why it happens, but seems that sometimes the routing packet is not received correctly by the http server.
I have solved them by first hex-encoding the routing packet and decoding it in the http listener.

**Comment by WickdDavid** [comment]
In /lib/listeners/http.py, seems that by changing this block

`
                if customHeaders != []:
                    for header in customHeaders:
                        headerKey = header.split(':')[0]
                        headerValue = header.split(':')[1]
                        #If host header defined, assume domain fronting is in use and add a call to the base URL first
                        #this is a trick to keep the true host name from showing in the TLS SNI portion of the client hello
                        if headerKey.lower() == "host":
                            stager += helpers.randomize_capitalization("try{$ig=$WC.DownloadData($ser)}catch{};")

                        stager += helpers.randomize_capitalization("$wc.Headers.Add(")
                        stager += "\"%s\",\"%s\");" % (headerKey, headerValue)

                # add the RC4 packet to a cookie

                stager += helpers.randomize_capitalization("$wc.Headers.Add(")
                stager += "\"Cookie\",\"session=%s\");" % (b64RoutingPacket)`

to this

 

`cookieString = "{}={};".format(cookie,b64RoutingPacket)
                

                # Add custom headers if any
                if customHeaders != []:
                    for header in customHeaders:
                        headerKey = header.split(':')[0]
                        headerValue = header.split(':')[1]

                        if headerKey.lower() == "cookie":
                            cookieString += "{};".format(headerValue)
                            continue

                        #launcherBase += ",\"%s\":\"%s\"" % (headerKey, headerValue)
                        launcherBase += "req.add_header(\"%s\",\"%s\");\n" % (headerKey, headerValue)
                
                launcherBase += "req.add_header('Cookie',\"%s\");\n" % (cookieString) `

The 'session' cookie will just have the value but not the field name (i.e. 'session')

Here the problem in the decoded launcher i get from `launcher python http`

`req.add_header('Cookie',"disclaimer_accepted=1;=iuoREgJtZe9NHsbsrx0DVqIAdeM=;");`

**Comment by xorrior** [comment]
@WickdDavid, the cookie option is specifically for providing a custom name for the routingcookie. To use additional custom cookie values, they need to be set in the profile.

**Comment by WickdDavid** [comment]
Ok, I have set the cookie through DefaultProfile, still some problems arise.
In particular, on this line (n 52 of data/agent/stagers/http.py, but it is in other files, see my first comment)

`headers['Cookie'] = "%s;%s" % (headers['Cookie'], headerValue)`

Since on the first call the key 'Cookie' does not exists, this instruction will throw a **key error** (and then pass without saving the cookie value)
Of course this can be easily fixed by adding 'Cookie' as a key before referencing it.

**Comment by xorrior** [comment]
@WickdDavid Can you do another git pull and try again? Both the powershell and python listeners should be working with a custom cookie header.

![image](https://user-images.githubusercontent.com/9156069/40982968-8e456748-68ac-11e8-9e46-39ba71c9e662.png)

![image](https://user-images.githubusercontent.com/9156069/40982983-935109d6-68ac-11e8-90dc-c59c99961f98.png)

**Comment by WickdDavid** [comment]
Sorry, got busy all this week.
The fix works great, had some conflict by pulling the fix-branch ;)

**Comment by xorrior** [comment]
@WickdDavid great!

**Comment by xorrior** [comment]
merged/fixed
