### ISSUE TITLE
'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by infra-poppin-games** [EmpireProject/Empire#1143]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
ubuntu

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
listener: dbx
stager: windows/launch_vbs

when run sysinfo,return below error info

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://user-images.githubusercontent.com/7940673/40523186-18222f72-6007-11e8-9fbc-f38b60a6d13a.png)

**Comment by winnie22** [comment]
Hi @infra-poppin-games, could you please test with dev branch? There are merged some PR which solves some utf8 issues and can help you. It looks quite similar with issue #1114 too, but there is no fix yet. Thanks!

**Comment by infra-poppin-games** [comment]
same problem #1114
