### ISSUE TITLE
Error in obfuscation

### ISSUE THREAD

**Issue by H0nus** [EmpireProject/Empire#1148]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Debian
Linux pentest 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
Python 2.7.15

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I expect the stager to be created with obfuscated options set to True
If i don't choose to obfuscate the payload, it works fine

## Screenshot of error, embedded text output, or Pastebin link to the error
`
The managed DLL bound to this executable: 'pwsh.dll', did not match own name 'powershell.dll'.
A fatal error was encountered. This executable was not bound to load a managed DLL.
[!] Exception: [Errno 2] No such file or directory: u'/usr/share/empire/data/misc/Obfuscated.ps1'
`

## Any additional information
I don't understand why is doing that.
One thing that i changed is a copy of /usr/bin/pwsh to /usr/bin/powershell;

**Comment by xorrior** [comment]
@H0nus It's possible that this is a debian-only issue? I can generate a launcher with obfuscation on a Ubuntu host and the docker image with any issue. Can you try a fresh install and see if the issue persists?

**Comment by H0nus** [comment]
Yes, i'll take a look on fresh ubuntu and fresh debian too

**Comment by H0nus** [comment]
Well, that's strange, but reinstalling system actually worked :D 
I don't know why. Btw now it works: I just had to manually install libssl1.0.0 and powershell from debian 9 repos.
Thanks too much, and keep up your awesome project !
