### ISSUE TITLE
No Module Named iptools (Help)

### ISSUE THREAD

**Issue by ColeShelly** [EmpireProject/Empire#1150]
## Empire Version
Just Downloaded so Latest.

## OS Information (Linux flavor, Python version)
Kali Linux, Python 2.7 and 3.

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Followed the Instructions, read the README and looked on Youtube.

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Desktop/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/root/Desktop/Empire/lib/common/helpers.py", line 50, in <module>
    import iptools
ImportError: No module named iptools

**Comment by mr64bit** [comment]
Did you run the setup/install.sh script, and were there any errors shown?

If you did run the install script, you can try installing iptools manually with `pip install iptools` and see if that fixes it.

**Comment by ColeShelly** [comment]
Yes, i ran setup/install.sh and pip install iptools. iptools gave me..
--------------------------------------------------------------------------
pip install iptools
Requirement already satisfied: iptools in /usr/local/lib/python3.6/dist-packages (0.6.1)

**Comment by ColeShelly** [comment]
I did setup/install.sh and it installed, at the end it told me to create a password, once i did it finished.

**Comment by ColeShelly** [comment]
It Work! Thank You! Thank you very much!
