### ISSUE TITLE
Empire failed to start on fresh install 

### ISSUE THREAD

**Issue by vladimirpe00** [EmpireProject/Empire#1151]
## Empire Version
latest version

## OS Information (Linux flavor, Python version)
ubuntu 14.04 server  3.13.0-143-generic

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I cloned the empire repo
git clone https://github.com/EmpireProject/Empire.git,  cd Empire/setup/, and run ./install.sh 

and I got Setup complete !

## Screenshot of error, embedded text output, or Pastebin link to the error
 
once I ran ./empire or ./empire -debug 
im getting error

Traceback (most recent call last):
  File "./empire", line 5, in <module>
    from flask import Flask, request, jsonify, make_response, abort, url_for

## Any additional information

I tried to install requirements.txt using pip install requirements.txt and i got this error

/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt

**Comment by mr64bit** [comment]
>/usr/local/lib/python2.7/dist-packages/pip/vendor/urllib3/util/ssl.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

What versions of Python 2 and OpenSSL do you have?
Have you tried upgrading Python 2?
