### ISSUE TITLE
`ps`  function is missing from the tab completion of interacting agents

### ISSUE THREAD

**Issue by jmhickman** [EmpireProject/Empire#1162]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Ubuntu 18.04
Python 2.7.15rc1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Attempting to tab complete at the agent's prompt omits the `ps` functionality. At first I was kind of shocked that Empire didn't have this functionality, but I found a blog post that directly referenced it. It works fine, though it lacks a `help` entry.

## Any additional information
It would be nice to list `ps` in tab completion.  It is also missing from the `searchmodule process` and `searchmodule ps` if it is in fact a module itself.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi,

I may be wrong but I think it's because `ps` is a "bult-in" function and not a real module.

https://github.com/EmpireProject/Empire/blob/e37fb2eef8ff8f5a0a689f1589f424906fe13055/data/agent/agent.ps1#L330-L335 

:sunflower:

**Comment by xorrior** [comment]
@jmhickman ps is not actually a module. It's just an alias command in the agent.

**Comment by jmhickman** [comment]
Okay, fair enough. It's not a module, so it doesn't come back in a search for 'ps.'

That being said, my main feedback was that it isn't possible to discover the 'ps' functionality like I did all the other agent functions. It isn't in tab completion, and it isn't in `help` when run inside the agent context. I just think it would be good to add it to those two things.
