### ISSUE TITLE
Error when running dir/ls command with param

### ISSUE THREAD

**Issue by jammys** [EmpireProject/Empire#1164]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Debian

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Hello guys, I'm facing an error when I use dir/ls or mkdir short command with parameters since I've updated to the last version.

Error message : **error running command: A positional parameter cannot be found that accepts argument 'Owner;Expression={ (Get-Acl dir.FullName).Owner }},lastwritetime,length,name'.**

So I have to use : shell dir \\\\test\c$ to make it works.
But when I use dir/ls without args it works great. It seems the args causes the issue and aren't interpreted.

**Comment by daniellukas12** [comment]
same

**Comment by xorrior** [comment]
merged to the dev branch.
