### ISSUE TITLE
Empire not getting agent

### ISSUE THREAD

**Issue by ss6851** [EmpireProject/Empire#1170]
## Kali Linux 2018.2

I executed the payload (generated by `launcher powershel`l )on the server and the client, but didn't receive any agent in Empire.

The following is the screenshot (excerpt) of the payload/command, which I am executing on the server/client.

![image](https://user-images.githubusercontent.com/28718872/41792918-78633df4-7628-11e8-9c16-c917f623bc30.png)

**Comment by xorrior** [comment]
@ss6851 what troubleshooting steps have you taken already?

**Comment by ss6851** [comment]
I have executed the command ( the one in screenshot above) on WIndows Server 2016/2012 and Windows 10 Client.

**Comment by magicallizard** [comment]
Try turning off Windows Defender then try
