### ISSUE TITLE
Cannot get Powershell Obfuscation to work.

### ISSUE THREAD

**Issue by re8el** [EmpireProject/Empire#1172]
## Empire Version
2.5 

## OS Information (Linux flavor, Python version)
Kali Rolling x64, Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Cannot get Powershell Obfuscation to work.

## Screenshot of error, embedded text output, or Pastebin link to the error
https://pastebin.com/P74q8ZVr

**Comment by xorrior** [comment]
@re8el what troubleshooting steps have you taken?

**Comment by melkor993** [comment]
Add this line to your ".bashrc"

export TERM=xterm

it should solve the problem

**Comment by xorrior** [comment]
@re8el I'm going to close this for lack of activity.
