### ISSUE TITLE
Listener Redirector Not Worked Error

### ISSUE THREAD

**Issue by abbasjahanbakhsh** [EmpireProject/Empire#1176]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
kali 4.16..0

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
i want use pivot with empire
uselistener redirector
execute

[!] Agent is not present in the cache
[!] Listener failed to start!

## Screenshot of error, embedded text output, or Pastebin link to the error
(Empire: listeners/redirector) > agents

[*] Active agents:

 Name     La Internal IP     Machine Name      Username                Process            PID    Delay    Last Seen
 ----     -- -----------     ------------      --------                -------            ---    -----    ---------
 salam    ps 192.168.200.22  CLIENT701-PC      SAZMAN\jack          powershell         1040   5/0.0    2018-07-03 10:26:42
 SazmanWi ps 192.168.200.22  CLIENT701-PC      *SAZMAN\jack         powershell         812    0/0.0    2018-07-03 10:26:45
 

(Empire: agents) > listeners

[*] Active listeners:

  Name              Module          Host                                 Delay/Jitter   KillDate
  ----              ------          ----                                 ------------   --------
  http              http            https://192.168.200.21:443           5/0.0                      

(Empire: listeners) > uselistener http
(Empire: listeners/http) > info

    Name: HTTP[S]
Category: client_server

Authors:
  @harmj0y

Description:
  Starts a http[s] listener (PowerShell or Python) that uses a
  GET/POST approach.

HTTP[S] Options:

  Name              Required    Value                            Description
  ----              --------    -------                          -----------
  SlackToken        False                                        Your SlackBot API token to communicate with your Slack instance.
  ProxyCreds        False       default                          Proxy credentials ([domain\]username:password) to use for request (default, none, or other).
  KillDate          False                                        Date for the listener to exit (MM/dd/yyyy).
  Name              True        http                             Name for the listener.
  Launcher          True        powershell -noP -sta -w 1 -enc   Launcher string.
  DefaultDelay      True        5                                Agent delay/reach back interval (in seconds).
  DefaultLostLimit  True        60                               Number of missed checkins before exiting
  WorkingHours      False                                        Hours for the agent to operate (09:00-17:00).
  SlackChannel      False       #general                         The Slack channel or DM that notifications will be sent to.
  DefaultProfile    True        /admin/get.php,/news.php,/login/ Default communication profile for the agent.
                                process.php|Mozilla/5.0 (Windows
                                NT 6.1; WOW64; Trident/7.0;
                                rv:11.0) like Gecko
  Host              True        https://192.168.200.21:443       Hostname/IP for staging.
  CertPath          False       /root/Desktop/Tools/Empire/data/ Certificate path for https listeners.
  DefaultJitter     True        0.0                              Jitter in agent reachback interval (0.0-1.0).
  Proxy             False       default                          Proxy to use for request (default, none, or other).
  UserAgent         False       default                          User-agent string to use for the staging request (default, none, or other).
  StagingKey        True        e10adc3949ba59abbe56e057f20f883e Staging key for initial agent negotiation.
  BindIP            True        0.0.0.0                          The IP to bind to on the control server.
  Port              True        443                              Port for the listener.
  ServerVersion     True        Microsoft-IIS/7.5                Server header for the control server.
  StagerURI         False                                        URI for the stager. Must use /download/. Example: /download/stager.php

(Empire: listeners/http) > back
(Empire: listeners) > uselistener redirector
(Empire: listeners/redirector) > info

    Name: redirector
Category: peer_to_peer

Authors:
  @xorrior

Description:
  Internal redirector listener. Active agent required.
  Listener options will be copied from another existing agent.

redirector Options:

  Name              Required    Value                            Description
  ----              --------    -------                          -----------
  Listener          True        http                             Name of the listener to clone
  internalIP        True        192.168.200.22                   Internal IP address of the agent. Yes, this could be pulled from the db but it becomes tedious when there is multiple addresses.
  Name              True        Sazman_redirector1               Listener name. This needs to be the name of the agent that will serve as the internal pivot
  ListenPort        True        8082                             Port for the agent to listen on.

(Empire: listeners/redirector) > execute
[*] Starting listener 'Sazman_redirector1'
[!] Agent is not present in the cache
[!] Listener failed to start!
(Empire: listeners/redirector) >

**Comment by xorrior** [comment]
@abbasjahanbakhsh The Name field needs to be set to an actual agent name as the description of the module states.
