### ISSUE TITLE
Update Mimikatz on Invoke-Mimikatz.ps1 to 2.1.1-20180616

### ISSUE THREAD

**Issue by zlowram** [EmpireProject/Empire#1193]
## Empire Version
From git - dev branch

## OS Information (Linux flavor, Python version)
Windows 10 with all updates

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

The current version of Mimikatz being used in the Invoke-Mimikatz (2.1.1 20171106) does not work properly in a fully updated Windows 10 box. If you use the -DumpCreds option (sekurlsa::logonpasswords) it will error (ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list) and won't dump any credentials at all.

This behavior is fixed on the latest release (at the moment of writing is 2.1.1-20180616) so it would be great to have this latest version on Invoke-Mimikatz.

I've tried to naively do that myself by just replacing the b64 chunk by the b64 obtained from the original mimikatz PE but it didn't work (I guess it's not that straightforward). If you guide me on what else needs to be done I can do that myself and send a PR if you are busy.

Thank you!

**Comment by zlowram** [comment]
Nvm, found harmj0ys post about Invoke-Mimikatz and could finally update it myself. Here's the PR: https://github.com/EmpireProject/Empire/pull/1194

**Comment by xorrior** [comment]
@zlowram Thanks!
