### ISSUE TITLE
Ppwerahell/Empire wont install

### ISSUE THREAD

**Issue by zu3s** [EmpireProject/Empire#1198]
## Empire Version
2.3.0

## OS Information (Linux flavor, Python version)
kali linux 2018.2
python 2.7.15
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
i am trying to obfuscate a generated windows/launcher_bat

(Empire: stager/multi/launcher) > set Listener http
(Empire: stager/multi/launcher) > generate
[!] PowerShell is not installed and is required to use obfuscation, please install it first.
![screenshot 20](https://user-images.githubusercontent.com/34065997/43042741-9245406a-8d1f-11e8-91d8-be99bbcb9d69.png)
![screenshot 18](https://user-images.githubusercontent.com/34065997/43042742-95f14fd8-8d1f-11e8-877e-321f96da90fa.png)

## Any additional information
i have updated and upgrade the kali system as of July 21. 

Linux kali 4.16.0-kali2-amd64 #1 SMP Debian 4.16.16-2kali2 (2018-07-04) x86_64 GNU/Linux
i have re-installed empire a few times. it used to work. but now i cant obfuscate.

**Comment by xorrior** [comment]
@zu3s If powershell isn't installed, then obfuscation will not work.

**Comment by zu3s** [comment]
Yes I am well aware... but powershell will not install via the empire setup

**Comment by xorrior** [comment]
@zu3s I would try installing powershell outside of the empire setup.

**Comment by zu3s** [comment]
I did. I installed powershell via terminal on its on. Then running empire

**Comment by zu3s** [comment]
Thx. The obfuscation works. And now stagers arent gettng caught.
BUT, I can't get an active agent on windows 10 1803. I can get an agent on
macOS no problem. But nothing is happening in windows
