### ISSUE TITLE
Empire/no call back

### ISSUE THREAD

**Issue by zu3s** [EmpireProject/Empire#1199]
Empire Version

Not infront of my computer. But its the one from the dev branch cause the powershell doesn't work in kali

OS Information (Linux flavor, Python version)

Kali linux

Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Up until friday. Empire worked perfectly. I read getiing bal backs and agents left and right on my test computers. But starting yesterday. I make the payload the same way. And delivered it the same way.
But not 8 get no call back what sooo ever. Windows defender is picking up every domshe l single attempt.
And just to test theories. Copying the python script in cmd used to work. But doesn't now.
Side note. My veil evasion. Every single payload gets caught by windows defender as well. Any ideas?
I can't install phantom cause powershell/obfuscation

Screenshot of error, embedded text output, or Pastebin link to the error wont install pr work icorrectlyAny additional information

**Comment by protocolic** [comment]
The agents started to be detected by the defender, the methods of obfuscation in Empire do not help. Who else has this problem? Tried to use separately invoke obfuscation with different keys did not help. Who knows what the problem is?

**Comment by zu3s** [comment]
Kinda the same problem. But  I cant even use obfuscation. Ps wint install
in kali or through the empire download

**Comment by protocolic** [comment]
If PS doesn't install you should install it. Because empire will not work without PS.

**Comment by zu3s** [comment]
Ps will not install

**Comment by zu3s** [comment]
got ps installed

**Comment by zu3s** [comment]
now payloads are not being detected by windows defender. 
BUT , now when payload is executed on target machine. there is no call back to the attacking machine.
any ideas?

**Comment by protocolic** [comment]
disable defender, and generate until it works

**Comment by zu3s** [comment]
So, the stagers arent being caught. There are getting on the target machine no problem now. But once activated. No callback to the attacker machine.  I tried on macOS and got a agent no problem. ?? But windows 10 version 1803 with windows defender off firewall off ,will not get a agent?  Thoughts?

**Comment by xorrior** [comment]
@zu3s It could be a number of host or network based controls that are preventing you from getting an agent. No way to know what those could be with the information you've provided.

**Comment by zu3s** [comment]
Understood.
