### ISSUE TITLE
Detected by the Defender  Windows  4.18.1807.18075

### ISSUE THREAD

**Issue by protocolic** [EmpireProject/Empire#1201]
## Empire Version
Версия Empire: 2.5 

## OS Information (Linux flavor, Python version)
Версия CentOS Linux 7.5.1804 (Core) 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

The agents started to be detected by the defender, the methods of obfuscation in Empire do not help.

Detects an object: amsi:PowerShell_C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe_10.0.14393.00000000000000002

Determines: Trojan:Win32/ArmsiTaper

The obfuscation is done in Empire and using Invoke-Obfuscation v1.8

Help with this problem?

**Comment by xorrior** [comment]
@protocolic We do not provide any official support for bypassing AV. I would do some additional research.
