### ISSUE TITLE
autorun module

### ISSUE THREAD

**Issue by poopaapoopaa** [EmpireProject/Empire#1205]
Is there a way to know which module is currently set as the autorun module (apart from checking them one by one)?

**Comment by winnie22** [comment]
Hi, i think you are using the old autorun style. Did you try this - https://www.blackhillsinfosec.com/empire-resource-files-auto-runs-docx/? Then command autorun show will solve your issue.

**Comment by xorrior** [comment]
@poopaapoopaa please let us know if the suggestion from @winnie22 does not work for you.
