### ISSUE TITLE
powershell/collection/screenshot

### ISSUE THREAD

**Issue by poopaapoopaa** [EmpireProject/Empire#1207]
The script that appears in the comments (https://github.com/PowerShellMafia/PowerSploit/blob/master/Exfiltration/Get-TimedScreenshot.ps1) seem to have an interval parameter. However the module in Empire only takes Ratio and Agent parameters. Is it possible to use it for repeated screenshots with a time interval?

**Comment by xorrior** [comment]
@poopaapoopaa You can modify the module to try repeated screenshots. I'm not sure how empire would handle the output.
