### ISSUE TITLE
Powershell Jobs

### ISSUE THREAD

**Issue by fridgehead** [EmpireProject/Empire#1208]
## Empire Version
2.4

Is it possible to use powershell Jobs framework to spawn background tasks? I have a module that spawns an SSH tunnel as a Job, when i run it with scriptimport / scriptcmd the job starts fine however I cant seem to kill the job afterwards. "Shell get-job" doesnt list anything and the function i wrote to retrieve jobs and kill them also retrieves nothing

Is there some sort of odd runspace thing going on with stuff spawned by scriptcmd?

**Comment by mr64bit** [comment]
Agents build their own AppDomain for each job, so you won't see them with `Get-Job`.

When a job starts, you'll see a message from the agent `Job started: <job id>`. You can also fetch running jobs from an agent with `jobs`.

You can kill a running job with `jobs kill <job id>`.
