### ISSUE TITLE
[file] requested by [IP] with no routing packet

### ISSUE THREAD

**Issue by poopaapoopaa** [EmpireProject/Empire#1210]
I've been getting several of the above messages while Empire runs with an http listener on port 8080 - common file names (that I don't have) being requested by IPs I don't know. What is that? looks like somebody performs scanning? perhaps using a less common port would solve that?

**Comment by xorrior** [comment]
@poopaapoopaa You can change the port that is used in the listener options. You can also implement a reverse proxy as a redirector and filter out erroneous requests.

**Comment by poopaapoopaa** [comment]
Thanks thing is I'm not sure if it's something that needs to be screened or an error of an actual agent.
I saw a similar issues in:
https://github.com/EmpireProject/Empire/issues/1053

I get the same file (login/process.php) requested with this error, as well as other files, such as manager/html.

I use http listener.
