### ISSUE TITLE
Laucher_bat detected by AV's.

### ISSUE THREAD

**Issue by alienwaresoldier** [EmpireProject/Empire#1212]
Laucher_bat detected by most of the AV's.

Couple of months ago if tested and generate a launcher bat it was FUD. 1/36 or 2/36 max.
But now i see its detecteble by most of the AV's

My quistion is, why?

**Comment by generatorada** [comment]
That's it because of such as you and not FUD you need to use private AV scanners that do not send data

**Comment by generatorada** [comment]
That's it because of such as you and not FUD you need to use private AV scanners that do not send data

**Comment by alienwaresoldier** [comment]
I was thinkin the same.I know it is because of people don’t use private AV scanners like us :-(
We must think of something to prevent  it in the future. Anyway thanks for your comment :-)

**Comment by poopaapoopaa** [comment]
no distribute doesn't seem to work anymore. I didn't see a currently usable online alternative (that doesn't share results). Any recommendations?

**Comment by alienwaresoldier** [comment]
Use private av scanners like antiscan.me or run4me. **DO NOT USE VIRUS TOTAL!!!!**
