### ISSUE TITLE
Modules missing?

### ISSUE THREAD

**Issue by nafstad** [EmpireProject/Empire#1214]
## OS Information (Linux flavor, Python version)
Ubuntu 16.04.5
Python 2.7.12

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Trying to run empire after i have installed it:

`./empire
Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/opt/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/opt/Empire/lib/common/helpers.py", line 50, in <module>
    import iptools
ImportError: No module named iptools
`

## Any additional information

Have tried to run install.sh several times, and getting the same error.

**Comment by nafstad** [comment]
Just did a clean install, got it to work now..

**Comment by antonytuff** [comment]
nafstad I have been experiencing the same issue did you manage to fix it.
