### ISSUE TITLE
usemodule persistence/elevated/schtasks   Unable to return

### ISSUE THREAD

**Issue by Afangkuai** [EmpireProject/Empire#1216]
![image](https://user-images.githubusercontent.com/22121116/44761759-ee75fa80-ab76-11e8-8bf4-72e31d36473c.png)

![image](https://user-images.githubusercontent.com/22121116/44761770-fd5cad00-ab76-11e8-931e-ea5057bcb498.png)

A target machine，
No use of any anti-virus software to close the firewall.

**Comment by mr64bit** [comment]
Is "txt" the name of a running listener?
That's that the error message is indicating.
