### ISSUE TITLE
Install script .deb package 404 

### ISSUE THREAD

**Issue by SunnySwagger** [EmpireProject/Empire#1218]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Kali Rolling 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Debian package libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb not found during installation of the Empire. 

## Screenshot of error, embedded text output, or Pastebin link to the error
root@kali:/opt/Empire/setup# ./install.sh 
--2018-09-02 23:34:59--  http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
Resolving ftp.us.debian.org (ftp.us.debian.org)... 64.50.236.52, 64.50.233.100, 128.30.2.26, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|64.50.236.52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-09-02 23:35:00 ERROR 404: Not Found.

dpkg: error: cannot access archive 'libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb': No such file or directory

## Any additional information
I have to search for the similar package and add it to the install.sh script in order to fix. It would be great if the installation script is updated on the main Empire git repo.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
#1219 should fix this

**Comment by mr64bit** [comment]
#1268 fixes this, has been merged.
