### ISSUE TITLE
Solution for failed pip dependency in ubuntun 9.5 pycrypto 

### ISSUE THREAD

**Issue by madisettisunil** [EmpireProject/Empire#1220]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
ubuntu 9.5

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Empire launch failed because of 

## Screenshot of error, embedded text output, or Pastebin link to the error
Failed building wheel for pycrypto

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ohqoTY/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wGkBoa/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ohqoTY/pycrypto/

## Any additional information
apt-get install build-essential libssl-dev libffi-dev python-dev solves above issue

**Comment by mrsmith0x00** [comment]
@madisettisunil how about to update Ubuntu? ;)

**Comment by DakotaNelson** [comment]
Yeah, that ubuntu is super old. Closing.
