### ISSUE TITLE
Unable to Start EMPIRE MAC OSX High Sierra File "./empire", line 35     print '[*] Fresh start in docker, running reset.sh for you'  \

### ISSUE THREAD

**Issue by Bal33p** [EmpireProject/Empire#1226]

**Comment by Bal33p** [comment]
Current version.
MACOs High Sierra 10.13.6 
Empire will not run Error

 sudo ./empire 
  File "./empire", line 35
    print '[*] Fresh start in docker, running reset.sh for you'
                                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('[*] Fresh start in docker, running reset.sh for you')?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hey,
Seems you try to launch Empire with python 3. I don't know MacOS but can you try:
`sudo python2.7 ./empire`

(or try python2.6 or type python2[TAB][TAB] to see which python version you have)

**Comment by Bal33p** [comment]
Thanks for the suggestion.

I tried all three.. and reinstalled python2.7 using Brew

$ python
python             python2            python2.7          python3            python3-config     python3.6-32       python3.6m         python3.7          python3.7m         pythontex          pythonw2           
python-config      python2-config     python2.7-config   python3-32         python3.6          python3.6-config   python3.6m-config  python3.7-config   python3.7m-config  pythonw            pythonw2.7         


$ sudo python ./empire 
Password:
  File "./empire", line 35
    print '[*] Fresh start in docker, running reset.sh for you'
                                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('[*] Fresh start in docker, running reset.sh for you')?


$ sudo python2 ./empire 
Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/Users/laniakea/Applications/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
  File "/Users/laniakea/Applications/Empire/lib/common/helpers.py", line 574, in get_config
    cur.execute("ALTER TABLE config ADD COLUMN %s BLOB" % (field))
sqlite3.OperationalError: no such table: config


$ sudo python2.7 ./empire 
Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/Users/laniakea/Applications/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
  File "/Users/laniakea/Applications/Empire/lib/common/helpers.py", line 574, in get_config
    cur.execute("ALTER TABLE config ADD COLUMN %s BLOB" % (field))
sqlite3.OperationalError: no such table: config


$ sudo python3 ./empire 
  File "./empire", line 35
    print '[*] Fresh start in docker, running reset.sh for you'
                                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('[*] Fresh start in docker, running reset.sh for you')?
$ sudo python3 ./empire 
File "./empire", line 35
    print '[*] Fresh start in docker, running reset.sh for you'
                                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('[*] Fresh start in docker, running reset.sh for you')?
bal33p:Empire laniakea$ sudo python3 ./empire 
  File "./empire", line 35
    print '[*] Fresh start in docker, running reset.sh for you'
                                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('[*] Fresh start in docker, running reset.sh for you')?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Try
`$ sudo python2.7 ./setup/setup_database.py`
then
`$ sudo python2.7 ./empire`

**Comment by Bal33p** [comment]
Perfect! That did the trick... Thank you, much appreciated.

**Comment by xorrior** [comment]
Thanks @ThePirateWhoSmellsOfSunflowers
