### ISSUE TITLE
Authorization Code is malformed or invalid.

### ISSUE THREAD

**Issue by MrZanerson** [EmpireProject/Empire#1239]
## Empire Version

2.3.0 

## OS Information (Linux flavor, Python version)
Ubuntu 16 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Followed your process and unable to create listener e.g execute after set the app client id and set auth code and execute fails with response 400. 

## Screenshot of error, embedded text output, or Pastebin link to the error

!] Something went wrong, HTTP response 400, error code [70000]: AADSTS70000: Transmission data parser failure: Authorization Code is malformed or invalid.
Trace ID: 08117e67-19da-xxxxxxxxxx
Correlation ID: 2ef7d39c-4b4a-442f-xxxxxxxxx
Timestamp: 2018-09-23 10:54:55Z

**Comment by mr64bit** [comment]
Hello,
Are you sure you copied just the auth code from the URL? (it's usually followed by an "lc" parameter, which isn't part of the auth code)

**Comment by pentestitde** [comment]
I have the same problem. I'm sure that I provided the correct auth code.
[!] Something went wrong, HTTP response 401, error code [70002]: AADSTS70002: The provided request must include a 'client_secret' input parameter.
Trace ID: 061d33cf-34dc-4e8c-9f26-xxxxxxx
Correlation ID: f284e53c-4f29-47d4-9416-xxxxxx
Timestamp: 2018-12-01 21:21:56Z

**Comment by mr64bit** [comment]
Fix has been pushed to `dev`, gist has been updated with instructions.
https://gist.github.com/mr64bit/3fd8f321717c9a6423f7949d494b6cd9
Thanks.
