### ISSUE TITLE
What's wrong

### ISSUE THREAD

**Issue by LIZySARA** [EmpireProject/Empire#1257]
## Empire Version
DEV 

## OS Information (Linux flavor, Python version)
Ubuntu 16.04 X86 64 

## Screenshot of error, embedded text output, or Pastebin link to the error
![telechargement](https://user-images.githubusercontent.com/22563762/47364513-ca97e680-d6d9-11e8-86e8-e563280fcfcb.png)

**Comment by DakotaNelson** [comment]
Probably a python2/python3 issue. You're running this on a system that doesn't have English set as its language, correct?

Can you provide any information about how you're running empire? The launching command you're using? Python version?

**Comment by mr64bit** [comment]
Empire doesn't support Unicode right now unfortunately, sorry.
