### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by rootlord42** [EmpireProject/Empire#1264]
## Empire Version
latest

## OS Information (Linux flavor, Python version)
Kali Linux, Python3, pip2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
ran #~sudo ./install.sh

## Screenshot of error, embedded text output, or Pastebin link to the error

 `Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable
`

**Comment by condor-webdev** [comment]
Same error here on latest kali with pip 18.1 on python 2.7:
```
Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable
```

**Comment by condor-webdev** [comment]
> I'm getting the same issue... tried ./reset.sh and./install.sh again, still not working. Unsure if it's related, but during the installation I see:
> 
> ```
> ./Empire/setup/install.sh: line 114: cd: ./setup: No such file or directory
> --2018-10-31 16:59:34--  http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
> Resolving ftp.us.debian.org (ftp.us.debian.org)... 208.80.154.15, 128.61.240.89, 64.50.233.100, ...
> Connecting to ftp.us.debian.org (ftp.us.debian.org)|208.80.154.15|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2018-10-31 16:59:36 ERROR 404: Not Found.
> 
> dpkg: error: cannot access archive 'libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb': No such file or directory
> ```
> Looks like the debian site has updated and ...8u7 has been replaced by ...8u8.

I changed this manually in the installer but the problem still remains

**Comment by bisack** [comment]
I also fixed the libssl error manually. Ran into an issue with urllib, which was also broken. Manually installed urrlib3 1.23 (pip install urllib3==1.23) to downgrade that, and ran into 'NoneType' error.

**Comment by condor-webdev** [comment]
> I also fixed the libssl error manually. Ran into an issue with urllib, which was also broken. Manually installed urrlib3 1.23 (pip install urllib3==1.23) to downgrade that, and ran into 'NoneType' error.
> 
> Edit:
> As per #1266 - downgrading to 1.22 instead of 1.23 seems to have fixed the issue. You will have to either run the reset.sh script or delete Empire and do a fresh install, but then everything worked for me from there.

Thanks, was just perfect, i modified it in requirements.txt and now it works.

**Comment by bucky67gto** [comment]
try running reset.sh in the setup folder.  Hope it helps

**Comment by mr64bit** [comment]
Should be fixed now in `dev`, closing.

**Comment by aakifshaikh** [comment]
root@kali:~/tools/Empire# ./empire 
Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/root/tools/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

Tried running reset and then install - still not working
