### ISSUE TITLE
urllib3 error with version 1.24

### ISSUE THREAD

**Issue by mcjon3z** [EmpireProject/Empire#1266]
## Empire Version
cloned from commit 92fcf43

## OS Information (Linux flavor, Python version)
Debian Stretch-20181011 (latest) docker image
Python 2.7.13 installed from repo

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Upon launch, dependency error relating to urrlib throws and crashes. Some google searches found similar errors associated with urrlib upgrades from 1.23 to 1.24 which indicates that there is a bug introduced in 1.24. 

Manually installing version 1.23 via pip in the dockerfile before running Empire setup corrects the issue and Empire launches fine.

## Screenshot of error, embedded text output, or Pastebin link to the error
```
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "./empire", line 1397, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 109, in __init__
    self.listeners = listeners.Listeners(self, args=args)
  File "/opt/Empire/lib/common/listeners.py", line 38, in __init__
    self.load_listeners()
  File "/opt/Empire/lib/common/listeners.py", line 63, in load_listeners
    self.loadedListeners[listenerName] = imp.load_source(listenerName, filePath).Listener(self.mainMenu, [])
  File "/opt/Empire//lib/listeners/onedrive.py", line 12, in <module>
    from requests import Request, Session
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/local/lib/python2.7/dist-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/local/lib/python2.7/dist-packages/requests/compat.py", line 47, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
root@ce11442b4acf:/opt/Empire#
```

**Comment by bisack** [comment]
I'm also running into this problem on Kali, not in Docker. Been spending the last couple days trying to fix various dependency issues in both the install and run time, including this one.
Manually installing 1.23 clears the error but empire still doesn't run.

**Comment by bisack** [comment]
Thanks, I will give that a try. Might help some of the other issues I have had as well.

**Comment by hktalent** [comment]
me too, in kali linux

**Comment by mcjon3z** [comment]
Doing a little more testing, it appears that the error is throwing out of the requests dependency which in Empire requirements is hardcoded at requests==2.18.4; Looking at the dependencies for requests, the current release version is 2.20 and it stipulates urllib3>=1.21.1,<1.25 which indicates it quite possibly has been tested to work properly with 1.24. Looking at the dependencies for requests v 2.18.4, it requires urllib3>=1.21.1,<1.23.

2.20 dependencies:
https://github.com/requests/requests/blob/master/setup.py

2.18.4 dependencies:
https://github.com/requests/requests/blob/v2.18.4/setup.py

If it doesn't break something else, updating Empire requirement for requests from 2.18.4 to 2.20 may resolve the issue. If I get some time this weekend, I may try throwing it into a docker image and playing around with it.

**Comment by bisack** [comment]
@mcjon3z - I suspected something like that might be the case, and I hope you had a chance to do some testing as this sounds like the more appropriate, or 'right way' to fix the issue. I mainly submitted my hack/fix to share with others who, like me, have workflows blocked by the issue.

**Comment by mcjon3z** [comment]
@bisack, still have not had a chance. Devs may wish to merge their preferred solution in the meantime cause there are several ways to skin this cat. 

Unfortunately this seems to be a common issue with many projects and any solution is likely going to have unforeseen impacts for some folks that have other projects using these dependencies...particularly with Kali and having a bunch of other python projects using pip to system instead of in virtual environments. 

Running Empire in docker has worked well for me and keeps it isolated from any locally installed code that may use different libraries. When given the option of using docker vs a virtualenv I generally go with docker and alias a startup script so you really can’t even tell it is running in a container.
