### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by aakifshaikh** [EmpireProject/Empire#1278]
## Host machine: MacOS High Sierra version 10.13.6
Kali-Linux-2018.4-vm-amd64
Python 2.7.15+

## Error screenshot below-

root@kali:~/tools/Empire# ./empire
Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/root/tools/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

## Found the same issue type reported previously (#1264 ), followed those steps but still not resolving.
I ran reset and then install again - didn't work

**Comment by ssnkhan** [comment]
Hi, I managed to get this running again in 2018.4 by:

`git clone https://github.com/EmpireProject/Empire.git` and then manually replacing both `setup/install.sh` and `setup/requirements.txt` from the `dev` branch here -- https://github.com/EmpireProject/Empire/tree/dev

Please let me know if this resolves the issue for you.

**Comment by aakifshaikh** [comment]
This can be closed. Thank you!

Aakif
