### ISSUE TITLE
Help Wanted/Quick question: What is  external/generate_agent for? and how do I use it?

### ISSUE THREAD

**Issue by lonewolf210** [EmpireProject/Empire#1282]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Kali 2018 newest

Sorry just basic question but what exactly is the external/generate_agent module for? I have got stagers to call back from target hosts on my test network and they are listed as agents. That combined with reading the agents wiki I was under the impression that agents are compromised hosts so what is this module for? Also it appears to be a powershell script but that's not what the output file extension is?

**Comment by mr64bit** [comment]
`generate_agent` gives you code for an agent that's already fully staged, that can start communicating with the server without having to go through the staging process. This agent shouldn't be executed at once, since I don't think Empire would handle two different agents ghosting each other pretty well.

**Comment by lonewolf210** [comment]
> `generate_agent` gives you code for an agent that's already fully staged, that can start communicating > with the server without having to go through the staging process. This agent shouldn't be executed at > once, since I don't think Empire would handle two different agents ghosting each other pretty well.

So it's for executing from the box  I am running Empire on? Like I have read the description on the module. I guess a better question is what is an Agent? I thought it was a compromised target host

**Comment by mr64bit** [comment]
Nope, it's for running on a compromised host.
An agent is Powershell or Python code you've got running on a remote host that talks to the Empire server and runs commands and other code for you.
The `generate_agent` module is for pretty specific scenarios where you can get code execution, but something is preventing you from staging an agent normally. Other than that, the results are the same as using any other stager.

**Comment by lonewolf210** [comment]
ahh thank you
