### ISSUE TITLE
Launcher code not working - Agent does not connect to Empire

### ISSUE THREAD

**Issue by zazazo** [EmpireProject/Empire#1283]
## Empire Version

2.5

## OS Information (Linux flavor, Python version)

Attacker : Kali
Victim : Windows 10 (Defender is disabled)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

-  I launched Empire and setup a http listener. 
-  I created a launcher with "launcher powershell http", copied its code (screenshot 1)
-  Pasted the code to my Victim CMD prompt. 

-> The CMD closes, but agent does not connect back to Empire. Nothing happens, Although I have disabled Windows Defender. 

## Screenshot of error, embedded text output, or Pastebin link to the error

<img width="1410" alt="screenshot 2018-12-10 at 16 12 22" src="https://user-images.githubusercontent.com/44822267/49722093-769b8e00-fc96-11e8-8ce0-934501c145a6.png">

<img width="1071" alt="screenshot 2018-12-10 at 16 13 47" src="https://user-images.githubusercontent.com/44822267/49722158-a185e200-fc96-11e8-86f9-ecfd8c5394d2.png">

**Comment by mr64bit** [comment]
You can try taking the "-w 1" out of the command, this will stop the window
from hiding itself when PowerShell launches. See if there's any helpful
information printed out.

If that doesn't help, here's a more thorough debugging method. Set Base64
to false in the launcher options, then create the launcher. Paste the
launcher code into a PowerShell console, but remove the first command.
($ErrorActionPreference
= "SilentlyContinue";) See if that runs and gets you an agent. If it
doesn't, it should at least provide a helpful error.

**Comment by eqhaleel** [comment]
Actually i disabled my windows defender and i got my agents...however windows defender detects and deletes the agents thereby preventing the agents to call the c2 server. Hence,i recommend the team to find a way to bypass the av please

**Comment by mr64bit** [comment]
Unfortunately, we don't have the manpower to work around Defender all the time. There's a new AMSI bypass in `dev` that works consistently however, you're welcome to try that.

**Comment by eqhaleel** [comment]
@mr64bit I'm using the dev as suggested but I don't know how to make use of the AMSI, can you please tell me how to do that? thanks
