### ISSUE TITLE
Creating a Linux service with systemd for Empire

### ISSUE THREAD

**Issue by ardabuyukkayaMOV** [EmpireProject/Empire#1284]
## Empire Version
 2.5

## OS Information (Linux flavor, Python version)
Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
**I love empire and I want to use empire listeners 24 hours online , when I logout ssh session 
my empire server shuts down so...**

**I try to make little service script but I get this error** 

## Screenshot of error, embedded text output, or Pastebin link to the error
<a href="https://ibb.co/LJ78BZQ"><img src="https://i.ibb.co/pRFxNLW/Ekran-Al-nt-s.png" alt="Ekran-Al-nt-s" border="0"></a>
## THİS İS MY SCRİPT
<a href="https://imgbb.com/"><img src="https://i.ibb.co/8xvwKnW/2.png" alt="2" border="0"></a>

**Comment by mr64bit** [comment]
For keeping Empire alive without an SSH connection, I'd recommend `screen` or `tmux`.

If you really want to run it as a service, try adding this to your unit file:
`WorkingDirectory=/root/Empire`

**Comment by ardabuyukkayaMOV** [comment]
> For keeping Empire alive without an SSH connection, I'd recommend `screen` or `tmux`.
> 
> If you really want to run it as a service, try adding this to your unit file:
> `WorkingDirectory=/root/Empire`

Thank you for your replay 

Do you now how to use screen or tmux.

I also get this error when I use as a service

<a href="https://ibb.co/7gJxWSd"><img src="https://i.ibb.co/2870tF1/eyy.png" alt="eyy" border="0"></a>

**Comment by mr64bit** [comment]
`Type=forking` tells systemd that the main process will exit once the service is started, which Empire doesn't do. Change it to `Type=simple`.
