### ISSUE TITLE
PSInject needs fix installed and agent throws error in Empire.

### ISSUE THREAD

**Issue by PoSHMagiC0de** [EmpireProject/Empire#1285]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Kali Linux..Latest

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
PSInject needs to be updated to include fix so it functions again submitted by Mr64bit in PSInject repo.
[](https://github.com/EmpireProject/PSInject/pull/2)

I applied fix and that fixed inject for Windows 7.  Works as intended.
For Windows 10 latest updates PSInject does work but payload throws errors in Empire.  Will be listed below in txt file.
I decoded payload it runs by adding a print line to module so I can catch it to decode.  Ran it straight on Windows 10 machine and it works.  I tried injected it on Windows 10 machine and it fails.  Tested psinject with my own payload and it works.  Tried to use my own payload to download decoded stager from previous step to then run in case payload is too big but it fails also.

## Screenshot of error, embedded text output, or Pastebin link to the error
[Erroronwin10launch.txt](https://github.com/EmpireProject/Empire/files/2710638/Erroronwin10launch.txt)

## Any additional information
I noticed through my testing with psinject powershell module itself it does not like single quotes "'" in the payload anywhere.  It works fine with escaped double quotes.  I only seen this on Windows 10.  Have not went through stager to see if I see anything that could be a breaker.

**Comment by mr64bit** [comment]
The `dev` branch has the PSInject fix, but I'm not sure if that's the issue here. I've occasionally had issues like this, but they were never consistent enough for me to debug it.

**Comment by PoSHMagiC0de** [comment]
Yeah, I concatenated 2 issues in 1.  Wanted to let known I was using the one with your fix to clarify.
This issue is separate from the fix you did.  I used to have intermittent issues a few months back before the fix was needed but now I can't get one agent to fire off manually or automatically with the inject though I can handcraft stuff to run injected and it runs fine including downloading script I made to run to test.  All of the testing I did was on Windows 10 since Windows 7 works fine.

**Comment by PoSHMagiC0de** [comment]
Adding a screenshot.  I downloaded the dev to try that branch.  This time instead of injecting into Notepad I injected into a command prompt.  Getting same type of error in Empire but in the cmd prompt I got errors I am pasting below.
![empirecmderror](https://user-images.githubusercontent.com/22720816/50460137-ed3bbb00-0927-11e9-9b84-b4ec86af1a52.PNG)

**Comment by phra** [comment]
@PoSHMagiC0de see #1286 in order to fix method on null-valued expression error.

**Comment by PoSHMagiC0de** [comment]
Just wanted to say that after I did a git pull of the most recent dev branch, psinject now works fine in Windows 10 now.  This is can be closed.  Now just need to get the correct version of Invoke-Mimikatz.ps1 into the commit..the one with the 2018 date in it.  I keep a copy of it to re-add to Empire when I pull/clone it.  That is for another issue tracker though.  :-)


So, I would say fixed in current dev branch for psinject.

**Comment by phra** [comment]
FYI the update of Invoke-Mimikatz is in this PR: https://github.com/EmpireProject/Empire/pull/1294
