### ISSUE TITLE
Works fine on LAN but not over internet

### ISSUE THREAD

**Issue by PinkPantherX** [EmpireProject/Empire#1295]
## Empire Version
2.5
## OS Information (Linux flavor, Python version)

Attacker: Kali linux  Target: Win10 & Win7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I created a http listener and launched a script on win10 (defender on, firewalls on, avast on). I got the connection and everything works fine, in local netwok.
Then I tried with public IP:
Host http://publicIP:443
Port  443
Bind IP 192.168.1.5 (tried with 0.0.0.0 also)

I'm using vpn (static IP) on Kali with port 443 opened. Tested it on canyouseeme.org and the port is opened. 
When I launch the script, nothing happends, I don't get an agent, Avast is not alerted, Defender also.
I thought that maybe firewals are stoping it...I've disabeld all the firewalls and still don't get an agent.
Same thing on win10 and win7.
Anyone has a clue?

![screenshot from 2019-01-03 17-50-10](https://user-images.githubusercontent.com/35148783/50650554-1213dc00-0f81-11e9-920a-387010a036c0.png)

**Comment by mr64bit** [comment]
If your VPN is runnin on the kali machine, you'll need to listen on the IP of that virtual adapter rather than the LAN IP. But unless you have a reason not to, listening on `0.0.0.0` is easier, and works just the same.

Try running Empire with `--debug 2` and make http requests to your public IP:port from the target machine using curl or a browser, see if you get a response.

**Comment by PinkPantherX** [comment]
Tnx for the answer man...I've set up BindIP with the vpn's local IP and still no success. I've also made a http request using a browser from the target machine and didn't get the response. I'm so freaking close. There must be something with the IP settings and the ports, just cant figure it out...

![screenshot from 2019-01-04 11-04-19](https://user-images.githubusercontent.com/35148783/50683956-32d94180-1014-11e9-993e-496e916aebc9.png)
![screenshot from 2019-01-04 11-49-34](https://user-images.githubusercontent.com/35148783/50685382-41762780-1019-11e9-9478-0d1c97821bd9.png)

**Comment by mr64bit** [comment]
Now I see another issue. In your second screenshot, you have CertPath specified, making this an HTTPS listener. You'll need to change your Host option to start with `https://`, and when you're testing in a browser you need to specify `https://` as well.

**Comment by PinkPantherX** [comment]
Nothing helped..I've tried to test it with https://, no result. I did reset.sh on Empire and started all over, this time without CertPath, and still no agent. I even switched the server but still nothing. I think its something about redirecting local IP... I must figure it out. Apreciate any help.

**Comment by mr64bit** [comment]
You can do forwarding with iptables, but at this point it seems the packets aren't even reaching your machine. (unless you enabled a local firewall on the Kali box)
How are you forwarding traffic from the public IP through the VPN? That's where I'd start looking first.

**Comment by PinkPantherX** [comment]
I thought that just by opening port 443 on vpn will be enough fo forward traffic and that Empire would do the rest. My bad. I found some iptables rules for openvpn on Github and I set them up, but nothing seems to work yet. The firewall is not on. I think the proper forwarding is the problem..

**Comment by mr64bit** [comment]
Because your VPN is using private address space, you'll need to set up NAT
masquerading as well if you haven't already.

**Comment by PinkPantherX** [comment]
Ok, will try

**Comment by generatorada** [comment]
iptables -t nat -A PREROUTING -p tcp -d youip --dport 443 -j DNAT --to-destination 10.30.126.30:443

And 
ipforward 1

Check in 
2ip.ru/check-port/?port=443
