### ISSUE TITLE
Feature request: interact all

### ISSUE THREAD

**Issue by PabloBrusseel** [EmpireProject/Empire#1298]
Would be nice if you could use a particular module on all agents that speak the same language.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
There is a undocumented workaround to automatically run module on connect. Just try to set `all` as agent
```
(Empire) > usemodule powershell/collection/screenshot
(Empire: powershell/collection/screenshot) > 
(Empire: powershell/collection/screenshot) > set Agent all
(Empire: powershell/collection/screenshot) > 
```
It will automatically run the screenshot module for all the agents currently connected.

PS : Like #1299, I don't know if this workaround still works.

:sunflower:

**Comment by PabloBrusseel** [comment]
Perfect! Works like a charm!

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Nice, let me know if it also works for `autorun`
