### ISSUE TITLE
Feature request: run on connect

### ISSUE THREAD

**Issue by PabloBrusseel** [EmpireProject/Empire#1299]
It would come in handy to specify one or more pre-configured modules that would run when the agents connect back to your Empire framework

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
There is a undocumented workaround to automatically run module on connect. Just try to set `autorun` as agent
```
(Empire) > usemodule powershell/collection/screenshot
(Empire: powershell/collection/screenshot) > 
(Empire: powershell/collection/screenshot) > set Agent autorun
(Empire: powershell/collection/screenshot) > 
```
It will automatically run the screenshot module for all the new agents.

:sunflower:

**Comment by mr64bit** [comment]
Hi Pablo, hope this worked for you.
Closing issue.
