### ISSUE TITLE
Obfuscated UserAgent in stage1

### ISSUE THREAD

**Issue by StayPirate** [EmpireProject/Empire#1308]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Debian 9 (stretch)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
The UA is obfuscated among the rest of the payload, it could lead to an easy detection rate from a network point of view if HTTP listener is in place.

## Screenshot of error, embedded text output, or Pastebin link to the error
```paRam($S, $SK, $UA = 'MOzIlla/5.0 (WINDoWS NT 6.1; WOW64; TRiDeNT/7.0; rv:11.0) lIkE GEcKo')FUnCtiON COnVeRtTo - RC4ByteSTrEaM {```

**Comment by mr64bit** [comment]
Nice catch, thanks.
