### ISSUE TITLE
ImportError: No module named pydispatch

### ISSUE THREAD

**Issue by mesnuuu** [EmpireProject/Empire#1310]
## Empire Version
2.3.0

## OS Information (Linux flavor, Python version)
kali linux 2018.4

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/opt/Empire/lib/common/empire.py", line 14, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch

**Comment by mesnuuu** [comment]
**i ran this command .** 
pip install pydispatcher
--------------------------------


```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pydispatcher
  Using cached https://files.pythonhosted.org/packages/cd/37/39aca520918ce1935bea9c356bcbb7ed7e52ad4e31bff9b943dfc8e7115b/PyDispatcher-2.0.5.tar.gz
Building wheels for collected packages: pydispatcher
  Building wheel for pydispatcher (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/88/99/96/cfef6665f9cb1522ee6757ae5955feedf2fe25f1737f91fa7f
Successfully built pydispatcher
Installing collected packages: pydispatcher
Successfully installed pydispatcher-2.0.5
```
---------------------------------------------------------------------------------------------

**Now this error when try to run empire .** 


> Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/opt/Empire/lib/common/empire.py", line 34, in <module>
    import agents
  File "/opt/Empire/lib/common/agents.py", line 64, in <module>
    from zlib_wrapper import compress
ImportError: No module named zlib_wrapper

**Comment by mesnuuu** [comment]
now this error : 
``Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

**Comment by mesnuuu** [comment]
now this error : 

`Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable
`

**Comment by mesnuuu** [comment]
after ./reset.sh 

`Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 107, in __init__
    self.stagers = stagers.Stagers(self, args=args)
  File "/opt/Empire/lib/common/stagers.py", line 43, in __init__
    self.load_stagers()
  File "/opt/Empire/lib/common/stagers.py", line 68, in load_stagers
    self.stagers[stagerName] = imp.load_source(stagerName, filePath).Stager(self.mainMenu, [])
  File "/opt/Empire//lib/stagers/windows/backdoorLnkMacro.py", line 2, in <module>
    from xlutils.copy import copy
ImportError: No module named xlutils.copy
`

**Comment by baegmon** [comment]
Had the same problem, "ImportError: No module named pydispatch" is due to an issue with the latest version of pip and pyinstaller.

Clone the dev branch and do the usual setup: git clone -b dev https://github.com/EmpireProject/Empire

Tested on Kali 2018.4

**Comment by mesnuuu** [comment]
> Had the same problem, "ImportError: No module named pydispatch" is due to an issue with the latest version of pip and pyinstaller.
> 
> Clone the dev branch and do the usual setup: git clone -b dev https://github.com/EmpireProject/Empire
> 
> Tested on Kali 2018.4
thanks for your reply . 
should i delete previous folder of Empire or i have to uninstall first ? and what is correct procedure of doing so ?

**Comment by kazoo123** [comment]
I'm having same issue.. Do you get to fix your own. I have tried the above command mentioned above but still same error. Please enlighten me on how you do it

**Comment by mesnuuu** [comment]
> I just removed the previous installation and cloned the dev branch.
> 
> Maybe try removing all installations, downgrading pip to 18.1, install all modules via pip (pyinstaller, pydispatch etc) and then run the setup command again.

1- i removed previous installation ( deleted empire folder ) . i did correct ? 
2- when i cloned dev bracnh , in did not see setup.sh file in it . so unable to proceed further .

**Comment by antonytuff** [comment]
i have been having this error any help??
traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/root/Empire/lib/common/helpers.py", line 50, in <module>
    import iptools
ImportError: No module named iptools

**Comment by christophetd** [comment]
Same issue here. Will use the Docker image for now

**Comment by qwertyMu** [comment]
I solved it by cloning the dev branch as described above, then cd into setup and running ./install.sh

**Comment by mr64bit** [comment]
@mesnuuu, clone Empire like normal, then do `git checkout dev`. Run `setup/install.sh`, and you should be good. (may need to downgrade pip to 18.1)

**Comment by mesnuuu** [comment]
> @mesnuuu, clone Empire like normal, then do `git checkout dev`. Run `setup/install.sh`, and you should be good. (may need to downgrade pip to 18.1)

thanks a lot . it worked

**Comment by Allevon412** [comment]
> @mesnuuu, clone Empire like normal, then do `git checkout dev`. Run `setup/install.sh`, and you should be good. (may need to downgrade pip to 18.1)

This did not work for me... anyone else have a suggestion? Also how do yo uninstall empire? Do you just delete all the files or is there an actual uninstall command?

**Comment by MMquant** [comment]
On `Linux kali 4.19.0-kali5-amd64` fully upgraded on 16-07-2019 following works:
```
# pip install --user --upgrade pip==18.1
# git clone -b dev https://github.com/EmpireProject/Empire.git
# cd Empire/setup && ./install.sh
```

**Comment by Kruxinator** [comment]
Use
```
apt install python3-pydispatch
```
instead of `pip3 install pydispatch`. Worked for me!
