### ISSUE TITLE
HTTP Listener fails to start Errno13

### ISSUE THREAD

**Issue by saebyeolbe** [EmpireProject/Empire#1311]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
Kali Linux on AWS instance

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When trying to create a http listener, I get hit with the error seen below, Errno13. I have tried to set the CertPath as Empire/data, however the same error message shows. I have tried changing the Host option to my AWS EC2 elastic IP, but it does not help either.

## Screenshot of error, embedded text output, or Pastebin link to the error

![image](https://user-images.githubusercontent.com/33109196/51660250-18c5ca00-1fe8-11e9-9d55-a0f9c1efb763.png)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
`Listener startup on Port 80 failed: Permission denied`, I think you forgot the launch Empire as root. Anyway, you should avoid to use Empire as root and use it behind a reverse proxy or a NAT/PAT firewall.

:sunflower:

**Comment by saebyeolbe** [comment]
Oh my god... I'm so dumb! I'm used to logging in as a root on my VirtualBox Kali VM but I didn't think to sudo on EC2. Thank you very much!
