### ISSUE TITLE
Invoke-Kerberoast no hash loaded

### ISSUE THREAD

**Issue by headlessfish** [EmpireProject/Empire#1313]
Hi,

The  invoke-Kerberoast script does not seem to output hashes in the correct format. Whether I use the default format (John) or hashcAt, the output is the same, and neither is crackable loaded into hashcAt or John. It just tells me that no hashes are loaded. Is there anything I can do to fix this?

**Comment by mr64bit** [comment]
Fix has been merged to `dev` (#1304)
