### ISSUE TITLE
Empire is not starting (HELP)

### ISSUE THREAD

**Issue by kazoo123** [EmpireProject/Empire#1316]
Can someone please help me, I've spent more than 48hrs still didn't solve the issue, 
I got this error when i tried to lunch Empire after installing..

traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Downloads/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/root/Downloads/Empire/lib/common/helpers.py", line 50, in <module>
    import iptools
ImportError: No module named iptools

Your contributions would be appreciated.
Thanks

**Comment by kazoo123** [comment]
I manage to solve the above query but right now am having to issue (Error)

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Downloads/Empire/lib/common/empire.py", line 14, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch

Kindly help

**Comment by mr64bit** [comment]
Did you encounter any errors while running `setup/install.sh`?
Try running `pip install -r setup/requirements.txt`, this will install all the needed python libraries.

**Comment by kjoon41** [comment]
follow as below; (my english is very poor.)
1.python -m pip install SomePackage      >next> ./reset.sh 
2.pip install -r pydispatch  >next> ./reset.sh (if the shown other ImportError: No module named xxxxx)
3.pip install -r "xxxxx"
......

**Comment by antonytuff** [comment]
Kjoon41 any help on how I can fix this one??

traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/root/Empire/lib/common/helpers.py", line 50, in <module>
    import iptools
ImportError: No module named iptools

**Comment by ekisa** [comment]
For anyone having trouble during m2crypto installation;
I have managed to resolve the issue by this
pip install swig

**Comment by mr64bit** [comment]
Closing as a duplicate to #1323, see fixes there.
