### ISSUE TITLE
Module Missing  ./empire", line 13, in <module> Please help

### ISSUE THREAD

**Issue by antonytuff** [EmpireProject/Empire#1317]
I have been having this issue during Empire Installtion
Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/opt/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/opt/Empire/lib/common/helpers.py", line 50, in <module>
    import iptools

**Comment by mr64bit** [comment]
Try running `sudo pip install -r setup/requirements.txt`, see if that completes successfully and try starting Empire again.

**Comment by CptOfEvilMinions** [comment]
1. pip install pip==18.1 
1. ./setup/instal.sh

**Comment by mr64bit** [comment]
Addendum to what the Captain said:
Switch to the dev branch, there are a bunch of install fixes there.
I'm gonna close this, since this should fix your issue, but if not, feel free to re-open it.
