### ISSUE TITLE
No module found pydispatch?

### ISSUE THREAD

**Issue by agrawalsmart7** [EmpireProject/Empire#1318]
I have tried to install Empire on Kali Linux. I first install all the dependencies which are mention in requirements.txt file. 

`pip install -r requirements.txt`

When I run Empire what I saw an error 

`Import-Error:- No module found pydispatch`

But when I tried `pip install pydispatch`

it says already installed. Now I don't know why I am getting this error.

Thanks, looking for anyone who can guide me in this.

**Comment by sh4hin** [comment]
Fix it using the below steps:
1- apt-get install python-pyinstaller python-pydispatch zlib_wrapper macholib
2- go to setup folder and run the reset.sh would fix the issue.

cheers

**Comment by agrawalsmart7** [comment]
Thanks, it solved my problem.
