### ISSUE TITLE
Error while excuting Empire

### ISSUE THREAD

**Issue by hchadli** [EmpireProject/Empire#1320]
Hi,

I just installed the latest version of Empire and I'm getting this error messages. This is when I want to execute it. 

```
Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/opt/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/opt/Empire/lib/common/helpers.py", line 50, in <module>
    import iptools
ImportError: No module named iptools
```
I appreciate your help.

Many thanks,

Chadli

**Comment by JonA-01** [comment]
Go to the setup directory _Empire/setup/_,

Run the following command:
`pip install -r requirements.txt`

Go back into the Empire Directory _Empire/_

Re-execute empire.
`./empire`

**Comment by hchadli** [comment]
@JonA-01 you're the best, thanks
It solved my problem.
Thanks again.
