### ISSUE TITLE
Not being able to run empire

### ISSUE THREAD

**Issue by rustyanera** [EmpireProject/Empire#1330]
I have installed all the requirements and done both of the setups but when i try run empire it dosent start and says:

 Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/root/Empire/lib/common/helpers.py", line 50, in <module>
    import iptools
ImportError: No module named iptools

Please Help.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Please use the Github search function : #1320

**Comment by Nikhithx86** [comment]
pip install iptools

**Comment by rustyanera** [comment]
hey thanks but now im getting an error saying:

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/empire.py", line 14, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch

I tried to do pip install it worked but this time it just says this.

**Comment by mr64bit** [comment]
You can keep doing `pip install` for each new import failure, but running `setup/install.sh` if you haven't already is a much faster solution.

What OS are you running? If you already ran `setup/install.sh` but it failed for some reason, `pip install -r setup/requirements.txt` should get you all the python packages you need.

**Comment by rustyanera** [comment]
Thanks I'm running kali linux and I've tried that and it didn't work I did the pip install on ip tools and it worked but the new one doesn't I'll try latter busy atm thanks :)

**Comment by rustyanera** [comment]
mr64bit it installed but for some reason its showing that its not installed and still says the same thing...

**Comment by rustyanera** [comment]
Fixed i got it I just did a reset from the setup folder and it worked and its running. Thanks to you all :)

**Comment by rustyanera** [comment]
1. sudo pip install <things you need>
2. update python (I had python 2.7 then updated to 3)
3. update pip (If needed)
4. go to setup folder and type "sudo pip3 install -r requirements.txt" 
5. now inside the setup folder type "sudo ./reset.sh"
6. if empire starts type exit and try run from main folder, otherwise idk.
Hope this helps someone that has this problem :)
