### ISSUE TITLE
ReflectivePick updated source code

### ISSUE THREAD

**Issue by RedSec-Shay** [EmpireProject/Empire#148]
Hello,
I see the Reflective Pick dll was updated  4 months ago with "updated dlls to fix bug in injection and dll payload injection"  (commit 123a2435a7d0db63d6f0fd4f03ebf1cf53c23626)
looking at tje reflective pick source code in the power pick repository I see the code was updated a year ago (does not contain the latest fix applied to the binary) . 
could you kindly let me know where can I find the updated reflective pick source code containing the fix .
I'm want to embed stageless agent into the reflective pick (bypassing the 1200 char limitation ). 

Thanks.

**Comment by enigma0x3** [comment]
Hey RedSec-Shay,
We are going to get the code cleaned up and then create a place within the Empire project to store it for future viewing. We will push it once we work out some internal logistics on the best place to maintain it going forward. 

Thanks!

**Comment by RedSec-Shay** [comment]
Is there a place where I can find the updated Reflective Pick source ?  
Also , how is empire currently replacing (patching) the embedded powershell code ? (Invoke-PSInject.ps1???)

**Comment by enigma0x3** [comment]
It currently searches for a string in the DLL and patches in commands. We are working on a complete rewrite of the dlls and will publish the source once that is finished.

Sorry for the delay!

**Comment by RedSec-Shay** [comment]
Thank you for updating,I look forward seeing that updated code . you guys are doing amazing work.

**Comment by HarmJ0y** [comment]
We still don't have movement on this but it's not forgotten- the code will likely be pushed post BlackHat/Vegas once the PowerPick/ReflectivePick projects are consolidated to a new repo.

**Comment by HarmJ0y** [comment]
pinging @leechristensen as he's the new master of that source

**Comment by enigma0x3** [comment]
@RedSec-Shay,
@leechristensen just finished re-writing this. We should have it up on Github soon.

**Comment by enigma0x3** [comment]
pinging @leechristensen :)

**Comment by xorrior** [comment]
@RedSec-Shay We should have the source code soon....... ;)

**Comment by xorrior** [comment]
https://github.com/EmpireProject/PSInject
