### ISSUE TITLE
Ability to stop download

### ISSUE THREAD

**Issue by mubix** [EmpireProject/Empire#161]
Just in case a file is attempted to download that is too large, downloads are currently blocking so no other commands get through to stop the job.

**Comment by HarmJ0y** [comment]
We'll look into it, unfortunately it won't be a simple fix due to how the downloads are currently architected. We'll see if we can move it into a background job tasking at some point.

**Comment by mubix** [comment]
I understand, hence the reason for asking for the ability to simply stop the download rather than backgrounding, if I make the mistake and realize too late that I've started a download on a 20GB file, I'm basically up * creek until it finishes

**Comment by HarmJ0y** [comment]
Agreed on the request. We want to support this, just might take a bit of time based on the current architecture.

**Comment by xorrior** [comment]
@mubix This has been added for the powershell agent https://github.com/EmpireProject/Empire/commit/c27a2d9c604a624f5fe78f6f395b7cf27de52e9c. I will work on getting background downloads into the python portion soon. You will notice downloads will be somewhat slower. Also, the downloads are launched into a separate AppDomain, so the job is not aware of any modified variables in the agent. Whatever has been set for the Delay/Jitter, that is what the download job will use to chunk the data. So be wary of decreasing the delay after issuing a download command, this might cause the download to go much slower.

**Comment by xorrior** [comment]
Sorry nvm, back to the drawing board.

**Comment by xorrior** [comment]
Completed for the powershell agent in https://github.com/EmpireProject/Empire/pull/638
