### ISSUE TITLE
Feature Request: Multiple Hosts

### ISSUE THREAD

**Issue by mubix** [EmpireProject/Empire#162]
Allow for multiple targets in the IPs and enable trying each before dying

**Comment by HarmJ0y** [comment]
for what component exactly, the stagers or another component?

**Comment by mubix** [comment]
launchers, primarily, I don't like metasploit's current point of needing to add transports after a session is active, it takes too much care, especially when you are dealing with 5 or more sessions. I'd rather have a setting that I can set so that all of my persistence and shells have multiple IPs

**Comment by enigma0x3** [comment]
We will look into adding this. 

Thanks

**Comment by mubix** [comment]
@enigma0x3 sweet! thanks!

**Comment by xorrior** [comment]
This is not something we are going to address at this time.
