### ISSUE TITLE
A '$' in the staging key prevents the hop stager to negotiate

### ISSUE THREAD

**Issue by scufre** [EmpireProject/Empire#304]
## Empire Version

Empire 1.5
## OS Information (Linux flavor, Python version)

Debian 8.5 (amd64)
Python 2.7.9
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
1. Setup Empire and have the bad luck that the generated default staging key contains the '$' (dollar sign) character.
2. Setup a native listener
3. Setup a hop listener having the ''RedirectTarget'' option set to the previously setup native listener
4. Place hop.php in web server
5. Generate launcher for ''hop'' listener
6. Execute it in the target windows host

After a little time the agent should became active but instead nothing happens. Running in debug mode the following messages are shown:

```
 HttpHandler : [*] /index.asp?<removed hash> requested from None at <removed IP>
 Agents : [*] Sending stager (stage 1) to <removed IP>
 HttpHandler : [*] Post to /index.jsp?<removed hash> from <removed name> at <removed IP>
 Agents : [*] Agent <removed> from <removed IP> posted to public key URI
 Agents : [!] Invalid key post format from <removed name>
----------------------------------------
Exception happened during processing of request from ('<removed IP>', <removed port>)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/test/Empire-1.5/lib/common/http.py", line 119, in do_POST
    (code, responsedata) = self.server.agents.process_post(self.server.server_port, clientIP, sessionID, resource, postData)
TypeError: 'NoneType' object is not iterable
----------------------------------------
 HttpHandler : [*] Post to /index.php?<removed hash> from <removed name> at <removed IP>
 Agents : [!] Agent <removed> posted sysinfo without initial checkin`
```
## Any additional information

The issue seems to be in the stager_hop.ps1 file that has double quotes to hold the key, that does variable replacement. Instead the stager.ps1 does not have this issue.

```
--- a/Empire-1.5/data/agent/stager_hop.ps1   2016-03-31 18:34:46.000000000 -0300
+++ b/Empire-1.5/data/agent/stager_hop.ps1        2016-08-17 18:13:47.267027657 -0300
@@ -105,4 +105,4 @@

     # TODO: remove this shitty $server logic
     Invoke-Empire -Servers @(($s -split "/")[0..2] -join "/") -SessionKey $key -SessionID $ID -Epoch $epoch;
-} Start-Negotiate -s "REPLACE_SERVER" -SK "REPLACE_STAGING_KEY" -UA $u;
+} Start-Negotiate -s "REPLACE_SERVER" -SK 'REPLACE_STAGING_KEY' -UA $u;
```

**Comment by HarmJ0y** [comment]
So the default staging keys in master don't include '$' https://github.com/PowerShellEmpire/Empire/blob/master/setup/setup_database.py#L20, so unsure as to how that got in. As far as the hop.php code goes, it's being simplified in the 2.0 rewrite, which will be out in a few weeks at DerbyCon.

**Comment by xorrior** [comment]
@scufre this will no longer be an issue in Empire 2.0 as the '$' is no longer included in the character set for generation of the StagingKey.
