### ISSUE TITLE
Feature request: Expand on autorun capabilities

### ISSUE THREAD

**Issue by Viss** [EmpireProject/Empire#311]
Currently, the autorun functionality only runs one module. Asking empire to autorun another module means the first autorun is stomped. This is problematic for engagements where one is attempting to 'catch someone' who infrequently uses a machine and things need to happen the moment an agent phones home. Here is an example scenario

Target is an individual with multiple machines. One machine was left unattended and was subsequently backdoored. It is presumed that this individual is re-using passwords, so the intention is to extract credentials from one machine, then identify the other machine and attempt a connection - similar to how a typical virus/trojan/worm functions. In this case:
- install persistence for 3-4 times during the day, so that a shell can be attempted at various times, or upon "awakening" (maybe there's better tradecraft here. I wonder if you can do "when  user unlocks workstation" or "when machine comes out of sleep")
- sysinfo
- attempt mimikatz
- shell arp -a
- attempt uac bypass, or otherwise gain system privileges, and run new agent with higher privs

With the intention of returning to the console at a later time and "finding all of this information waiting for you", because maybe the target got up at 3am to do some work, and the agent fired, and did a bunch of stuff for you while you were asleep and the target was awake.

**Comment by HarmJ0y** [comment]
Right now this just isn't possible with the current code base. Even with the 2.0 rewrite I don't know if we'll be able to integrate it, but will keep it in mind.

**Comment by Viss** [comment]
so I've solved part of it: the multi autorun - I've started using the rest api and scripting stuff with just simple bash scripts and making queries against empire. At the moment, I just have a while loop that goes and harvests screenshots, then moves them into another directory for review. What would be really cool, is to, somehow (and this is the part I don't know how to do) trigger an action based on an incoming shell. Perhaps a new module that is a 'linker' module, which can just spit something out via the api to an external script, which simply triggers all the appropriate modules I'd like to autorun..

The second half is done, I'm using it now - I'm running a bunch of modules by hand, externally using the api. I just haven't noodled out the architecture for having a new module fire upon agent connect that tells the external script 'yo, you should run all your shit now'

Totally open to suggestions though :D

**Comment by xorrior** [comment]
Unfortunately, I don't think we will be able to support this request at this time.
