### ISSUE TITLE
uploading file consumes a lot of memory (20 Mb file -> 2 to 3 GB memory)

### ISSUE THREAD

**Issue by mynameisv** [EmpireProject/Empire#323]
![empiremem](https://cloud.githubusercontent.com/assets/17194500/18673243/5ed9e6ec-7f4b-11e6-9951-2be92d516b9f.png)
Empire 1.4, 1.5 and dev
Client OS : Windows 7 and 10

Hi,

I've found a strange behavior but i did not found any bug in the code explaining that.
Maybe it's a bad usage of PowerShell logic or PowerShell is not a good language to process binary data ;-).

TL;DR : uploading files bigger than 25MB consumes so much memory that it do not work on "normal" computer with Windows 7 and 10.

The problem appears in agent.ps1, when uploading a file, it consumes a lot of RAM and finally explodes. More precisely, it happens at several places:
- at the end of the function Get-Task, during the $result return
- during UTF8.GetString($data)
- during the call of Decrypt-Bytes in Process-Tasking
- during the call of Decode-Packet in Process-Tasking

For a 10MB file, the average memory consumption is :
- $result => 700 MB
- UTF8.GetString($data) => 700 MB
- Decrypt-Bytes => 2,5 GB
- Decode-Packet => 2,1 GB

For a 20 MB file, the average memory consumption is :
- $result => 1,3 GB
- UTF8.GetString($data) => 1,3 GB
- Decrypt-Bytes => 3,1 GB
- Decode-Packet => 2,4 GB

For files bigger than 25MB on a computer (Windows 7 and 10) with 4GB of RAM, it explodes.

Does anybody have the same behavior ?
Any idea about the reason and how to solve that ?

**Comment by killswitch-GUI** [comment]
@rvrsh3ll Will start trying to debug this issue. Thanks for the report, I will respond back with my findings!

**Comment by killswitch-GUI** [comment]
Confirmed, 12Mb upload spiked to 1GB of RAM usage.

**Comment by killswitch-GUI** [comment]
@mynameisv Still working this, I have free time today so Im going to dive into the agent side. Will report back soon

**Comment by mynameisv** [comment]
@killswitch-GUI  nice :-).
But don't you think it's a bug in powershell or a missuse of data type ?
$wc.DownloadData() returns an Array that's not a flexible data type ;-).

**Comment by xorrior** [comment]
So @killswitch-GUI and I have looked into the issue, it doesn't appear there is a concrete fix for this problem. Currently, all of the data in a file upload is passed to the agent in one exchange with the server. Uploads cannot be chunked like download jobs as there is no guarantee in the order of the data. Thus you could have issues with corrupted files. Going forward, the best solution would be to impose a file upload limit between 2-5 mb. I will do some testing and see what works best.

**Comment by xorrior** [comment]
Added a 1MB file upload limit.

**Comment by timothyleung1** [comment]
What is the best alternative to upload large size file? One way is to split the zip file into multiple files and pack them back on the server side. Any other ways?
