### ISSUE TITLE
Global list command does not tab complete

### ISSUE THREAD

**Issue by leesoh** [EmpireProject/Empire#326]
## Empire Version

1.6
## OS Information (Linux flavor, Python version)

elementaryOS 0.4, python 2.7.12
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

The global `list` command (`list agents`, `list listeners`) does not tab complete.

**Comment by xorrior** [comment]
Will be fixed in the next 2.0_beta push.
