### ISSUE TITLE
get_spn_tickets consumes all the memory

### ISSUE THREAD

**Issue by aarju** [EmpireProject/Empire#338]
## Empire Version

2.0_beta
## OS Information (Linux flavor, Python version)

Kali Rolling, Agent running on Windows 7
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

On a large domain (10,000+ users) I attempted to execute the get_spn_tickets module on an agent running as a normal user. The job executed, but never returned any data. After 20 minutes the workstation running the agent became unstable and I found that the powershell process running the agent was consuming 9GB of RAM and growing. I killed the process so I don't know if the data would have eventually returned.

I modified line 81 of get_spn_tickets.py to add the '-SPN' flag to the Get-NetUser module and this appears to fix the error with this module. In a large network with thousands of users with SPNs this may still be an issue.

**Comment by HarmJ0y** [comment]
We're working on a refactor/optimization for PowerSploit, which contains the PowerView code this module is based on. Scale testing is something notoriously hard to track down, but after the refactor in the next month or two, we will update and see if this fixes the problem.

**Comment by xorrior** [comment]
Closing until this issue can be reproduced
