### ISSUE TITLE
DNS Communications

### ISSUE THREAD

**Issue by rvrsh3ll** [EmpireProject/Empire#342]
## Empire Version

2.0_beta
## OS Information (Linux flavor, Python version)

All

Create DNS Communications for all

**Comment by mlinton** [comment]
inspiration for the DNS channel - https://github.com/lukebaggett/dnscat2-powershell

**Comment by killswitch-GUI** [comment]
@enigma0x3 i have made some progress and re implementing a raw dns class. @rvrsh3ll you said no scappy so keep up with this and we will have a raw dns class for server and client side:  https://github.com/killswitch-GUI/dns_packet. will add the tests as well as I go for 'proper' dev

**Comment by enigma0x3** [comment]
You rock dude. I promise Ill get back to deving this feature soon :)

**Comment by killswitch-GUI** [comment]
Sweet! Nice part I think will be the options we have for DNS. Let's talk some time about the process of staging and what protocols we would like to see.

**Comment by xorrior** [comment]
Closing. No progress.

**Comment by vector-sec** [comment]
@killswitch-GUI I have a deep interest in this topic. If you're not still working on this would you share your progress with me so I could continue what you started?
