### ISSUE TITLE
2.0_beta api throws error when attempting to get list of agents

### ISSUE THREAD

**Issue by Viss** [EmpireProject/Empire#351]
## Empire Version

2.0

The API throws this error when attempting to ask it for a current list of agents

![image](https://cloud.githubusercontent.com/assets/1756255/19141711/7f9ca2e0-8b4c-11e6-8fab-d5a0e02f80e5.png)

**Comment by Viss** [comment]
similar error when trying to get /api/listeners

/api/modules returns expected results

**Comment by xorrior** [comment]
Hi,
The rest API is still a WIP and still in Beta. We will move our focus to this once we release version 2.
Thanks

**Comment by xorrior** [comment]
Unfortunately, the Rest API is not a priority at this time. Hopefully, at some point this year we can revive it.

**Comment by bneg** [comment]
The listeners table is different in Empire 2. Is "options" meant to be a "blob" or did the DB creation script go awry?

`CREATE TABLE `listeners` (
	`id`	integer,
	`name`	text,
	`host`	text,
	`port`	integer,
	`cert_path`	text,
	`staging_key`	text,
	`default_delay`	integer,
	`default_jitter`	real,
	`default_profile`	text,
	`kill_date`	text,
	`working_hours`	text,
	`listener_type`	text,
	`redirect_target`	text,
	`default_lost_limit`	integer,
	PRIMARY KEY(`id`)
);`
 vs.
CREATE TABLE `listeners` (
	`id`	integer,
	`name`	text,
	`module`	text,
	`listener_type`	text,
	`listener_category`	text,
	`options`	blob,
	PRIMARY KEY(`id`)
);
