### ISSUE TITLE
Extend feature to gather credentials/vault for all users 

### ISSUE THREAD

**Issue by Fist0urs** [EmpireProject/Empire#356]
## Empire Version

All
## OS Information (Linux flavor, Python version)

All 
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

At the moment, modules "enum_cred_store" and "vault_credential" only rely on agent user identity.
## Any additional information

It would be cool to be able to retrieve all credentials from credman and vaults for all users. This could be done by looking at the creds database for concerned users plaintext passwords (or SHA1 requested for DPAPI). If credentials could not be found, a message would be displayed saying "required credential for user X not found in creds database, please use module mimikatz to retrieve DPAPI SHA1 key for all users prior to use this module".

This would need to add SHA1 to credential database (currently it is not the case iirc) and a bit more of code within "enum_cred_store" and "vault_credential" (actually, all you need is user SID and plaintext or SHA1 secret)

**Comment by xorrior** [comment]
We won't be supporting this request at this time. Thanks
