### ISSUE TITLE
NAT to Listener not longer working with 2.0_beta

### ISSUE THREAD

**Issue by wiking-at** [EmpireProject/Empire#363]
## Empire Version

2.0_beta 
## OS Information (Linux flavor, Python version)

Ubuntu 14.04.4 LTS 
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

With the Empire main branch it is easily possible to use the listener behind a NAT Firewall. You just set the "Host" option to you public IP and NAT the agent communication to your private IP.

With the 2.0_beta it is no longer possible to launch a listener with the IP set to the Public IP. The listener seems to try to bind to the public ip and then fails as there is no interface which could be used.
## Screenshot of error, embedded text output, or Pastebin link to the error

![empire2 0_beta_nat](https://cloud.githubusercontent.com/assets/8046292/19238626/bc88bebe-8f02-11e6-8f2b-f9a22e8df09e.PNG)
there is nothing running on port 443. if i launch it with the host set to the private ip it works without a problem.

**Comment by xorrior** [comment]
Hi,
Can you just walk through the steps of how you're setting each of the options for the listener? Also can you retry this while running empire with the --debug 2 option?

**Comment by exFill** [comment]
I'm having the same issue but on 1.6.0 ... I just pulled a today.  I'm using NAT to a public address, in the past I'd set the public address in the listener Host value.

Here is the output when running --debug 2:
![2016-10-12_15-23-36](https://cloud.githubusercontent.com/assets/22801157/19326393/f52c0166-908f-11e6-9f6e-829ced132ccf.jpg)

I am running as root and there is no other process running on port 443.

**Comment by horllste** [comment]
stop the service running on that port and "execute" again

**Comment by exFill** [comment]
horllste ... I already said there are no other services running on that port in my previous post.

Ok, I think I fixed the issue ... the file lib/common/listeners.py was attempting to bind using the value set in the Host field (lhost), which in this case was the Public IP (the NAT IP) (error: Cannot assign requested address)

Here is the diff ... not sure if this is the best solution and I may have missed something entirely:

lib/common/listeners.py
145c145
<                 server = http.EmpireServer(self.agents, lhost=lhost, port=port, cert=cert_path)
---
>                 server = http.EmpireServer(self.agents, lhost="0.0.0.0", port=port, cert=cert_path)
569c569
<                 server = http.EmpireServer(self.agents, lhost=lhost, port=port, cert=certPath)
---
>                 server = http.EmpireServer(self.agents, lhost="0.0.0.0", port=port, cert=certPath)

**Comment by exFill** [comment]
Now with more time to review the code and issues I see this was fully discussed in #327 ... is the solution to move to 2.0_beta or is the 1.6 branch going to be fixed?

**Comment by rvrsh3ll** [comment]
Sound like you want to use the "foreign" type listener. Try that first.

**Comment by remrem29** [comment]
I have tried with the 2.0Beta on KALI2016-2 with no luck - there are more listeners in the Beta and tried HTTP, Http_foreign and Meterpreter, but no luck. So going back to Empire 1.5.

**Comment by rvrsh3ll** [comment]
running as root?

**Comment by remrem29** [comment]
Yes - As this was an test setup - all was done as root.

**Comment by curi0usJack** [comment]
+1 on this issue. fresh pull of 1.6. Public nat'd IP. Worked fine one 1.5. Exact same error message.

**Comment by Snizz** [comment]
Bump, same issue here.  Public NAT'ed VM. Verify ports are unused. Running as root.

**Comment by exFill** [comment]
So a work around that I've been using in 1.6 is to use the Public DNS name of the Public IP you want ... so if using AWS, look on the EC2 Management Console highlight your instance and copy/use the Public DNS as the Host

![2016-10-26_16-34-55](https://cloud.githubusercontent.com/assets/22801157/19746100/7608ef28-9b9a-11e6-8dcb-f7ac863ad1ef.jpg)

Then,
**(Empire: listeners) > set Host http://[publicDNS]**

**Comment by xorrior** [comment]
@wiking-at is this still an issue for you?

**Comment by wiking-at** [comment]
as far as i know it is still not possible to use a nat ip as the listener. 
so you always have to use a dns name as a workaround.

as dns queries may leave unwanted traces using an ip address might be beneficial in some scenarios.
also for first time users which don't know that using an ip is not possible this might be problematic.

with some earlier builds it was possible to use a nat ip as a listener.
i haven't tested if the issue is still there with the latest commits.

 were there some changes addressing this issue or are you asking in gerneral?

as i'm on a business trip currently i can't do technical validation currently.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
I always use Empire 2.0 and NAT without problem. For example, with the HTTP listener, the bind IP is totally decorrelated from Host staging's address. 

My setup is
`Agent -> My.Public.IP -> NAT -> 192.168.1.1:8080`

I use : 

> set Host http://My.Public.IP
> set BindIP 192.168.1.1
> set Port 8080

I have a NAT rule on my firewall to translate My.Public.IP:80 to 192.168.1.1:8080

TPWSOS

**Comment by xorrior** [comment]
@wiking-at  Can you give @ThePirateWhoSmellsOfSunflowers's suggestion a try and let us know?

**Comment by Gr3yCod3riX** [comment]
@ThePirateWhoSmellsOfSunflowers But, since on my server I'm using custom external port, and not the default 80(I can't change it).

For example (router is mapping 32333 to 1100):
mydnsaddress:32333
local address: 1100

 In that case how do you configure Empire to NAT properly? 
Thanks

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Ok, my bad, **address translation** is working, but not **port translation**.  
```
set Host http://My.Public.IP
set BindIP 192.168.1.1
set Port 8080
```
then I run `info` : 

`Host : http://My.Public.IP:8080`

so your issue #477 is perfectly valid. Need to find some time to perform tests and submit a PR.

TPWSOSF

**Comment by xorrior** [comment]
@wiking-at @ThePirateWhoSmellsOfSunflowers I think I have the answer to this problem. When using empire behind NAT configuration such as a home network, you will need to setup listeners as if you were using a redirector. You will need to have one listener set as http_foreign, with the "Host" option set to the public IP/DNS host name. Then you setup a normal http listener with the BindIP and Host options set to the internal IP address/host name. Provided that the NAT port forwarding configuration is correct, everything should work. I've testing this on a home router and confirmed that it works. When using hosted infrastructed behind a public NAT, like aws, you can use a normal http listener. Set the BindIP to the internal ip address and then the host option to the public IP/host name. Empire cannot bind to an IP address that is not on the host.

**Comment by Gr3yCod3riX** [comment]
@xorrior Hi. The problem I'm having is that I can not port translate external port when using Empire launcher to generate a payload. That payload just won't call back.  I have not stated it was an issue only for a home network. This was tested on my VPS, where for example metasploit works perfectly, which means it's not a networking problem. 

For example:
I have dns hostname with external port / **custom port**
That external port (for example is 35551) is mapped to my internal 1100 on my local IP
>>dnsHostname:35551 mapped to internal IP:1100<<

I have not found I way to call back to "dnsHostname:35551"

So, if there is a solution for this case can you please elaborate procedure for making Empire target my listener correctly. Or maybe I have missed something.

Thank you

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
@xorrior : I think your solution is a little bit complicated.

If I understand the code, the `host` field is only useful for the agent and the `bindIP` and `Port` only for the listener. Thus, I think you should totally decorrelate these options by removing [this](https://github.com/EmpireProject/Empire/blob/master/lib/common/listeners.py#L165-L203l) part and [this](https://github.com/EmpireProject/Empire/blob/master/lib/common/listeners.py#L216-L221) part.

 - For the first part, you can replace the logic by just checking if the supplied value is a valid url (e.g check if the supplied value is `[http(s)]://[ip|domain]:[port]`). You can also want to check if the user set Host with https if a CertPath is also set.

 - For the second part just check if Port is indeed a numerical value.

Finally, a user can easily use listeners with all network configurations with only one listener

```
Staging Host : https://example.com:443
Listener : 192.168.1.21:8443
```
or
```
Staging Host : http://example.com:1337
Listener : 192.168.1.21:8080
```

Maybe I'm wrong in my analysis,let me know ;)

**Comment by xorrior** [comment]
@ThePirateWhoSmellsOfSunflowers maybe my explanation was a bit more complicated then it needed it to be. Stand by for a (hopefully) better explanation.

**Comment by xorrior** [comment]
So to elaborate with pictures. When working behind a NAT in which the external and internal ports do not match, you will need to configure listeners as if you were using a redirector. Observe below. 

<img width="541" alt="foreignlistener" src="https://cloud.githubusercontent.com/assets/9156069/24776306/28f610e8-1aee-11e7-9a11-60810ec60362.png">

This foreign listener allows for your agents to stage and beacon through that hostname. Your nat config will redirect the traffic to your internal http listener that will be setup like so:

<img width="564" alt="internallistener" src="https://cloud.githubusercontent.com/assets/9156069/24776595/751d3a36-1aef-11e7-9811-051328579fdb.png">

In instances where the ports do not differ, you only need to setup one listener, with the BindIP and Host set accordingly (i.e. aws nat):

<img width="555" alt="sameports" src="https://cloud.githubusercontent.com/assets/9156069/24776721/1764d056-1af0-11e7-834b-2707b514173a.png">

If you are familiar with Cobaltstrike, you know that it would require a similar setup so that agents could stage through your redirector/NAT. 

@ThePirateWhoSmellsOfSunflowers your suggestion does make sense but that would be something we consider after the 2.0_beta merge with master. @wiking-at Can you give this solution a try?

**Comment by Gr3yCod3riX** [comment]
@xorrior This solution that you have described in steps is working as expected and @ThePirateWhoSmellsOfSunflowers suggestion is a good simplification for NAT settings. I hope this will be a part of 2.0 release. 

Keep up the good work

**Comment by Omardavinci** [comment]
how you show bindIp info? i dont see in any way.
