### ISSUE TITLE
http_hop listener cannot redirect to a listener that is using a self-signed certificate

### ISSUE THREAD

**Issue by atkinsj** [EmpireProject/Empire#369]
## Empire Version

2.0_beta, fresh pull
## OS Information (Linux flavor, Python version)

Local: Kali rolling updated
Remote: Windows Server 2012
Hop host: Debian 8, nginx1.10.1 + php7.0.11-1
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
1. Create a http listener using the default generated ssl cert in ./data/empire.pem
2. Create a hop listener that redirects to the http listener
3. Attempt to stage an agent
## Screenshot of error, embedded text output, or Pastebin link to the error

> 2016/10/09 21:53:45 [error] 6311#6311: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
> error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /var/www/html/admin/get.php on line 17
> PHP message: PHP Warning:  file_get_contents(): Failed to enable crypto in /var/www/html/admin/get.php on line 17
> PHP message: PHP Warning:  file_get_contents(https://192.168.0.118:9999/admin/get.php): failed to open stream: operation failed in /var/www/html/admin/get.php on line 17" while reading response header from upstream, client: 192.168.0.126, server: _, request: "GET /admin/get.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "192.168.0.118"

**Comment by HarmJ0y** [comment]
Ahhh k didn't think about this, that the php redirector needs to ignore self-signed certs as well. We're looking into this and hope to have a fix shortly.

**Comment by xorrior** [comment]
This may be working now with the fix from #569 . Just need to re-test.

**Comment by xorrior** [comment]
Fixed. cb26ae4
