### ISSUE TITLE
set StagingKey

### ISSUE THREAD

**Issue by bkr32** [EmpireProject/Empire#383]
## Empire Version

1.6.0
## OS Information (Linux flavor, Python version)

kali 2016.2
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

in some cases i may create a stager and may need to reboot my environment or reset the database, afterwhich i have to re-create my listener, each time a listener is created a StagingKey is also assigned to it and this key may not work with my old stager, 
to counter this i tried 
set StagingKey ### 
however after checking options the old staging key is still present, is it actually possible to change the staging key?

**Comment by enigma0x3** [comment]
I just tested and I am able to change it. What listener are you using? With the HTTP listener, I did: uselistener http
set StagingKey ####################
info
execute

**Comment by bkr32** [comment]
i did as following
listeners
options
set Name
set Host 
set Port
set StagingKey ######

**Comment by enigma0x3** [comment]
and if you type "info" after setting it, does the new key not show up?

**Comment by bkr32** [comment]
no still shows the old key

**Comment by rschwass** [comment]
I cant change my staging key either. I have an foreign listener and I need my staging keys to match, and the foreign listenre has a weird string. When I set the staging key its alwasy an md5 hash or so it looks. Weird.

**Comment by xorrior** [comment]
This is resolved in the 2.0_beta branch and will be subsequently resolved when that branch is merged with master.
