### ISSUE TITLE
[feature request] custom staging script/commands

### ISSUE THREAD

**Issue by thesle3p** [EmpireProject/Empire#398]
I sort of touched on this in #390 but would it be possible to make Empire run a script or command on a host before Empire stages the payload? Like as I mentioned in #390 run Invoke-Obfuscation on a windows host before staging out Empire? Or maybe with A macro attack run a script to check if it's being run in a sandbox before it writes out the payload. It would give Empire some added flexibility.

**Comment by rokups** [comment]
I can see this being useful for running a persistent keylogger and delivering keystrokes upon a connection and not having to maintain active connection to listen to keystrokes.

**Comment by xorrior** [comment]
I don't think we are going  to support this request at this time.
