### ISSUE TITLE
WorkingHours query

### ISSUE THREAD

**Issue by Xurse** [EmpireProject/Empire#406]
## Empire Version
1.6.0

## OS Information (Linux flavor, Python version)
Kali 2.0 , python 2.7.12+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

From my understanding, Workinghours in my listener settings will determine if the agent should poll back to my listener or generate any traffic. What I observe is that the agent remain active even when the working_hours is over (deliberately set it to 5 min for testing). So I have some question for the developers.

1) Is this is the intended behavior?
2) It seems that no matter what workinghours i define, once the client reboots and starts to beacon, it neglect the workhours setting. For example I define it as 23:00-23:05. If the client restart at 08:00 and connect back, it will continue to interact with the listener and bypass my setting.
3) What will happen if I set the agent's workinghour while the client is active. Will it persist or everything will initialize when it reboot.

Please advise thank you.

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://cloud.githubusercontent.com/assets/24275335/20760284/88ba2232-b75a-11e6-8831-7104d387e15c.png)

![image](https://cloud.githubusercontent.com/assets/24275335/20763188/f5f8e80c-b763-11e6-8067-cabd291d94da.png)

**Comment by enigma0x3** [comment]
Ill take a look at this, thanks!

**Comment by xorrior** [comment]
@Xurse Fixed in master and dev. Thanks!
