### ISSUE TITLE
Problem finding agents

### ISSUE THREAD

**Issue by lm902** [EmpireProject/Empire#409]
## Empire Version
1.6.0

## OS Information (Linux flavor, Python version)
Ubuntu 16.10, Python 2.7.12+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Once the number of agents gets huge, it's extremely hard to find the desired agent to work with.
I should be able to filter agents by name or username.

## Screenshot of error, embedded text output, or Pastebin link to the error
[Screenshot](http://i.imgur.com/1G9DRYV.jpg)

## Any additional information
None

**Comment by leesoh** [comment]
You probably already know this, but when you tab complete after typing a few letters, it will suggest a filtered list of agents. Not exactly what you describe, but pretty close?

**Comment by lm902** [comment]
I know that tab complete will give me a list of agents, but I can't search for an agent running on a specified computer name (such as "DCS01.EXAMPLE.COM") or a username (such as "EXAMPLE\Administrator")

**Comment by leesoh** [comment]
Short of renaming your agents to match your hostname, no. So your ideal solution would be something like this?
```
<Empire: agents) > list agents -> all agents shown
<Empire: agents) > list agents WORKS -> show all agents beginning with WORKS
```

**Comment by lm902** [comment]
Yes, that's exactly what I meant. So that managing like a few hundreds of agents will be a lot easier.

**Comment by leesoh** [comment]
Ahh, I see now. That's slick! I'm out of workarounds and agree with you wholeheartedly :D

**Comment by xorrior** [comment]
@lm902 we have/had a PR #763  trying to address this. No timetable on when it will be fixed.
