### ISSUE TITLE
.Net 2.0 support: using System.Security.Cryptography.RijndaelManaged instead System.Security.Cryptography.AesCryptoServiceProvider in stager when can't load System.Core

### ISSUE THREAD

**Issue by max3raza** [EmpireProject/Empire#417]
## Empire Version
2.0_beta and latest master branch

## OS Information (Linux flavor, Python version)
ArchLinux, Python 3.5

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Expected results: Start-Negotiate function should works successfully in the case of missed System.Core assembly (for example .Net 2.0)
Actual result:
can't find System.Security.Cryptography.AesCryptoServiceProvider because System.Core is not found
## Any additional information
example of solution:
https://github.com/OctopusDeploy/Calamari/commit/291c50fb6c9bf0c3ce4f921b29e6f452f18e9106

**Comment by xorrior** [comment]
Fixed https://github.com/EmpireProject/Empire/commit/b34f8858a5a27232dbdc6366742234f872b92805
