### ISSUE TITLE
Modules and shell do not work with UTF-8

### ISSUE THREAD

**Issue by redt3am** [EmpireProject/Empire#420]
## Empire Version
Latest

## OS Information (Linux flavor, Python version)
Kali, Ubuntu (same problem) 
English default language on both, but with utf8 support

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

networks in my country often contain credential and other string in native language Shell commands and modules such as invoke-wmi does not work when any of the fields contain non-ascii characters. When there are such characters, the server will give an error.  

 the strings in the native language is displayed correctly, just can't use them 

## Screenshot of error, embedded text output, or Pastebin link to the error
[!] Error: module source contains non-ascii characters

## Any additional information
It looks like it's intentionally restricted to ascii. 

However, downloading files with UTF-8 chars works thanks to (https://github.com/adaptivethreat/Empire/issues/125), but modules do not.

**Comment by Xyrodileas** [comment]
When performing tests with a Windows 10 machine in English, but with utf8 support (French keyboard), we couldn't use several modules like enumcreds and mimikatz.
We get the following error : 
`'ascii' codec can't encode characters in position 74-81: ordinal not in range(128)`

**Comment by amandus1990** [comment]
The same with chinese. Tried to add sys.setdefaultencoding('utf-8') in ./empire, does not work.
