### ISSUE TITLE
Cannot start listener on any port

### ISSUE THREAD

**Issue by L10n-of-Jud4h** [EmpireProject/Empire#422]
## Empire Version
1.6.0

## OS Information (Linux flavor, Python version)
Kali 2.0 Rolling
python 2.7.12+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
any time I try to start a listener on a port I always get the following error:

(Empire: listeners) > run
[!] Error starting listener on port 1234: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 1234, port likely already in use.

This happens with pretty much any port I try to use, even if the ports are open on my router. I installed Empire twice now from scratch, and even edited my ports.conf file to include ports 80, 8080, and 1234, like this:

0.0.0.0:80
0.0.0.0:8080
0.0.0.0:1234

None of these ports are in use, and checked this with netstat. I tried both with and without apache2 running and it's the same issue.

I also made sure my kali is up to date.

**Comment by mubix** [comment]
You are probably running into the same NAT / non-local IP issues as in #408 - If so, you can use a hostname/DNS name for the time being.

**Comment by L10n-of-Jud4h** [comment]
Hmm... I did look at it, though my interface is bridged

**Comment by L10n-of-Jud4h** [comment]
I do have a port forward on my router to the port I'm trying to use and it's enabled

**Comment by mubix** [comment]
@L10n-of-Jud4h so the Empire listener IP address is the same as the IP that your Kali VM has?

**Comment by L10n-of-Jud4h** [comment]
I tried the following:

I tried using the IP that my Kali VM has, which is the in the same subnet as my host machine because it's bridged.

I also tried using my external IP address from my ISP, which used to work great before, and have it pointed to the port that I have open on my router which points to the IP of my Kali machine through port forwarding.

Not sure what else I can try.

**Comment by L10n-of-Jud4h** [comment]
How would I use my ISP DNS and make it point back to me?

**Comment by newdays** [comment]
Exactly the same issue here, i forward a port on my cisco router to my kali machine but when i run or execute listener i get port already used. It used to work by the way i think this is just latest update ?

How do i use ISP DNS to point the connection back to my Kali ? 

Regards, 

John

**Comment by 001-001** [comment]
Exactly the same problem here:

Cannot bind to port, in use
Nothing running on the port
nc can bind to port

Tried using aws dns address, internal ip address, 0.0.0.0, external dns name. Nothing works.

Anyone made any progess on this? I have time to test suggestions.

**Comment by xorrior** [comment]
Please look at #363 for how to use empire behind NAT on the 2.0_beta branch. This won't apply to 1.6 but the beta branch should be merged with Master soon.
