### ISSUE TITLE
agents always return internal ip instead of public 

### ISSUE THREAD

**Issue by ra7bi** [EmpireProject/Empire#426]
## Empire Version

1.6.0

## OS Information (Linux flavor, Python version)

 Linux kali 4.6.0-kali1-amd64 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

im trying to use Empire over the internet with dynamic DNS , i can get agents connect to my kali box but im not able to send anything to the agents can you help please

**Comment by xorrior** [comment]
@ra7bi Please re-run empire with the --debug 2 flag and post the output after sending a command in the git issue.
