### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by brandontict** [EmpireProject/Empire#429]
## Empire Version
Latest via git 

## OS Information (Linux flavor, Python version)
Kali rolling 2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Empire was working weeks ago, haven't used it until today. I've updated my machine many times since last time I've successfully ran empire .

## Screenshot of error, embedded text output, or Pastebin link to the error
```

 Empire git:(master) ./empire 
Traceback (most recent call last):
  File "./empire", line 6, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

```

## Any additional information
I've removed empire, and grabbed latest copy via git . Setup.sh finished with no issues . Verified that **python-openssl and pyOpenSSL** are installed and updated

```
➜  Empire git:(master) sudo apt-get install python-openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-openssl is already the newest version (16.2.0-1).
python-openssl set to manually installed.
The following packages were automatically installed and are no longer required:
  libassuan-dev libmimic0 libopencv-contrib2.4v5 libopencv-legacy2.4v5 libopencv-ml2.4v5 libradare2-1.0
  libschroedinger-1.0-0 python-vte
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
➜  Empire git:(master) sudo pip install pyOpenSSL
Requirement already satisfied: pyOpenSSL in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pyOpenSSL)
Requirement already satisfied: cryptography>=0.2.1 in /usr/lib/python2.7/dist-packages (from pyOpenSSL)
```

Appreciate all of your great work

**Comment by theoneandonly-vector** [comment]
same problem over here

**Comment by theoneandonly-vector** [comment]
I found a fix:

pip uninstall pyopenssl

then download latest popenssl:
https://pypi.python.org/pypi/pyOpenSSL

extract + run ./setup.py install

=works

**Comment by xorrior** [comment]
In several test cases, I have not ran into an issue with the pyOpenSSL pip package. I do understand that there may be edge cases where there is an issue. I think the workaround mentioned above is the best solution currently.

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!
