### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by tehseensagar** [EmpireProject/Empire#432]
I've applyed the fix for emire web and if I ran just ./empire it works like a charm but when I supply the user/pass/port parameters I got bunch of errors.

`
./empire --headless --restport 1337 --username admin --password temp1234

    Starting a full Empire instance
    [*] Loading modules from: /opt/Empire-master/lib/modules/
    Starting Empire RESTful API on port: 1337
    RESTful API token: gjibeplwpkwkl4auzcj5452kk6vibj0rpkctrm3i
    Traceback (most recent call last):
    File "./empire", line 1234, in
    start_restful_api(startEmpire=True, suppress=True, username=args.username, password=args.password, port=args.restport)
    File "./empire", line 1081, in start_restful_api
    if not request.json or not 'username' in request.json or not 'password' in request.json:
    File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in getattr
    return getattr(self._get_current_object(), name)
    File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
    File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
    RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.`

**Comment by xorrior** [comment]
The Empire rest API is still a long ways off from being ready for use. I would almost consider it still in alpha. Unfortunately, this is towards the bottom of the list when it comes to priority and won't be addressed for quite some time.

**Comment by xorrior** [comment]
@tehseensagar We will probably end up addressing this when revamping the REST api towards the tail end of the year. Sorry for the long wait.
