### ISSUE TITLE
Windows 10 check for PSVersion 2 available

### ISSUE THREAD

**Issue by PoSHMagiC0de** [EmpireProject/Empire#433]
## Empire Version
1.6

## OS Information (Linux flavor, Python version)
Kali 4.6.4, Python 2.7.13

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Some modules in PSEmpire require that Powershell Version 2.0 installed to function right.  Some of these modules are psinject and any dllinjection.  I also notice that although MiMiKatz ps1 module gives feedback locallly, it does not return any feedback remotely in PSEmpire unless I force the stager to be initiated in PSVersion 2.  Also, Windows 10 pro has the ability to remove the 2.0 runtime.

A work around I have done was create a custom module similar to the spawn module but adds on the parameter "-version 2.0" after "powershell.exe".  From what I seen if staging it has to be the first parameter after "powershell.exe"

A possible check code is below.  It would only be done if the current session is not in the version you are testing for.  Sorry, my github-fu is extremely weak.

`test = [scriptblock]::Create('$PSversiontable.PSVersion.Major')`
`$myversion = $null`
`Try`
`{`
`    Start-Job -Name Test -ScriptBlock $test -PSVersion 2.0 | Wait-Job |`
`        % {$myversion = Receive-Job $_;$_} | Remove-Job`
`    If($myversion -eq 2)`
`    {`
`        Write-Host "Powershell Version 2 Engine is installed."`
`    }`
`}`
`Catch`
`{`
`    Write-Host "Powershell Version 2 Engine is not installed."`
`}`

If this information can be collected for Empire and used to supply to Empire modules if psversion2 is possible then authors who modules require it can be further restricted from running so not to cause errors.  The agent task runner start-job function can include the "-PSVersion 2.0" parameter if the module requires it else just run the job without it running in the current runtime version.

Of course, this change would require a cascade change to existing modules if they do require to be ran in the PSVersion 2.0 runtime environment to function correctly.

3 versions that would be useful to check for is version 2.0, 4.0 and 5.0.  5.0 only for those who want to do fancier PoSH scripts that include classes and the other 5.0 only functionality. Of course if 5 is present then so is 4.
## Any additional information
When my github-fu gets better where I won't cause you more work with my errors in doing pulls, I have other stuff to contribute.

**Comment by leechristensen** [comment]
PSInject in the [2.0_beta branch](https://github.com/adaptivethreat/Empire/blob/2.0_beta/data/module_source/management/Invoke-PSInject.ps1) fixes this.  Can you verify that you don't have this problem when using the 2.0_beta branch?

@HarmJ0y Shouldn't we be able to just drop the 2.0_beta version of PSInject into the 1.6 branch without things breaking?

**Comment by PoSHMagiC0de** [comment]
Just pulled the latest branch of the 2.0 beta and gave it a try.  It is working in this build.  I been using the master, didn't bother to check for other branches.  I will begin pulling this branch as well and begin using it.

**Comment by PoSHMagiC0de** [comment]
Wanted to add.  Empire Version 2 works fine in Windows 10 but has some issues in Window 7.  This is a 64bit OS.  Empire Version 2 psinject, reflectiveinject and mimikatz doesn't inject or give back data on Windows 7.  Empire 1.6 works fine on Windows 7.  It seems 1.6 is best for pre Win10 and 2.0 works great for Win10+.

**Comment by xorrior** [comment]
@PoSHMagiC0de I tested some of the modules mentioned on a Win 7 box with the 2.0_beta branch and received output. I don't believe the version should be a problem anymore. Please re-open this if it still is. Thanks
