### ISSUE TITLE
[feature request] .so stager for linux

### ISSUE THREAD

**Issue by thesle3p** [EmpireProject/Empire#434]
it would be incredibly useful when deploying bootkits/rootkits if a .so stager was available for the Linux/python payload, would it be possible to create one?

**Comment by killswitch-GUI** [comment]
Could you give some more details on how this would look to facilitate .so to work with rootkits? deployment method etc?

**Comment by thesle3p** [comment]
some rootkits (EvilAbigail) takes payloads in .so format which is easy
to do with metasploit, but it would be nice to do the same thing with
Empire.

**Comment by killswitch-GUI** [comment]
@thesle3p i will see what the guys think. Your looking for a Shared Object that is injectable? Never played with that tool set, let me do some research on this.

**Comment by thesle3p** [comment]
Not needed figured out a way to get it to work, just had to modify the make
file.
