### ISSUE TITLE
mailraider/send_mail

### ISSUE THREAD

**Issue by milcaca** [EmpireProject/Empire#441]
On master branch as on 2.0, the module does not work for me. I'm on a 2013 environement (Office + exchange) with userland rights. Any idea ? The module was working last time I used it the only modification I can be sure is migration of environement.

**Comment by xorrior** [comment]
Can you please provide some more info as to what wasn't working in that module specifically? Keep in mind that if you do not modify the registry keys to allow for programmatic access to Outlook, the user will be prompted.

**Comment by xorrior** [comment]
Please complete the template for git issues so that we can better understand the problem you are having.
