### ISSUE TITLE
dependencies missing 

### ISSUE THREAD

**Issue by Nan0r** [EmpireProject/Empire#442]
## Empire Version
v1.5

## OS Information (Linux flavor, Python version)
debian 8.7 
Python 2.7.9

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

On my server, i have download lastest version of empire from github: 
https://github.com/adaptivethreat/Empire/releases 
When i try to launch empire after running ./setup/install.sh 
./empire
ImportError: No module named OpenSSL
for fixing this error, i try to install pyopenssl: 
pip install pyopenssl
but failed when pip try to install cryptography :
Command "/usr/bin/python -u -c "import setuptools, tokenize;file='/tmp/pip-build-fzxhtW/cryptography/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-6mdWxC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-fzxhtW/cryptography/

for fixing this secondary error, i install missing dependencies : 
apt-get install build-essential libssl-dev libffi-dev python-dev

and i retry to install cryptography & pyopenssl
pip install cryptography
pip install pyopenssl

and finally empire work like a charm :) 

I make you this return if you want to include all of dependencies you missing too include on install.sh 

Have a nice day and thanks a lot for you wonderful job !

**Comment by rvrsh3ll** [comment]
Apologies for the delay. This has been fixed!
