### ISSUE TITLE
Empire doesn't run : 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by Martou1** [EmpireProject/Empire#451]
`root@kaliTesting:/# apt-cache show python | grep "Version"
Version: 2.7.13-2
Version: 2.7.9-1
root@kaliTesting:/# apt-cache show empire | grep "Version"
Version: 1.14-1
Version: 1.12-1
root@kaliTesting:/# uname -r
4.9.0-kali1-amd64
`
I downloaded the latest version of Empire-master and i installed it by run `./setup/install.sh`

But i saw an error here :
```
root@kaliTesting:~/Téléchargements/Empire-master# ./setup/install.sh
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libssl-dev is already the newest version (1.1.0c-2).
python-dev is already the newest version (2.7.13-2).
python-m2crypto is already the newest version (0.24.0-1).
python-pip is already the newest version (9.0.1-2).
swig is already the newest version (3.0.10-1.1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 95 non mis à jour.
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages
Requirement already satisfied: iptools in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pydispatcher in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: flask in /usr/lib/python2.7/dist-packages
Requirement already satisfied: pyOpenSSL in /usr/lib/python2.7/dist-packages

 [>] Enter server negotiation password, enter for random generation: anything
Traceback (most recent call last):
  File "./setup_database.py", line 128, in <module>
    )''')
sqlite3.OperationalError: table config already exists


 [*] Certificate written to ../data/empire.pem


 [*] Setup complete!
```

And when i launch it it give me this error :
`root@kaliTesting:~/Téléchargements/Empire-master# ./empire
Traceback (most recent call last):
  File "./empire", line 10, in <module>
    from lib.common import empire
  File "/root/Téléchargements/Empire-master/lib/common/empire.py", line 31, in <module>
    import agents
  File "/root/Téléchargements/Empire-master/lib/common/agents.py", line 22, in <module>
    import http
  File "/root/Téléchargements/Empire-master/lib/common/http.py", line 67, in <module>
    class RequestHandler(BaseHTTPRequestHandler):
  File "/root/Téléchargements/Empire-master/lib/common/http.py", line 73, in RequestHandler
    serverVersion = helpers.get_config('server_version')[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
`
Thanks you very much for your help !

**Comment by killswitch-GUI** [comment]
Can you please use the reset script and report back?

**Comment by Martou1** [comment]
thanks for your reply :`root@kaliTesting:~/Téléchargements/Empire-master/setup# ./reset.sh

 [>] Enter server negotiation password, enter for random generation: anything
Traceback (most recent call last):
  File "./setup_database.py", line 131, in <module>
    c.execute("INSERT INTO config VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", (STAGING_KEY,STAGE0_URI,STAGE1_URI,STAGE2_URI,DEFAULT_DELAY,DEFAULT_JITTER,DEFAULT_PROFILE,DEFAULT_CERT_PATH,DEFAULT_PORT,INSTALL_PATH,SERVER_VERSION,IP_WHITELIST,IP_BLACKLIST, DEFAULT_LOST_LIMIT, "", "", API_USERNAME, API_PASSWORD, "", API_PERMANENT_TOKEN))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
Traceback (most recent call last):
  File "./empire", line 10, in <module>
    from lib.common import empire
  File "/root/Téléchargements/Empire-master/lib/common/empire.py", line 31, in <module>
    import agents
  File "/root/Téléchargements/Empire-master/lib/common/agents.py", line 22, in <module>
    import http
  File "/root/Téléchargements/Empire-master/lib/common/http.py", line 67, in <module>
    class RequestHandler(BaseHTTPRequestHandler):
  File "/root/Téléchargements/Empire-master/lib/common/http.py", line 73, in RequestHandler
    serverVersion = helpers.get_config('server_version')[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
`

**Comment by Martou1** [comment]
Ok i resolve the problem by adding `conn.text_factory = lambda x: unicode(x, "utf-8", "ignore")` after the line 100
Thanks you anyway killswitch-GUI :+1:

**Comment by killswitch-GUI** [comment]
was this a lang issues @Martou1 ?

**Comment by killswitch-GUI** [comment]
I figured that much

**Comment by Martou1** [comment]
I don't know...i work on french OS effectively...
But why did you say that ? Anything in relation with the lang can cause this issue ?
