### ISSUE TITLE
[feature request] option for powerManagementEvent for  wmi persistence 

### ISSUE THREAD

**Issue by thesle3p** [EmpireProject/Empire#457]
Would it be possible to add a option to the WMI persistence module to spawn a agent every time the target resumes from suspend (event type seven)? The documentation for that can be found here 

https://msdn.microsoft.com/en-us/library/aa394362(v=vs.85).aspx

**Comment by xorrior** [comment]
@thesle3p I'm sure it's possible. I would take a look at some of the examples for wmi persistence in powersploit and submit a PR when ready.
