### ISSUE TITLE
setting OutFile discards module output

### ISSUE THREAD

**Issue by dgrim1214** [EmpireProject/Empire#461]
## Empire Version
1.6

## OS Information (Linux flavor, Python version)
Ubuntu 16.10

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Setting an OutFile for any module results in the job being created and instantly finished with no output. 

## Any additional information
Empire is being run as root and the intended path has rw permissions properly set.

**Comment by rvrsh3ll** [comment]
Target OS?

**Comment by dgrim1214** [comment]
Windows 7 SP 1

**Comment by xorrior** [comment]
@dgrim1214 What modules have you tried using with OutFile?

**Comment by xorrior** [comment]
Closing. No response
