### ISSUE TITLE
[Feature Request] Integrate Invoke-Obfuscation into Empire to evade AV signatures

### ISSUE THREAD

**Issue by cobbr** [EmpireProject/Empire#462]
With AMSI and in-memory scanning of powershell scripts on the rise, I think it would be great to integrate a full powershell obfuscator into the Empire codebase. I implemented an integration with Invoke-Obfuscation into a fork of Empire: [ObfuscatedEmpire](https://github.com/cobbr/ObfuscatedEmpire).  I would love to see some of the functionality integrated into Empire.

For a full explanation of motivations behind the idea and how to use ObfuscatedEmpire, please see my [writeup on ObfuscatedEmpire](https://cobbr.io/ObfuscatedEmpire.html). I'll limit this post to discussion of implementation.

### Design Decisions

Integrating Invoke-Obfuscation and Empire into ObfuscatedEmpire required a few major design decisions. I'm sure that I didn't make all of the best decisions. Even if it is decided to integrate some of the obfuscation changes, it could certainly be done differently than how I have implemented it.

A few of the design decisions to be discussed:

* **Powershell** - Invoke-Obfuscation is written in powershell, not python. The integration would introduce **server-side** powershell into Empire. With the advent of cross-platform powershell, this is a possibility. However, the cross-platform Powershell 6.0 is still currently in **alpha** state, and Kali/Debian are **not** officially supported.

I did all of my testing of ObfuscatedEmpire on Kali Linux with Powershell-6.0-alpha and have not encountered any problems. Introducing server-side powershell is a major change, but this is *powershell* Empire, is it not?

* **Empire Modules** - With how Empire is currently structured, modules are responsible for providing their own powershell code to be run on the target machine. To obfuscate module code, I altered **all** *python* module files to implement obfuscation logic.

* **Obfuscated module code files** - Obfuscation of large scripts, such as Invoke-Mimikatz, can take some time. To allow for obfuscation of modules to take place prior to when they need to be executed, I am storing obfuscated module source code in `data/obfuscated_module_source`.

* **Configuration** - I didn't want the added obfuscation functionality to get in the way of a user who just wanted to use Empire normally, without obfuscation. So all obfuscation is **disabled be default**. I also wanted obfuscation to be a transparent process to a user, without them needing to understand exactly what is going on or needing to alter their normal Empire usage. With this in mind, I utilized a global `obfuscate` setting. Setting this value to `True` automatically obfuscates all module code sent to all agent, as well as the agent negotiation process for new agents. In addition, I've added a global `obfuscate_command` setting that allows advanced users to customize their obfuscation with Invoke-Obfuscation style syntax. For stagers/launchers, there are similar `Obfuscate` and `ObfuscateCommand` settings available in the menu of all applicable stagers.

It may make more sense to implement `Obfuscate` and `ObfuscateCommand` settings *per-module* than to use the global obfuscate setting for all modules, but I have **not** implemented this. I leave that up for discussion.

I've included some of the higher-level design changes I made when implementing `ObfuscatedEmpire`, but I'm sure there's plenty more to discuss. Feel free to grab a copy of it and play with it. I would love to get feedback on the decisions made, and hear if anyone has any opinions on things that could be done better. Or just let me know about all the mistakes I'm sure I made, that's cool too.

I will try to submit a PR soon. I have ObfuscatedEmpire merged onto the dev and master branches so far, but not the 2.0_beta yet. I'll see about getting it merged onto the 2.0_beta and submit a PR. Let me know if you'd like to see any design changes prior to submitting!

**Comment by xorrior** [comment]
This sounds really cool, nice work. We'll have to get back to you on this. Most likely this will be considered after the merge into the 2.0 branch.

**Comment by xorrior** [comment]
@cobbr Overall I think this would be awesome to have. If you feel confident in your code base, feel free to submit a PR to the 2.0_beta branch and we'll test it out. Thanks for the suggestion!

**Comment by thesle3p** [comment]
Any plans on merging this?

**Comment by xorrior** [comment]
@thesle3p do you have a pull request? This would be great. Would also require some serious overhead. I remember seeing a python port of Invoke-Obfuscation out there somewhere....

**Comment by cobbr** [comment]
Sorry guys, I'm still working on this.

A lot of issues came up when moving to Empire 2.0 with a particular type of obfuscation within Invoke-Obfuscation, I can submit a PR w/ that mode of obfuscation disabled for now and just re-enable it once it's fixed. Or keep working through some of the bugs until it's ready.

The only python port I've seen only included the ASCII encoder, if I remember right.
