### ISSUE TITLE
Problem Launching Empire

### ISSUE THREAD

**Issue by sparta3407** [EmpireProject/Empire#464]
## OS Information (KALI LINUX ROLLING 2016.2, Python version
I can't launch Empire: i've this errors:

Traceback (most recent call last):
  File "./empire", line 1237, in <module>
    main = empire.MainMenu(args=args)
  File "/root/BYPASS AV/Empire/lib/common/empire.py", line 98, in __init__
    dispatcher.connect(self.handle_event, sender=dispatcher.Any)
AttributeError: 'module' object has no attribute 'connect'

**Comment by patitoaxel** [comment]
Which python version are you on?

**Comment by sparta3407** [comment]
python 2.7.13

**Comment by xorrior** [comment]
Have completed the setup script successfully? I tested this on kali rolling and did not have any issues after completing the setup script. You can re-open this issue if you are having problems with it after completing the setup script.
