### ISSUE TITLE
Certificate Not Applying (CertPath)

### ISSUE THREAD

**Issue by P0ng04** [EmpireProject/Empire#466]
## Empire Version
2.0 Beta

## OS Information (Linux flavor, Python version)
Ubuntu - 16.04
Python 2.7.12
and
Kali - 2016.2
Python 2.7.13

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Applying the CertPath option, and changing URL to use HTTPS.  The certificate seems like its not taking, when navigating to the page through a browser it shows as a insecure connection and the certificate information is not there. The previous version worked, and tested the certificate against multiple other services with success.

## Any additional information
Testing the certificate with previous version works.

**Comment by xorrior** [comment]
<img width="505" alt="2017-04-22 13_12_06-privacy error" src="https://cloud.githubusercontent.com/assets/9156069/25306552/6e2d1960-275d-11e7-981c-0880cff4e413.png">

Is this the certificate error you are referring to @P0ng04 ? If you are using a self-signed certificate, there is no CA. Therefore, your browser will show that error message everytime. However the cert path is working. Try doing another git pull before attempting this again.

**Comment by P0ng04** [comment]
Thanks for the reply, I think I mentioned this before, but the certificate I have is valid, and works on the older version of empire.  I also use this certificate in my meterpreter handlers and it has not issues.  I will try another git pull and some more troubleshooting on my part and get back to you.  Good framework, could use some more modularity but I like where you guys have come and where you are.


Thank you very much for your assistance.  I hope I didn't come off brash.



________________________________

**Comment by wonktnod** [comment]
I have the same problem with a version pulled from today (2017-05-30). Whatever I give as a value for CertPath in the listener/http setup is ignored. I can supply an arbitrary file e.g. /etc/passwd and the listener comes up without an error. However there is an easy fix, just copy the pem file over the default file created during setup in data/empire.pem. Since that file will be used anyway as long as you only need one listener you have no problem.

**Comment by xorrior** [comment]
Fixed https://github.com/EmpireProject/Empire/commit/5a530fede9ddd064cd7dfea57ffc3868328ca456
