### ISSUE TITLE
Agent download Command Needs a Cancel Option

### ISSUE THREAD

**Issue by VillaStrayligh7** [EmpireProject/Empire#467]
## Empire Version
1.6.0 / 2.0_beta

## OS Information (Linux flavor, Python version)
Kali Linux (latest)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Once a file download is initiated from an Empire agent, the agent ignores any other task commands until the file download completes.  Since only up to 512K is downloaded on each agent check-in, if the file is extremely large and/or if the check-in delay is set to a non-default larger value, this will lock the Empire agent into that one file download operation for an extended period of time.  Issuing an agent "clear" command has no effect on a current file download. Request is to either:

1. Allow other agent task commands to execute on agent check-in while a file download is in progress
or
2. Provide a way to task the agent to cancel a file download in progress

It would also be useful if at the initiation of a file download, on the first status message (eg. "[+] Part of file File_X from Agent_Y saved") or in another initial status message, if it would report the total download file size in bytes.
## Screenshot of error, embedded text output, or Pastebin link to the error
N/A

**Comment by xorrior** [comment]
See #164

**Comment by xorrior** [comment]
#161
