### ISSUE TITLE
Agent shell Command Should Display a Completed Status Message

### ISSUE THREAD

**Issue by VillaStrayligh7** [EmpireProject/Empire#468]
## Empire Version
1.6.0

## OS Information (Linux flavor, Python version)
Kali Linux (latest)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
The agent shell command should always return on next check-in a brief status message to indicate the command executed on the target.  This is to cover the scenario when the command being passed to shell does not return output.  In that scenario there's no verification if the command actually ran, and in an async comms architecture it makes sense to always return some form of status indicator following an agent task.

This functionality exists in 2.0_beta, which always returns  "..Command execution completed."

## Screenshot of error, embedded text output, or Pastebin link to the error
N/A

**Comment by xorrior** [comment]
We will be merging the 2.0_beta branch into master very soon, so this will be effectively resolved.
