### ISSUE TITLE
Absurd mem usage on situational_awareness/host/computerdetails

### ISSUE THREAD

**Issue by dwendt** [EmpireProject/Empire#473]
## Empire Version
1.6.0

## OS Information (Linux flavor, Python version)
win server 2k8 x86 edition

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
```
(Empire: agents) > usemodule situational_awareness/host/computerdetails
(Empire: situational_awareness/host/computerdetails) > info
Options:

  Name      Required    Value                     Description
  ----      --------    -------                   -----------
  4648      False                                 Switch. Only return 4648 logon
                                                  information (RDP to another machine).
  AppLocker False                                 Switch. Only return AppLocker logs.
  Agent     True        None                      Agent to run module on.
  4624      False                                 Switch. Only return 4624 logon
                                                  information (logons to this machine).
  SavedRDP  False                                 Switch. Only return saved RDP
                                                  connections.
  PSScripts False                                 Switch. Only return PowerShell scripts
                                                  run from operational log.
```

powershell proceeds to kill itself via consuming up to 2gb of memory in one sitting.

my guess is it occurs where there's way too many event logs [here](https://github.com/EmpireProject/Empire/blob/293f06437520f4747e82e4486938b1a9074d3d51/data/module_source/situational_awareness/host/Get-ComputerDetails.ps1#L56) because they're all loaded into memory before being filtered. which isn't very efficient tbh.

context: there's probably like 9001gb of event logs on the host. it'll probably OOM powershell on any call to Get-EventLog. is there any possibility of preventing/catching issues like this where it'll go out of memory really easily?

## Screenshot of error, embedded text output, or Pastebin link to the error
my agent is now dead -- because a 2GB powershell.exe pegged memory and the system became unresponsive -- and we will be holding a funeral for it

**Comment by rvrsh3ll** [comment]
We could change this to something like: Get-EventLog -Newest 100. Thoughts?

**Comment by PoSHMagiC0de** [comment]
This can probably be alleviated by doing it with wmi and using filters.
Example:
`gwmi -class win32_ntlogevent -Filter "LogFile='Security' and (EventIdentifier='4624' or EventIdentifier='4648')"`

I see only the Message is accessed so what you get can be further shrunk with:
`gwmi -query "Select Message from win32_ntlogevent where LogFile='Security' and (EventIdentifier='4624' or EventIdentifier='4628')"`

**Comment by xorrior** [comment]
Added a Limit option to only return the n newest log entries.
