### ISSUE TITLE
Tab completion on OSX

### ISSUE THREAD

**Issue by Viss** [EmpireProject/Empire#475]
## Empire Version
2.0_beta

## OS Information (Linux flavor, Python version)
OSX

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Pretty straightforward: tab completion doesn't work when using empire on OSX. It's not a showstopper but it does prevent being as nimble as one could be when using the tool on OSX.

**Comment by harml355** [comment]
Same issue on OSX. Usestager[TAB] enter doesnt't show command list

**Comment by thansau239** [comment]
same issue!!!

**Comment by harml355** [comment]
Getting real annoying :/

**Comment by leechristensen** [comment]
Pull requests are open to all and are the guaranteed fastest ways to get fixes :)

**Comment by rvrsh3ll** [comment]
OSX is not a supported distro for Empire at this time.
