### ISSUE TITLE
NAT Configuration for custom external port

### ISSUE THREAD

**Issue by Gr3yCod3riX** [EmpireProject/Empire#477]
## Empire Version
2.0 / 1.6

## OS Information (Linux flavor, Python version)
Debian

I want to route over WAN and I've tried many suggested solution and it didn't work. 
Config:
Server -> publicDNS:3322 (custom port, can't be changed to 80)
                local IP:1100
3322 is mapped to 1100 on the firewall 
I have tried setting host -> publicDNS and port -> 3322 but it won't work

What is the right setting?

**Comment by xorrior** [comment]
see #363
