### ISSUE TITLE
powershell doesnt connect using reverse_tcp_dns

### ISSUE THREAD

**Issue by Omardavinci** [EmpireProject/Empire#487]
## Empire Version
Last version

## OS Information (Linux flavor, Python version)
kali linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I was testing porwershell empire and doesnt seem's to work using dyndns like http://theddns:port or reverse_tcp_dns.

**Comment by xorrior** [comment]
see #477
