### ISSUE TITLE
Feature: Add timestamp to results table

### ISSUE THREAD

**Issue by bneg** [EmpireProject/Empire#493]
## Empire Version
2.0_Beta

## OS Information (Linux flavor, Python version)
All

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Every results write to the database also includes a timestamp

This should be pretty easy, I'll look into doing this myself.

**Comment by xorrior** [comment]
Sounds great! Just submit a PR once you've got it figured out. Thanks
