### ISSUE TITLE
Unable to delete agents

### ISSUE THREAD

**Issue by cartagenae** [EmpireProject/Empire#505]
## Empire Version
2.0_beta

## OS Information (Linux flavor, Python version)
Linux Ubuntu

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

After typing kill all, empire prompts me to confirm killing all agents.

I type 'y' and the agents are still there.

**Comment by mr64bit** [comment]
Are the agents contacting the server? The kill command will only remove an
agent once the agent confirms it has closed. (To remove agents that are out
of contact, use the remove command)
Is this specific to 'kill all'? Can you kill agents one at a time?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
If you can provide more information such as `--debug 2`' logs or your setup (listener' options ? stager options ?), it could help us.

**Comment by cartagenae** [comment]
@mr64bit, thank you. I did a remove on each of them after killing all my agents. It worked. They're no longer currently listed my want to list my 'active' agents.

**Comment by cartagenae** [comment]
@mr64bit, thank you. I did a remove on each of them after killing all my agents. It worked. They're no longer currently listed my want to list my 'active' agents.
