### ISSUE TITLE
set name - unknown syntax

### ISSUE THREAD

**Issue by totoroha** [EmpireProject/Empire#510]
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I started the empireshell right after i installed it. use command "listeners" - tried to set name with command "set Name test" but the program returned with an error message as:
"Unknown syntax: set name test"

can anyone tell me how to fix it?

**Comment by necony286** [comment]
i have a similar problem i cant even use info command in when i move to listeners or set anything

**Comment by xorrior** [comment]
@totoroha please see https://github.com/EmpireProject/Empire/issues/511
