### ISSUE TITLE
Empire does not start

### ISSUE THREAD

**Issue by dea8face** [EmpireProject/Empire#512]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Kali 2017.1 rolling

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
After install and trying to run script gives an error

## Screenshot of error, embedded text output, or Pastebin link to the error
root@kali:~/Empire# ./empire
Traceback (most recent call last):
  File "./empire", line 11, in <module>
    from lib.common import empire
  File "/root/Empire/lib/common/empire.py", line 27, in <module>
    import agents
  File "/root/Empire/lib/common/agents.py", line 64, in <module>
    from zlib_wrapper import compress
ImportError: No module named zlib_wrapper

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
`pip install zlib_wrapper` ?

**Comment by dea8face** [comment]
root@kali:~/Empire/setup# pip install zlib_wrapper
Requirement already satisfied: zlib_wrapper in /usr/local/lib/python3.5/dist-packages

**Comment by xorrior** [comment]
You need to use python 2.7

**Comment by dea8face** [comment]
pip2.7 install zlib_wrapper solved it.. thx for help
