### ISSUE TITLE
Empire start error

### ISSUE THREAD

**Issue by arcadyan** [EmpireProject/Empire#513]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)

Kali 2017.1 rolling
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
After installed and trying to run script gives an error!

## Screenshot of error, embedded text output, or Pastebin link to the error

```
root@a7f99h3kk5j69d77v3v5-android:~/Empire# ./empire
Traceback (most recent call last):
  File "./empire", line 1294, in <module>
    main = empire.MainMenu(args=args)
  File "/root/Empire/lib/common/empire.py", line 75, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist')
TypeError: 'NoneType' object is not iterable
root@a7f99h3kk5j69d77v3v5-android:~/Empire# 

```

**Comment by xorrior** [comment]
you need to run ./reset.sh from the setup directory. Warning: this will clear the database.

**Comment by arcadyan** [comment]
Worked ..thanks a lot!
