### ISSUE TITLE
trouble with syntax or commands not working

### ISSUE THREAD

**Issue by necony286** [EmpireProject/Empire#514]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
kali 2016

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
#511
i think i had the wrong person help me or i didnt understand them but i made a new post cuz i dont know can u see if i comment on the closed ones anyway my problem was the commands are not working u told me im using wrong syntax but some commands are working like for example list command and the "uselistner" command u told me to use is for using an Empire listener module which i dont want.
 i want to make a listner  and the part " <listner_type> " i dont get what and how to use the correct syntax or where can i find it ?
http://www.powershellempire.com/?page_id=110 it dosent say anything about these things here

## Any additional information
and did u see what those the error say http://tinypic.com/view.php?pic=1zqalx3&s=9
(Empire) > listeners
[!] No listeners currently active
(Empire: listeners) > info
[!] Invalid listener name
(Empire: listeners) > exit
[>] Exit? [y/N] 
invalid name but i dont have an listner created how can i make one if i can set host port name?

**Comment by xorrior** [comment]
Listeners
uselistener http
set optionname optionvalue

**Comment by necony286** [comment]
ok ty<3 my bad. excuse me it wasnt like that before. can u spare a min more and tell me where can i learn the syntax

**Comment by xorrior** [comment]
http://www.harmj0y.net/blog/empire/the-empire-strikes-back/

**Comment by necony286** [comment]
i fking love you! serbia says u picku mater (with love from serbia )

**Comment by redsnakefi** [comment]
I was about to file the same issue. Listeners 101 page need to be updated or create a separate page for 2.0. New users following reading popular Empire tutorial sites expect to see something from "info" after invoking "listeners". I only learn in this Issues page that I have to invoke "uselistener http" as well.
