### ISSUE TITLE
Unable to set a listener [Panic Mode]

### ISSUE THREAD

**Issue by 0xsauby** [EmpireProject/Empire#515]
## Empire Version
[Version] 2.0

## OS Information (Linux flavor, Python version)
Kali Linux Rolling Stones
4.9.0-kali2-amd64 #1 SMP Debian 4.9.13-1kali1 (2017-03-01) x86_64 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Unable to set a listener.
(Empire) > listeners
[!] No listeners currently active 
(Empire: listeners) > set Name test
*** Unknown syntax: set Name test
(Empire: listeners) >

## Screenshot of error, embedded text output, or Pastebin link to the error
Attached
![empire](https://cloud.githubusercontent.com/assets/7544525/26083883/5163026c-39a6-11e7-95b5-98ebcbc700f8.png)

**Comment by n00shE** [comment]
Empire 2.0 has changed the way listeners are created. To create a new listeners use the command 'uselistener'. In you case you will probably want the http listener. Use the command 'uselistener http'. Now you can set your options.

**Comment by 0xsauby** [comment]
Ah, works now. Thanks a stack.
