### ISSUE TITLE
Can't clear agents

### ISSUE THREAD

**Issue by ztencmcp** [EmpireProject/Empire#518]
## Empire Version

[Version] 2.0 | 

## OS Information (Linux flavor, Python version)

Debian & Pyathon 2.7.13

###################################
I found when i wanted to kill agents and clear them with command kill and clear, it couldn't work. the agents still there. What's going on here? The only way is run ./reset.sh? Thanks.

**Comment by rvrsh3ll** [comment]
navigate to the agents section. if you want to kill all your agents type "kill all". then you can remove them all from the database by "remove all"
