### ISSUE TITLE
[!] Error in launcher command generation.

### ISSUE THREAD

**Issue by Nyxw0rm** [EmpireProject/Empire#519]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Kali linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
[!] Invalid listener: http
[!] Error in launcher command generation.

## Screenshot of error, embedded text output, or Pastebin link to the error
http://imgur.com/a/hQ6pu

**Comment by atkinsj** [comment]
Have you started the listener yet?

**Comment by Nyxw0rm** [comment]
ok , I do not notice that jajaja thanks
