### ISSUE TITLE
You can't build a listener like you did before

### ISSUE THREAD

**Issue by EternalBlues** [EmpireProject/Empire#520]
## Empire Version
os Version debian8

After version updates,
You can't build a listener like you did before

**Comment by wambiri** [comment]
./G0atch555---

**Comment by wambiri** [comment]
./G0atch555---

**Comment by Ug0Security** [comment]
Same here on kali 2. 0 x64
![image](https://cloud.githubusercontent.com/assets/28728543/26192492/307737f4-3bb2-11e7-9969-c0af2d2dddd9.png)

I don't know if this is linked but it seems to have a mistake one the root path when reloading modules
(double slash before lib)
![image](https://cloud.githubusercontent.com/assets/28728543/26192529/5eeab264-3bb2-11e7-8d25-5836bc8e51fc.png)

**Comment by Ug0Security** [comment]
same here on kali 2.0 x64

![image](https://cloud.githubusercontent.com/assets/28728543/26192580/a2251290-3bb2-11e7-847e-8a37e8855984.png)


I don't know if this is linked but there is also a mistake iun the root path when i reload module

![image](https://cloud.githubusercontent.com/assets/28728543/26192613/c1fcdb8e-3bb2-11e7-8a1c-73fdd9c558f4.png)

**Comment by Ug0Security** [comment]
Just to share it used to work this way 

![image](https://cloud.githubusercontent.com/assets/28728543/26192784/48101146-3bb3-11e7-81d1-4c5426df2e11.png)

(forget le module number i just tried to copy all from new release)

**Comment by xorrior** [comment]
Help will show you all available commands in the current menu. 

From the listeners menu:  uselistener http. Then set your options. Then execute.
