### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by bustudo** [EmpireProject/Empire#524]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Kali Linux Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Trying to make listener

## Screenshot of error, embedded text output, or Pastebin link to the error
![screenshot from 2017-05-19 07-25-15](https://cloud.githubusercontent.com/assets/20223853/26245900/741b1860-3c64-11e7-89c6-c66583116174.png)

## Any additional information
the same error in all period of working empire

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Syntax has changed with 2.0 :
```
listeners
uselistener http (or other listener, you can use tab)
set optionname optionvalue
```
http://www.harmj0y.net/blog/empire/the-empire-strikes-back/
