### ISSUE TITLE
unknow syntax error

### ISSUE THREAD

**Issue by 0patch** [EmpireProject/Empire#530]
## Empire Version
Empire 2.0

## OS Information (Linux flavor, Python version)
Kali Linux 2017.1  and Python 2.7.13

Unable to set any listener due to ***Unknown syntax error. 

## Screenshot of error, embedded text output, or Pastebin link to the error
![screenshot from 2017-05-21 22-30-32](https://cloud.githubusercontent.com/assets/24611288/26287517/296edbf4-3e75-11e7-9a4a-af7d3ab539b7.png)

**Comment by rvrsh3ll** [comment]
2.0 has new syntax. check it out here http://www.harmj0y.net/blog/empire/the-empire-strikes-back/
