### ISSUE TITLE
Empire does not support using domain fronting over HTTPS

### ISSUE THREAD

**Issue by malcomvetter** [EmpireProject/Empire#533]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
*nix

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Empire supports domain fronting over HTTP, but not HTTPS.  CDNs, such as cloud front, fail to negotiate TLS/SSL or something as we see the TCP packets come in, but Empire does nothing to complete or acknowledge the traffic.

## Screenshot of error, embedded text output, or Pastebin link to the error
NA

## Any additional information
PR coming soon - we ID'ed the problem AND the solution.

**Comment by malcomvetter** [comment]
The solution for this _may_ also resolve this bug:
https://github.com/EmpireProject/Empire/issues/369

**Comment by rvrsh3ll** [comment]
https://media.giphy.com/media/26DOs997h6fgsCthu/giphy.gif

**Comment by mlinton** [comment]
Any updates on the PR for this?

**Comment by Viss** [comment]
![image](https://user-images.githubusercontent.com/1756255/26857825-55e3e778-4ae2-11e7-9af7-b19c7d380fb9.png)

if you force powershell to barf up a proper, usable error, it complains that the 'host' header cannot be modified directly, and this is what is causing the problem. It seems as though either powershell has changed preventing this behavior, or empire has changed the way the headers are modified to a method that doesn't work.

**Comment by malcomvetter** [comment]
@mlinton see @dchrastil's PR. 

@viss that's not an error we saw. We had issues with certs being invalid. Let's see if that error persists after the cert code is in place. Seems like it's a separate issue.

**Comment by xorrior** [comment]
@Viss the exception that you are noting is an entirely different issue. Modifying the host header is only possible with .net v4.0+, hence the ability to add custom headers is always optional.

**Comment by xorrior** [comment]
This is now fixed in #569
