### ISSUE TITLE
Empire doesn't work if there are any non-ASCII chars in path to it

### ISSUE THREAD

**Issue by GoltikRee** [EmpireProject/Empire#534]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)

Kali Linux 2017.1 Rolling, Python v2.7.13

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Empire doesn't start and all the scripts in `setup/ ` don't work if there are any non-ASCII chars in path to it

## Screenshot of error, embedded text output, or Pastebin link to the error

![screenshot](https://cloud.githubusercontent.com/assets/8699645/26523412/b4366974-431f-11e7-9bb7-1fa544d3e541.png)

(As you can see, there is an `я` (https://unicode-table.com/en/044F/) char in path

## Any additional information

**Comment by xorrior** [comment]
Unfortunately, we don't provide any support for unicode characters in Empire right now. We'd certainly appreciate any solutions you may have.
