### ISSUE TITLE
Dropbox Listener fails to execute

### ISSUE THREAD

**Issue by mnzkf07** [EmpireProject/Empire#537]
## Empire Version
2.0 (fetched today)

## OS Information (Linux flavor, Python version)
Ubuntu 16.04.2 LTS
Python 2.7.12

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

The dropbox listener fails to execute, drops a seemingly urllib related error. 

## Screenshot of error, embedded text output, or Pastebin link to the error

> File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/root/Empire/lib/common/helpers.py", line 792, in __run
>     self.__run_backup()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/root/Empire//lib/listeners/dbx.py", line 751, in start_server
>     dbx.users_get_current_account()
>   File "/usr/local/lib/python2.7/dist-packages/dropbox/base.py", line 3277, in users_get_current_account
>     None,
>   File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 239, in request
>     timeout=timeout)
>   File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 330, in request_json_string_with_retry
>     timeout=timeout)
>   File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 414, in request_json_string
>     timeout=timeout,
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 570, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 523, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 643, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 587, in urlopen
>     timeout_obj = self._get_timeout(timeout)
>   File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 302, in _get_timeout
>     return Timeout.from_float(timeout)
>   File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 154, in from_float
>     return Timeout(read=timeout, connect=timeout)
>   File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 94, in __init__
>     self._connect = self._validate_timeout(connect, 'connect')
>   File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
>     "int, float or None." % (name, value))
> ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.
> 
> 

## Any additional information

Some searches said it's to do with requests and urllib being mismatched or dated, I updated everything to latest but the issue still remains. 

Some help would be much appreciated, thanks in advance.

**Comment by xorrior** [comment]
I would setup and install the dropbox pip package on a standalone box. It's a third party module so there isn't much support we can provide.
