### ISSUE TITLE
bunch of errors can not start

### ISSUE THREAD

**Issue by tehseensagar** [EmpireProject/Empire#538]
## Empire Version
latest from repository

## OS Information (Linux flavor, Python version)
Ubunut 14 , python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

./empire 
Traceback (most recent call last):
  File "./empire", line 11, in <module>
    from lib.common import empire
  File "/opt/Empire-master/lib/common/empire.py", line 25, in <module>
    import helpers
  File "/opt/Empire-master/lib/common/helpers.py", line 52, in <module>
    import netifaces
ImportError: No module named netifaces
root@ExPl0I73R:/opt/Empire-master# pip install helpers
Collecting helpers
  Could not find a version that satisfies the requirement helpers (from versions: )
No matching distribution found for helpers
root@ExPl0I73R:/opt/Empire-master# pip install netifaces
Requirement already satisfied: netifaces in /usr/local/lib/python3.4/dist-packages

Any help to get ti run

Regards

**Comment by xorrior** [comment]
Empire is only compatible with python 2.7. You are using the wrong version of python.

**Comment by tehseensagar** [comment]
python -V
Python 2.7.6
