### ISSUE TITLE
Http Listener CertPath change got reverted and is now fixed again

### ISSUE THREAD

**Issue by wonktnod** [EmpireProject/Empire#548]
## Empire Version
Current

## OS Information (Linux flavor, Python version)
n/a

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
The http listener in /lib/listeners/http.py is using the data/empire.pem in any case because a previous change to use the value supplied in CertPath got reverted later. 

The customization was introduced here:
https://github.com/EmpireProject/Empire/commit/1ab09ebb3231989a71b0ba32d8d06fddeb31af53
And then was reverted to the hardcoded value here:
https://github.com/EmpireProject/Empire/commit/8ad39bb3fc7178c3e7bf972200fcf1afaaf14d1e

I have limited time now to check all other changes so please excuse the brevity of this report. There might be other changes that I have missed but it should be easy to create a two liner pull request with this information. 

## Any additional information
This is a duplicate of issue #466

**Comment by xorrior** [comment]
Fixed https://github.com/EmpireProject/Empire/commit/5a530fede9ddd064cd7dfea57ffc3868328ca456
