### ISSUE TITLE
Errors during install.

### ISSUE THREAD

**Issue by linuxdaddy** [EmpireProject/Empire#550]
## Empire Version
Latest, just downloaded it.

## OS Information (Linux flavor, Python version)
Kali Linux

## Screenshot of error, embedded text output, or Pastebin link to the error
![screenshot from 2017-05-31 00-18-22](https://cloud.githubusercontent.com/assets/26394383/26608542/7a57f2ca-459c-11e7-83a2-a1a223d0f9b1.png)
![screenshot from 2017-05-31 00-18-45](https://cloud.githubusercontent.com/assets/26394383/26608557/8784f498-459c-11e7-9e26-efd1cb909506.png)

## Any additional information
Tried pip install pydispatcher and still didnt work.

**Comment by xorrior** [comment]
The pip install is setting up the 3.5 version and not 2.7. Empire uses python 2.7On May 30, 2017 7:01 PM, linuxdaddy <notifications@github.com> wrote:Empire Version
Latest, just downloaded it.
OS Information (Linux flavor, Python version)
Kali Linux
Screenshot of error, embedded text output, or Pastebin link to the error


Any additional information
Tried pip install pydispatcher and still didnt work.

**Comment by linuxdaddy** [comment]
And how do i fix it?

**Comment by xorrior** [comment]
I would suggest changing your default python version:
https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux
