### ISSUE TITLE
bypassuac detected by AV

### ISSUE THREAD

**Issue by themonio** [EmpireProject/Empire#551]
When I try bypassuac this action is detected by the AV. Any hint for this? Thanks!

**Comment by xorrior** [comment]
There are plenty of alternative methods for byassing uac. I would highly suggest doing some research to find them.On May 31, 2017 7:23 AM, themonio <notifications@github.com> wrote:When I try bypassuac this action is detected by the AV. Any hint for this? Thanks!

**Comment by themonio** [comment]
i'm using your tutorial https://www.youtube.com/watch?v=v0zYorQ0eEY but same problem, will keep with the research
