### ISSUE TITLE
Empire error

### ISSUE THREAD

**Issue by iloveboobs1** [EmpireProject/Empire#555]
Traceback (most recent call last):
  File "./empire", line 11, in <module>
    from lib.common import empire
  File "/root/Empire/lib/common/empire.py", line 30, in <module>
    import stagers
  File "/root/Empire/lib/common/stagers.py", line 21, in <module>
    import macholib.MachO
ImportError: No module named macholib.MachO

**Comment by rvrsh3ll** [comment]
What OS are you trying to run this on? And did you run the install?

**Comment by iloveboobs1** [comment]
Im trying to run on Kali I did a ./install.sh

**Comment by rvrsh3ll** [comment]
try "sudo pip install macholib"

**Comment by xorrior** [comment]
@iloveboobs1 can you confirm the install completed successfully?

**Comment by iloveboobs1** [comment]
sudo pip2 install macholib
 Fixed the problem thanks rvrsh3ll
