### ISSUE TITLE
Empire Issue

### ISSUE THREAD

**Issue by c0d3xpl0it** [EmpireProject/Empire#556]
Team,

I am running Empire 2.0 on Kali rolling 2017 edition. But I am not able set up listener, can you guide ?

![image](https://cloud.githubusercontent.com/assets/8144002/26730063/70e561be-47b8-11e7-8580-6193cd71d59f.png)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
See #530

**Comment by c0d3xpl0it** [comment]
Thanks a lot.
