### ISSUE TITLE
usemodule persistence/powerbreach/eventlog  ---but  [!] Exception: 'launcher'

### ISSUE THREAD

**Issue by llovoll** [EmpireProject/Empire#558]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)

kali2.0    Python 2.7.9
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
usemodule persistence/powerbreach/eventlog
execute
[!] Exception: 'launcher'

how can i fix it? thank you

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://cloud.githubusercontent.com/assets/12322093/26755238/fea12c0a-48bb-11e7-8fc2-4f94650e6d75.png)

**Comment by 0xffffe001** [comment]
I'm facing the same issue with this module. I am using the same OS and Python version as @llovoll
https://youtu.be/md6sLIb0nhE
Please @sixdub can you look into this?

**Comment by xorrior** [comment]
@llovoll Most likely the modules need to be updated. We'll check it out.

**Comment by xorrior** [comment]
Fixed in both dev and master
