### ISSUE TITLE
Issue with starting Listener

### ISSUE THREAD

**Issue by aidden-laoch** [EmpireProject/Empire#561]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Kali Linux - Python 2.7.13

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
In the Listener context menu the commands 'run' and 'set' are missing resulting in the inability to start a listener.

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://cloud.githubusercontent.com/assets/24680240/26802969/85ac5292-4a10-11e7-81da-7b50b5e19468.png)

## Any additional information
Maybe its just me and I'm an idiot but I have git cloned this thing three times in different directories and reran the install script to ensure it wasn't just a botched clone. Let me know if I am missing something.

**Comment by aidden-laoch** [comment]
Just realized that I didn't show the results from the list command. Just in case anyone was wondering.

![image](https://cloud.githubusercontent.com/assets/24680240/26803085/ec838666-4a10-11e7-9a3a-0fc6d97afb09.png)

**Comment by necony286** [comment]
change of syntax bro 
http://www.harmj0y.net/blog/empire/the-empire-strikes-back/ heres some help

**Comment by aidden-laoch** [comment]
Thanks! I knew deep down it was me. Figured you guys wouldn't let anything like that happen.
