### ISSUE TITLE
Unexpected error:  <class 'struct.error'>  run empire

### ISSUE THREAD

**Issue by ayanamirins** [EmpireProject/Empire#567]
- [ ] 

- [ ] ##

 Empire Version
2

## OS Information (Linux flavor, Python version)

kali 2017 1 amd64
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

plz.. hellp me..  ./empire  or empire RESTful API  

Unexpected error:  <class 'struct.error'>

why ??
## Screenshot of error, embedded text output, or Pastebin link to the error

![screenshot from 2017-06-07 12-25-03](https://user-images.githubusercontent.com/29249594/26871044-ee0d3cae-4b3f-11e7-8adf-f39a9205c4e2.png)

**Comment by loneferret** [comment]
Getting the same

`root@kali:~/Empire# ./empire
[*] Loading stagers from: /root/Empire//lib/stagers/
[*] Loading modules from: /root/Empire//lib/modules/
[*] Loading listeners from: /root/Empire//lib/listeners/
Unexpected error: <class 'struct.error'>
Unexpected error: <class 'struct.error'>
Unexpected error: <class 'struct.error'>
Unexpected error: <class 'struct.error'>`

**Comment by xorrior** [comment]
@ayanamirins @loneferret I'm really not sure what is causing the error. It'll take some time to figure it out. Do you lose any functionality in empire when this happens? I was able to reproduce this but Empire *seemed* to still work without any issues. Please let me know.

**Comment by jiankeabc** [comment]
I installed it ,run happen the same thing like @loneferret, the software can be run ，but the function can't be use,use listeners-->info can't show any thing to me.

**Comment by ayanamirins** [comment]
empire 또는 empire-web 에서 리스너를 만들수는 있지만 피해자 컴퓨터에 파일을 실행 시켜도 에이전트 연결이 되지 않으며, 리스너생성 오류가 나타남.
현제 empire-master 버전 과 empier-dev 버전 에서만 같은 오류가 발생하며 empire1.6 버전은 아무런 문제없이 사용이 가능함.
또다른 여기서 궁굼한점은 empire-dev & empire-web dev 버전으로 설치를 하여 실행을 할경우 리스너타입에 따라서 추가설정을 따로 해줘야 에이전트 연결이
가능한지 궁굼합니다.

**Comment by ayanamirins** [comment]
Even if I create 'listeners' in empire or empire-web, I can not connect 'agent' even if I run the file on the victim machine.
The same error occurs only in the current empire-master and empier-dev versions.
The empire1.6 version can be used without any problems.
If you are running empire-dev & empire-web dev, you can use 'empire-web' with 'listenersTYPE'
I am wondering if it is possible to connect 'agent' by adding additional setting according to

**Comment by loneferret** [comment]
@xorrior As far as I can tell, no loss of functionality but I'll admit I didn't test out all the modules etc. Time was factor so I switched to a previous version.

**Comment by xorrior** [comment]
Fixed
