### ISSUE TITLE
how can add new module to empire 2?

### ISSUE THREAD

**Issue by backtoback1** [EmpireProject/Empire#568]
## Hello Guys i was trying to add new module to empire V2 i put the module in the right path 
(the powershell script and the python script) but when i run the module it show this error 
[!] Invalid module or agent language version: 'MinLanguageVersion'

Thanks
Regards

**Comment by mr64bit** [comment]
Can you show us the self.info and self.options dictionaries?

**Comment by backtoback1** [comment]
HI @mr64bit 
where i can find this files?

**Comment by xorrior** [comment]
@backtoback1 If you look in empire/lib/modules/ you should see a powershell and python module template. Modify the respective template for your module, then move that module file to the appropriate folder.

**Comment by backtoback1** [comment]
@xorrior the MinLanguageVersion of powershell template is the same with the module i want to import 
both is 2 and i can't edit python version at my module
