### ISSUE TITLE
Listener can not created

### ISSUE THREAD

**Issue by tehseensagar** [EmpireProject/Empire#573]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Kali Linux - Python 2.7

## Screenshot of error, embedded text output, or Pastebin link to the error
[](url)
![85ac5292-4a10-11e7-81da-7b50b5e19468](https://user-images.githubusercontent.com/21223363/27025137-3cb408c0-4f0e-11e7-9078-0f07ebc321f0.png)

It would be greate if any one share the steps to create listener in 2.0 version  . or  guide to get start with 2.0 step by step.

Regards

**Comment by necony286** [comment]
try this
uselistener http

**Comment by tehseensagar** [comment]
well does it have only http for listener nothing else? how do  I check for other listener module?

Regards

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
just press [TAB] after `uselistener` to see all the listeners.

**Comment by tehseensagar** [comment]
@ThePirateWhoSmellsOfSunflowers   thanks.

listeners
uselistener <space> <press-tab>
available listener modules are 

dbx           http_com      http_hop
http          http_foreign  meterpreter
