### ISSUE TITLE
such error:  [!]This script must be run as root

### ISSUE THREAD

**Issue by X1n9** [EmpireProject/Empire#576]
## Empire Version

newest
## OS Information (Linux flavor, Python version)

win7
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
iwant it run in win7, 
bash is allowed, 
but still except such error:  [!]This script must be run as root

PS G:\PenetrationTools\T00Ls\提权exp\powershell\Empire-master\setup> bash ./install.sh
 [!]This script must be run as root

## Screenshot of error, embedded text output, or Pastebin link to the error

![image](https://user-images.githubusercontent.com/21193133/27074481-d1d0b83a-5059-11e7-904a-38b3a6fcad1e.png)

**Comment by xorrior** [comment]
The answer is somewhere in the screenshot you posted. It's self-explanatory.

**Comment by X1n9** [comment]
nonono , actrually.  i had run cmd.exe or bash.exe as administrator alerady ... 
it's still such error 
this is the reason i want to ask my dear xorrior

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
As far as I understand, you want to install Empire on Windows via bash on Windows ? I don't think Empire server is compatible with such setup. Empire (server side) is only compatible with Linux/MacOS.

**Comment by X1n9** [comment]
Thanks for ur relply,  and then I will trying to setup in my kali ...
