### ISSUE TITLE
usestager invalid stager module

### ISSUE THREAD

**Issue by blackolo007** [EmpireProject/Empire#577]
![19197817_1382257978521323_1589402822_o](https://user-images.githubusercontent.com/29411110/27098067-7a2ba0da-50a0-11e7-9789-fd495416d9db.png)
please help me how to fix it

**Comment by 0xffffe001** [comment]
Please refer to Issue #573

**Comment by blackolo007** [comment]
it still not work

**Comment by Fintotini** [comment]
did you solve it? same problem here.

**Comment by lescopaque89** [comment]
still waiting for this release fix "usestager".
When you type "U" then tab2. There are only 2 options which are <uselistener> & <usestager> but <usestager> is invalid stager module.

Hope author/owner able to fix this and provide update for new release.

thanks alot !

**Comment by ghost** [comment]
Having the same problem

(Empire) > usestager
[!] Error: invalid stager module
(Empire) >

**Comment by jiushill** [comment]
Having the same problem
================================================================
 [Version] 2.5 | [Web] https://github.com/empireProject/Empire
================================================================

   _______ .___  ___. .______    __  .______       _______
  |   ____||   \/   | |   _  \  |  | |   _  \     |   ____|
  |  |__   |  \  /  | |  |_)  | |  | |  |_)  |    |  |__
  |   __|  |  |\/|  | |   ___/  |  | |      /     |   __|
  |  |____ |  |  |  | |  |      |  | |  |\  \----.|  |____
  |_______||__|  |__| | _|      |__| | _| `._____||_______|


       285 modules currently loaded

       0 listeners currently active

       0 agents currently active


(Empire) > usestager
[!] Error: invalid stager module
(Empire) >
