### ISSUE TITLE
Unknown syntax

### ISSUE THREAD

**Issue by blackolo007** [EmpireProject/Empire#580]
![screenshot from 2017-06-14 20-56-22](https://user-images.githubusercontent.com/29411110/27135903-f6b22e0a-5143-11e7-9d32-5b4f9e8d5e64.png)

**Comment by axpatito** [comment]
I new version you have to input uselistener and choose between listeners before configuring a listener.

**Comment by X1n9** [comment]
and i'am also accured this problems , 
and i read ur document,

 but i can't find real reason .....

![1111](https://user-images.githubusercontent.com/21193133/27191811-8f4e779e-522b-11e7-8c62-2b05e408b659.png)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Read again : 
[The uselistener command will allow you to select the type of listener. Hitting TAB after this command will show all available listener types](https://github.com/EmpireProject/Empire/wiki/Quickstart#listeners-101)
