### ISSUE TITLE
Unable to launch Empire

### ISSUE THREAD

**Issue by str4n63r** [EmpireProject/Empire#583]
Empire Version - Latest source code from Github

OS Information - Kali Linux 2016 R2 (32-Bit)

After successful installation tried launching Empire from **./empire** executable and received below error:
Error Reference: **[https://pastebin.com/kBLqva3q](https://pastebin.com/kBLqva3q)**

**Comment by xorrior** [comment]
Try running reset.shOn Jun 20, 2017 7:25 AM, Venkata Sateesh Netti <notifications@github.com> wrote:Empire Version - Latest source code from Github
OS Information - Kali Linux 2016 R2 (32-Bit)
After successful installation tried launching Empire from ./empire executable and received below error:
Error Reference: https://pastebin.com/kBLqva3q

**Comment by str4n63r** [comment]
@xorrior Thanks a lot man. This solved my problem.

**Comment by xorrior** [comment]
@str4n63r your welcome.
