### ISSUE TITLE
Dropbox listener issues discovered

### ISSUE THREAD

**Issue by Viss** [EmpireProject/Empire#587]
## Empire Version
newest out of dev branch, 6/22/2017

## OS Information (Linux flavor, Python version)
attacking machine is ubuntu, target machine is a mac on the newest version of macos

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I have found a number of issues pertaining to the dropbox stager. They are mostly logical or order-of-operation issues.

- When exiting an agent, empire should delete the agents files from dropbox. 
- When an agent disappears (is found, box is rebooted etc), issuing the command "remove <agent>" should delete the files from dropbox

**Comment by xorrior** [comment]
Truth be told, I kind of knew about these issues. I just forgot and was lazy. I'll get to this in the next day or two @Viss .

**Comment by xorrior** [comment]
@Viss When exiting an agent there aren't any files left in the dropbox folders besides the stagers for python and powershell. Once the "[!] Agent ..... exiting" message has been displayed, the corresponding results file has already been deleted. I wasn't able to replicate that particular issue in testing. The remove command only removes agents from the database and cache. If for some reason empire is restarted and there are files pertaining to lost agents in dropbox, they should be manually removed.
