### ISSUE TITLE
Python Agent: continuity issues

### ISSUE THREAD

**Issue by Viss** [EmpireProject/Empire#588]
## Empire Version
newest dev branch, 6/22/17

## OS Information (Linux flavor, Python version)
ubuntu on the server, newest macos on victim

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

The mechanism by which agents identify themselves to empire should include a routine which takes into consideration the empire installation may have been restarted, empire "removed an agent", and should recreate the files for itself. Ideally, if an orphaned shell comes back to life, empire should be able to handle it. This process is currently broken, this is what happens instead:

![image](https://user-images.githubusercontent.com/1756255/27465070-f648e074-5785-11e7-88ac-d1fb35ee538f.png)

This was a domain fronting agent attempting to reconnect through cloudfront.

It does this forever until you find and kill the errant agent. There is no way to 'recover' from this, as the errant agent will continue to try contacting the c2, but the listener can't seem to reconnect, so this flood is perpetual. Empire should understand what to do when a shell that's been 'removed' comes back to life and tries to reconnect.

To recreate this issue, all you have to do is shell a mac, then type 'remove all' in the agents context in empire. The errant shell will attempt to reconnect like this forever.

**Comment by xorrior** [comment]
I'll take a look. I think I know where this needs to be fixed.

**Comment by xorrior** [comment]
The powershell agent is fixed and will re-negetiate if it reports its self orphaned. Unfortunately on the python side,  any attempts to execute the re-negotiate function will fail as it is i a different namespace???
