### ISSUE TITLE
Python Agent: Emoji in command responses breaks the agent

### ISSUE THREAD

**Issue by Viss** [EmpireProject/Empire#589]
## Empire Version
newest out of dev, 6/22/17

## OS Information (Linux flavor, Python version)
server ubuntu, target newest macos

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

On a live engagement I encountered a machine which had a single emoji character as its hostname. This broke empire, and agents would fail to connect from this host. The following error messages were displayed:

![image](https://user-images.githubusercontent.com/1756255/27465321-a73a3684-5787-11e7-897a-b2c6c69c2056.png)

![image](https://user-images.githubusercontent.com/1756255/27465329-af007ffe-5787-11e7-8eaf-c742c5aea2d2.png)

**Comment by rvrsh3ll** [comment]
lol, will look into this for sure. If you have a fix, PR please!

**Comment by killswitch-GUI** [comment]
this is a unicode issue. I have a parser for this! Will take a look

**Comment by killswitch-GUI** [comment]
Can not replicate @Viss 
<img width="610" alt="screen shot 2017-07-27 at 10 03 06 am" src="https://user-images.githubusercontent.com/8761706/28682739-e4e639b0-72b2-11e7-96c1-7c1cf7009998.png">

Please provide some more info or maybe you can replicate. At the moment it seems like the unicode parsing is correctly working. Are you sure it was in the hostname?

**Comment by Viss** [comment]
Ah, I should have specified.
The victim in this case was a mac. 
and the shell was python.

I guess this is a non issue on windows boxes with powershell agents. 
Python though, starts fires :D

**Comment by killswitch-GUI** [comment]
@Viss ahh ok ty for update will check it out!

**Comment by killswitch-GUI** [comment]
@Viss pull request open!

**Comment by rvrsh3ll** [comment]
Merged into Dev @Viss

**Comment by jeffmcjunkin** [comment]
For posterity: :banana: 4eva
