### ISSUE TITLE
uselistener/usestager command doesn't display the supported listerners/stagers information

### ISSUE THREAD

**Issue by mpras123** [EmpireProject/Empire#595]
## Empire Version
Empire version 2.0

## OS Information (Linux flavor, Python version)
Kali lunux - up to date

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
the uselistener and usestager commands doesn’t display the list of supported listeners/stages instead it simple throws an error message-
(Empire: listeners) > uselistener
[!] Error: invalid listener module
(Empire: listeners) >

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://user-images.githubusercontent.com/16981983/27686868-4334314c-5cf2-11e7-9c3d-8d52b2c6b5b7.png)

**Comment by 0xffffe001** [comment]
Please take a look at issue #577

**Comment by mpras123** [comment]
thanks but didn't work..

**Comment by majidabdul82** [comment]
same here not working even after giving **[TAB] right after usestager**

**Comment by liteman** [comment]
uselistener<space><tab>

**Comment by majidabdul82** [comment]
**[Yes it is working. Thanks alot]**

**Comment by eqhaleel** [comment]
i have thesame error,can anyone help?

**Comment by majidabdul82** [comment]
bro eqhaleel, try with uselistener[ space ][ tab ][ tab ]

**Comment by mpras123** [comment]
thanks for the tip, uselistener[ space ][ tab ][ tab ] - worked for me

On Tue, Aug 1, 2017 at 12:59 PM, DynamicHackerBoys <notifications@github.com

**Comment by xorrior** [comment]
Closing

**Comment by eqhaleel** [comment]
thanks alot @majidabdul82 how can i hack outside my network with the empire framework?
