### ISSUE TITLE
Feature Request: Asterisk (*) on use/searchmodule tab completion to designate that elevated context is required

### ISSUE THREAD

**Issue by arch4ngel** [EmpireProject/Empire#598]
## Empire Version

~~Sadly, I'm not sure how to identify the exact version of Empire.~~

_edit:_ Version: 1.6 (I'll learn how to Git someday)

## OS Information (Linux flavor, Python version)

Linux flavor, Python version

## Expected behavior and description of the error, including any actions taken immediately 

prior to the error. The more detail the better.
When tab completing use/searchmodule, suffix each module name with an asterisk if the module requires an elevated context.

## Screenshot of error, embedded text output, or Pastebin link to the error

![current output](https://user-images.githubusercontent.com/11574161/27775436-f85d3f62-5f6f-11e7-855f-7fca2b18e43f.png)

![selection_062](https://user-images.githubusercontent.com/11574161/27775652-21fd46e4-5f72-11e7-9739-0c8d68bebfc0.png)

_edit:_ Added a more recent modified output.

Note the asterisks suffixed to each module name where an elevated context is required

## Any additional information

I recently began exploring Empire a lot more recently and I've found it very intuitive and useful! Unless I'm overlooking some configuration or notation, I haven't been able to discern which modules require an elevated context when tab completing use/searchmodule. I'll be following up with a pull request for version I patched up. Quick and easy!

**Comment by xorrior** [comment]
@arch4ngel I'll take a look at your PR. Thanks for the help man.
