### ISSUE TITLE
Plaintext passwords containing spaces not populating creds (manual add fails as well)

### ISSUE THREAD

**Issue by Liberator69** [EmpireProject/Empire#602]
## Empire Version
2.0 (built a few days ago)

## OS Information (Linux flavor, Python version)
Debian 9 (updated a few days ago)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Mimikatz run should populate creds. Works fine with hashes and any plaintext passwords not containing spaces. Manual add fails as well as it looks like delimiter being used must be a space. Tried single quoting, double quoting, and escaping with \ and no go.

**Comment by shannonmcmurtrey** [comment]
I think this is also an issue with invoke_wmi; but I'm seeing the problem with passwords containing quotation marks.  I can add the password; but when I run the module I get the following error:Unexpected token '^gi8<ZVwep' in expression or statement. which contains the portion of the password following the quotation mark.  The quotation mark in the password is the 12th or 13th character, and immediately precede the ^gi8 in the string above.

**Comment by jihadLkmaty218** [comment]
interesting Is there any explanation for some pictures of the error::)

**Comment by rvrsh3ll** [comment]
I found the issue. Cred store parsing and adding needs a bit of an overhaul. Working it. Thanks again for the info

**Comment by killswitch-GUI** [comment]
@rvrsh3ll how did this go? need me to test the branch?

**Comment by xorrior** [comment]
fixed in the dev brach @Liberator69
