### ISSUE TITLE
Problem post installation

### ISSUE THREAD

**Issue by pepino87** [EmpireProject/Empire#605]
I downloaded the version that is in github but at the moment of executing the application I get the following error

Traceback (most recent call last):

  File "./empire", line 11, in <module>

     From lib.common import empire

  File "/root/Empire/Lib/common/empire.py", line 14, in <module>

     From pydispatch import dispatcher

  ImportError: No module named pydispatch

The version where empire was installed is Linux Kali-2016-1 4.6.0-kali1-amd64 # 1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU / linux

please help
![error empire](https://user-images.githubusercontent.com/29956053/27930078-552406b8-6263-11e7-9d81-860f703581ed.PNG)

**Comment by Chiggins** [comment]
Did you run the `./setup/install.sh` command? It looks like you're missing the `pydispatch` module, which would be installed by running the `install.sh` script. Be sure to read the [quick start](https://github.com/EmpireProject/Empire/wiki/Quickstart) to avoid running into errors like this.

**Comment by rvrsh3ll** [comment]
^ What he said 👍 Let us know if you still have issues!
