### ISSUE TITLE
Cannot start Empire

### ISSUE THREAD

**Issue by amfad** [EmpireProject/Empire#607]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Ubuntu 14.04.5 LTS

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I am unable to launch empire. I keep getting the following error

## Screenshot of error, embedded text output, or Pastebin link to the error

/home/ubuntu/Empire# ./empire
Traceback (most recent call last):
  File "./empire", line 1294, in <module>
    main = empire.MainMenu(args=args)
  File "/home/ubuntu/Empire/lib/common/empire.py", line 75, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist')
TypeError: 'NoneType' object is not iterable

**Comment by rvrsh3ll** [comment]
Have you tried resetting the DB with ./reset.sh  ?

**Comment by wifiuk** [comment]
i have the same issue

**Comment by wifiuk** [comment]
reset fixed it for me
