### ISSUE TITLE
Feature request - Twitter listener

### ISSUE THREAD

**Issue by tristandostaler** [EmpireProject/Empire#611]
I was thinking it could be interesting to do a listener that goes through twitter like this tool:
https://github.com/PaulSec/twittor
That way, it would be more difficult to just block the IP of the C&C server.

**Comment by rvrsh3ll** [comment]
Great idea! We are always looking into more third-party c2 channels to implement within Empire. Closing this for now but, we hope to work on this feature in the future. Thanks!

**Comment by tristandostaler** [comment]
Great! It's a pleasure and thanks!
