### ISSUE TITLE
Feature Request:  BlackList for Credentials

### ISSUE THREAD

**Issue by Wh1teHat65** [EmpireProject/Empire#619]
Is it possible to add an option to Blacklist credentials; prevent use & storage?  

Use Cases:

- Engagements where both a credentialed vuln scan & pentest are occurring via two separate teams. 
- On Cyber ranges where the creds of the range admin may be stored for troubleshooting purposes  

If there is a way to do this now, any references would be greatly appreciated.  If there is a more appropriate location for this feature request, please let me know.

Thank-you to the team for such an Awesome tool.

**Comment by rvrsh3ll** [comment]
Odd request but, we'll surely look into it.

**Comment by rvrsh3ll** [comment]
Hello, we've decided not to support this request. Thank you for the info.

**Comment by Wh1teHat65** [comment]
Thank-you for your consideration.
