### ISSUE TITLE
Empire listeners types and their metasploit analogues

### ISSUE THREAD

**Issue by sash322** [EmpireProject/Empire#623]
Hello, can you please specify the types of listeners in the empire 2.0 http\meterpreter...etc and their analogs in metasploit. For example, I have a session opened in msf and I want to migrate to Empire using the **windows/manage/payload_inject module**
What types of msf payloads corresponds to the listeners in the empire? Sorry for bad english.

**Comment by xorrior** [comment]
@sash322  your best bet is to use the empire dll. This is just a reflective dll that will host the CLR, load the PowerShellRunner assembly, and execute an empire stager.
