### ISSUE TITLE
rest api separate certificate, and client verification

### ISSUE THREAD

**Issue by vvalien** [EmpireProject/Empire#626]
You can file this under enhancement.

I have recently been working with the rest api and would like empire to have the ability to define a separate certificate to use with rest.

I also think there should be a option to enable client certificate checking, this would greatly increase the security especially if the rest port is internet facing.

We could also add a little helper script to generate the needed certificates, just like the one we currently have.

Thank you.

**Comment by xorrior** [comment]
We won't be able to implement this feature request at this time. Thanks.
