### ISSUE TITLE
Issue with empire

### ISSUE THREAD

**Issue by usmarine2141** [EmpireProject/Empire#628]
## Empire Version
fresh git clone

## OS Information (Linux flavor, Python version)
Parrot OS

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
when running sudo ./empire to start empire

get the following 

Traceback (most recent call last):
  File "./empire", line 1294, in <module>
    main = empire.MainMenu(args=args)
  File "/home/blob/Empire/lib/common/empire.py", line 75, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist')
TypeError: 'NoneType' object is not iterable

**Comment by rvrsh3ll** [comment]
run reset.sh in the setup folder. Let me know if that fixes your issue.

**Comment by usmarine2141** [comment]
It did not. I resolved it myself.

**Comment by killswitch-GUI** [comment]
cool looks like a bad ip in the list? either way cool.
