### ISSUE TITLE
REST API agents/Y/kill fails

### ISSUE THREAD

**Issue by ElysiumSecurity** [EmpireProject/Empire#631]
## Empire Version

2.0
## OS Information (Linux flavor, Python version)
kali linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
curl --insecure -i -H "Content-Type: application/json" https://localhost:1337/api/agents/qsdfqsdfqsdf/kill?token=qsdfqsdfqsdf

>> "NameError("global name 'sessionID' is not defined",)"
## Screenshot of error, embedded text output, or Pastebin link to the error

"NameError("global name 'sessionID' is not defined",)"
## Any additional information

Commenting line 1036 fixes the issue

**Comment by killswitch-GUI** [comment]
you can confirm that was a active agent right @ElysiumSecurity ?

**Comment by ElysiumSecurity** [comment]
Yes @killswitch-GUI

**Comment by backlion** [comment]
emprie is not run dll and nothing shell!

**Comment by xorrior** [comment]
Fixed
