### ISSUE TITLE
class 'struct.error' ... again

### ISSUE THREAD

**Issue by kureeoffsec** [EmpireProject/Empire#648]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
kali and ubuntu, both fully updated

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
The following errors are displayed on server start up. 
[*] Loading stagers from: /pentest/Empire//lib/stagers/
[*] Loading modules from: /pentest/Empire//lib/modules/
[*] Loading listeners from: /pentest/Empire//lib/listeners/
Unexpected error: <class 'struct.error'>
Unexpected error: <class 'struct.error'>
Unexpected error: <class 'struct.error'>
Unexpected error: <class 'struct.error'>

Once started up, agents cannot connect to and interact with the C2 server over https. 

## Any additional information
The http listener appears to work with this setup.

**Comment by katsu-sec** [comment]
check xorrior's fix for this:
https://github.com/EmpireProject/Empire/commit/37c72f0428d68edc36d4e19ee3540770ef12d981

**Comment by theguly** [comment]
fix the error but listeners menu doesn't work:
![screen shot 2017-08-25 at 09 40 37](https://user-images.githubusercontent.com/1745802/29704309-8c8d35d8-8979-11e7-9382-945ef67d08b9.png)

(latest kali as of today)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
`uselistener [tab] [tab]` to see available listeners

**Comment by xorrior** [comment]
@kureeoffsec fixed.
