### ISSUE TITLE
[Feature Request] Auto Run Modules At Start

### ISSUE THREAD

**Issue by zero77** [EmpireProject/Empire#653]
Can you add the option to set modules to automatically run the first time a new agent connects.
For example, if a new agent connects run the bypassuac and then a persistent module or, any other modules the user selects to run.
Thanks

**Comment by Gilks** [comment]
You can set modules to autorun. Go into the module you want to run and put "autorun" in the Agent field and then type execute. Any new agents that come in will automatically run the module.

**Comment by qbiguenet** [comment]
Could be nice to run more than 1 module and based on the failure or success of the first one.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
You can use the API and a small script to chain modules. IMO it is the best solution.

**Comment by xorrior** [comment]
@zero77 This was done in #750. Its now in the dev branch.

**Comment by zero77** [comment]
@xorrior 
Ok thanks, is this documented in the wiki or somewhere else.
