### ISSUE TITLE
dropbox listener

### ISSUE THREAD

**Issue by jak12801** [EmpireProject/Empire#660]
what is the dropbox listener name?
dropbox or dbx?
when I use dbx and launcher powershell
there is error:
[!] Invalid listener: dropbox
[!] Error in launcher command generation.

**Comment by utkusen** [comment]
it's dbx. Use following path:

(Empire) > listeners
(Empire: listeners) > uselistener dbx
(Empire: listeners/dbx) > info

Now you will see options
