### ISSUE TITLE
Empire do not start

### ISSUE THREAD

**Issue by DrLafa** [EmpireProject/Empire#661]
## Empire Version
- Version 2.1 Master Release
8/28/2017

## OS Information (Linux flavor, Python version)
Kali linux 2017.1 i686
Linux 4.9.0-kali4-686-pae

Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
Python 3.5.4 (default, Aug 12 2017, 14:08:14)

## Expected behavior and description of the error.
What i do:
1. git clone https://github.com/EmpireProject/Empire.git
2. cd /Empire
3. ./setup/install.sh
4. ./empire
5. got this problem:

Traceback (most recent call last):
  File "./empire", line 1294, in <module>
    main = empire.MainMenu(args=args)
  File "/root/Empire/lib/common/empire.py", line 75, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

## Screenshot
![_2017-08-29_14-22-39](https://user-images.githubusercontent.com/24232540/29818563-8a0c20ae-8cc5-11e7-9a76-3aa82a3413f7.png)

**Comment by cjensenius** [comment]
@DrLafa - I had a similar issue earlier this morning, if you run the reset script does it resolve your issue?

**Comment by DrLafa** [comment]
@cjensenius I saw that install.sh try to install .deb - packages with x64 architecture, but i have i386. Some packages no was in i386 architecture, so Empire can not work in it.
