### ISSUE TITLE
Unable to get any options at all

### ISSUE THREAD

**Issue by mandy136** [EmpireProject/Empire#666]
## Empire Version
2.1
## OS Information (Linux flavor, Python version)
4.6.0-kali1-amd64
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I have recently git cloned Empire, run ./setup.sh. When I run Empire i am unable to get any options for example:

(Empire) > listeners
[!] No listeners currently active 
(Empire: listeners) > options
*** Unknown syntax: options
(Empire: listeners) > uname -r
*** Unknown syntax: uname -r
(Empire: listeners) > help

Listener Commands
=================
agents            Jump to the Agents menu.
back              Go back to the main menu.
exit              Exit Empire.
help              Displays the help menu.
info              Display information for the given active listener.
kill              Kill one or all active listeners.
launcher          Generate an initial launcher for a listener.
list              List all active listeners (or agents).
main              Go back to the main menu.
uselistener       Use an Empire listener module.
usestager         Use an Empire stager.

(Empire: listeners) > set Name eternal
*** Unknown syntax: set Name eternal
(Empire: listeners) >

**Comment by utkusen** [comment]
You don't have any active listener, therefore you can't use every option. To setup a listener:

>listeners
>help (you can see available options)
>uselistener -TABTAB- (you will see listener methods)
For example: >uselistener http
>info (you will see options for http listener)
>set Name eternal
>set Blablabla
>execute

Now you have a listener and you can use the other options
