### ISSUE TITLE
Unable to create a stager with dropbox listener

### ISSUE THREAD

**Issue by utkusen** [EmpireProject/Empire#668]
## Empire Version
2.1 (31 August 2017)

## OS Information (Linux flavor, Python version)
Kali Linux 2017.1, Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I created a dropbox listener, and trying to create a stager for it. But when I select multi/launcher or any powershell stager, I got following Error (even obfuscation option is False)

`[!] Exception: generate_launcher() got an unexpected keyword argument 'obfuscate'`

## Screenshot of error, embedded text output, or Pastebin link to the error

https://i.imgur.com/tgdScxR.png

**Comment by xorrior** [comment]
I just fixed this issue a few hours ago. Thanks

**Comment by xorrior** [comment]
The fix is on the dev branch. I'll push it to master as well
