### ISSUE TITLE
Incorrect Filename Description in Setup Script

### ISSUE THREAD

**Issue by recrudesce** [EmpireProject/Empire#669]
The file detailed in the print statement at the location below is incorrect.
https://github.com/EmpireProject/Empire/blob/master/empire#L37

That line should read `print helpers.color("[!] Please run setup_database.py")` as that's what the file is called on the filesystem

https://github.com/EmpireProject/Empire/blob/master/setup/setup_database.py

**Comment by xorrior** [comment]
fixed in master/dev
