### ISSUE TITLE
ImportError: No module named OpenSSL 

### ISSUE THREAD

**Issue by reubadoob** [EmpireProject/Empire#671]
## Empire Version

2.1

## OS Information (Linux flavor, Python version)

Linux kali 4.4.50-v7 #1 SMP Fri Apr 21 01:18:29 CDT 2017 armv7l GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
root@kali:~ apt update
Hit:1 http://kali.localmsp.org/kali kali-rolling InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
root@kali:~ uname -a
Linux kali 4.4.50-v7 #1 SMP Fri Apr 21 01:18:29 CDT 2017 armv7l GNU/Linux
root@kali:~ cd Empire
root@kali:~/Empire ls
changelog  data  empire  lib  LICENSE  README.md  setup
root@kali:~/Empire ./empire
Traceback (most recent call last):
  File "./empire", line 7, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL
root@kali:~/Empire cd setup
root@kali:~/Empire/setup ls
bomutils  get-pip.py  reset.sh		 xar-1.5.2
cert.sh   install.sh  setup_database.py
root@kali:~/Empire/setup# ./reset.sh

 [>] Enter server negotiation password, enter for random generation: toor

 [*] Database setup completed!

Traceback (most recent call last):
  File "./empire", line 7, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL

## Any additional information
I am currently running 
root@kali:~# openssl version
OpenSSL 1.1.0f  25 May 2017

**Comment by xorrior** [comment]
@reubadoob did you run the install script?

**Comment by reubadoob** [comment]
Yup.

**Comment by xorrior** [comment]
try pip install pyOpenSSL

**Comment by reubadoob** [comment]
root@kali:~# pip install pyOpenSSL
Collecting pyOpenSSL
  Using cached pyOpenSSL-17.2.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pyOpenSSL)
Collecting cryptography>=1.9 (from pyOpenSSL)
  Using cached cryptography-2.0.3.tar.gz
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.9->pyOpenSSL)
Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->pyOpenSSL)
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=1.9->pyOpenSSL)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting ipaddress (from cryptography>=1.9->pyOpenSSL)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting cffi>=1.7 (from cryptography>=1.9->pyOpenSSL)
  Using cached cffi-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    unable to execute 'arm-linux-gnueabihf-gcc': No such file or directory
    unable to execute 'arm-linux-gnueabihf-gcc': No such file or directory
    
        No working compiler found, or bogus compiler options
        passed to the compiler from Python's distutils module.
        See the error messages above.
        (If they are about -mno-fused-madd and you are on OS/X 10.8,
        see http://stackoverflow.com/questions/22313407/ .)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3rvQTQ/cffi/

**Comment by rvrsh3ll** [comment]
You're trying to install Empire on an ARM image. This is not supported yet. Will be soon.

**Comment by rvrsh3ll** [comment]
https://books.google.com/books?id=PndJDAAAQBAJ&pg=PA109&lpg=PA109&dq=pyopenssl+arm&source=bl&ots=Qimgr94nCq&sig=y05Bs2Ftz4Aif636S0z5N0Gpe-E&hl=en&sa=X&ved=0ahUKEwi7i9fU8ITWAhUM5IMKHUdxBqoQ6AEIcDAM#v=onepage&q=pyopenssl%20arm&f=false

**Comment by milnomada** [comment]
`pip install pyOpenSSL --upgrade` worked
