### ISSUE TITLE
collection/linux modules are not working

### ISSUE THREAD

**Issue by utkusen** [EmpireProject/Empire#678]
## Empire Version
2.1

## OS Information (Linux flavor, Python version)
Kali Linux 2017.1, Python

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When I try to use the modules below, I got following error:

`Exception: generate() takes exactly 1 argument (3 given)`

```
collection/linux/hashdump* 
collection/linux/keylogger
collection/linux/mimipenguin*
collection/linux/pillage_user
collection/linux/sniffer*
```

Screenshot: https://i.imgur.com/kAEbAB0.png

**Comment by rvrsh3ll** [comment]
Thanks for pointing these out. Will get them fixed shortly.

**Comment by xorrior** [comment]
Fixed all of the osx/linux generate function definitions for each module in the dev branch.
