### ISSUE TITLE
KillDate parameter set on listener and not apply to agents.

### ISSUE THREAD

**Issue by qbiguenet** [EmpireProject/Empire#689]
When i set a Killdate parameter to my listener, I expected Agents to be configure with the same date but I seems not.
I used the follwowing command to set the killdate after agents was active :  
`Usage: 'killdate [agent/all] [01/01/2016]'`
I would be nice if the Agents have the killdate automatically set based on the listener configuration.

Could be also nice to have the killdate information in the agent list to see if they all have the same, or not.

Thx :)

**Comment by xorrior** [comment]
Working on it. Fixed the PowerShell agent. Fighting with the python agent currently.

**Comment by xorrior** [comment]
fixed 3d7a07a
