### ISSUE TITLE
AttributeError: 'module' object has no attribute 'rand'

### ISSUE THREAD

**Issue by ianhawes** [EmpireProject/Empire#697]
## Empire Version
2.1

## OS Information (Linux flavor, Python version)
Ubuntu 16.04, Python 2.7.12

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Fails on start

## Screenshot of error, embedded text output, or Pastebin link to the error
```
Traceback` (most recent call last):
  File "./empire", line 11, in <module>
    from lib.common import empire
  File "/opt/Empire/lib/common/empire.py", line 27, in <module>
    import agents
  File "/opt/Empire/lib/common/agents.py", line 68, in <module>
    import encryption
  File "/opt/Empire/lib/common/encryption.py", line 62, in <module>
    random_function = OpenSSL.rand.bytes
AttributeError: 'module' object has no attribute 'rand'
```

## Any additional information
Appears to be related to pyca/pyopenssl#675

**Comment by tr1ll** [comment]
pip install 'pyopenssl==17.2.0'

**Comment by ilyaglow** [comment]
It seems that deprecated `OpenSSL.rand.bytes` function should be replaced by `os.urandom`

**Comment by xorrior** [comment]
Modified the pip install statement in the install script. Should be fixed now
