### ISSUE TITLE
how to resolve the TypeError

### ISSUE THREAD

**Issue by fifysky** [EmpireProject/Empire#705]
Traceback (most recent call last):
  File "./empire", line 1286, in <module>
    main = empire.MainMenu(args=args)
  File "/home/fifysky/Empire-master/lib/common/empire.py", line 75, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

**Comment by pctripsesp** [comment]
same error here
```
Traceback (most recent call last):
  File "./empire", line 1286, in <module>
    main = empire.MainMenu(args=args)
  File "/root/Empire/lib/common/empire.py", line 75, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable
```
Using Debian with kali repos, Linux version 3.2.0-4-amd64

**Comment by pctripsesp** [comment]
**Reinstallation worked for me:**
as root:
```
Remove directory 
rm -Rf Empire/
apt-get update && apt-get dist-upgrade
git clone https://github.com/EmpireProject/Empire.git
cd Empire/
cd setup/
./install.sh
cd ..
./empire
```

**Comment by jdmcwhinnie** [comment]
The current PCI spec strictly states that only TLS 1.2 is supported due to insecurities found in 1.0/1.1.

I think this is the problem.

**Comment by jdmcwhinnie** [comment]
got it to work by running reset.sh from Setup folder
