### ISSUE TITLE
Cannot create a Listener. "info" command not working as expected.

### ISSUE THREAD

**Issue by computersAreBuggedByNature** [EmpireProject/Empire#706]
## Empire Version
Latest, Downloaded today. Currently 276 Modules.

## OS Information (Linux flavor, Python version)
Kali Linux Rolling 2017, updated and upgraded.
Also tried inside virtualbox with another Kali Linux 2017.

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
After "git clone https://github.com/EmpireProject/Empire",
And after it's proper installation without errors ("./setup/install.sh"),
And after "./empire", or "sudo ./empire",
when the menu opens and I type "listeners", then I should be able to create my listeners by issuing "info" and getting the relative parameters, setting them up properly, and then executing, as explained in every tutorial and at https://powershellempire.com/?page_id=110 .

## Screenshot of error, embedded text output, or Pastebin link to the error
The problem is that issuing "info" does not work:
Here are the logs. What follow after "//" are of course my personal comments..

(Empire) > // once the main menu is loaded (it loads correctly as expected)
(Empire) > listeners // I type in "listeners" to jump to the listeners page
[!] No listeners currently active // I guess this is expected since I've just installed Empire.
(Empire: listeners) > info // I type in "info" expecting it to print out the beautiful options page, stating everything I can and cannot set about the listener.
[!] Invalid listener name
(Empire: listeners) >

That's it. I've tried every option in the menus (using "help"), there's no way around it.

## Any additional information
It keeps saying "Invalid listener name" when I issue "info" inside of "(Empire: listeners) > ", HOW AM I SUPPOSED TO SPECIFY A LISTENER's NAME  IF I CAN'T FIRST CREATE ONE?

I can't do anything without firstly setting up the Listener, so please help me out! I can't see why it's not working...

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
`uselistener [tab][tab]` to choose your listener type

**Comment by computersAreBuggedByNature** [comment]
Worked Wonderfully. A very deep Thank you.
Solved, can be Closed.
