### ISSUE TITLE
Consider not using pycrypto

### ISSUE THREAD

**Issue by edermi** [EmpireProject/Empire#707]
## Empire Version
Latest

## OS Information (Linux flavor, Python version)
All

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
While skimming the setup script, I noticed that pycrypto is used.
According to 
- https://theartofmachinery.com/2017/02/02/dont_use_pycrypto.html
- https://github.com/dlitz/pycrypto/issues/238
- and the list of issues as well as the activity on the project

one should not use pycrypto anymore because it's considered unmaintained and contains several (at least one security relevant) bugs.

[pycryptodome](https://pypi.python.org/pypi/pycryptodome) provides a maintained drop-in replacement.

**Comment by xorrior** [comment]
@edermi Thanks for pointing this out. Hopefully we can have this update before EOY.

**Comment by xorrior** [comment]
I've done some testing with this @edermi and everything seems to work. I'll do some additional testing this week and merge if everything checks out.

**Comment by xorrior** [comment]
@edermi I'm going to close this out for now. I'm not sure if we'll ever make this change.
