### ISSUE TITLE
RESTful API upload uses hashlib that is not imported

### ISSUE THREAD

**Issue by jymcheong** [EmpireProject/Empire#710]
## Empire Version
2.1

## OS Information (Linux flavor, Python version)
macOS Sierra 
python 2.7.13

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Was using the API to upload a file but got error "global name 'hashlib' is not defined" from response. I narrow down to https://github.com/EmpireProject/Empire/blob/086df98ed93ad06d31ae061b1e1ec70d69438796/empire#L911 

Adding a import hashlib at the beginning fixed it.

## Any additional information

**Comment by xorrior** [comment]
Added hashlib import statement
