### ISSUE TITLE
Feature Request: SOCKS for (DBX) Listeners

### ISSUE THREAD

**Issue by IljaSchumacher** [EmpireProject/Empire#715]
Greetings Fellows,

I have a little feature request.
Could we have SOCKS support for the Listeners please?

Basically we just need to add the following before any import of urllib2:

import socks
import socket
SOCKSIP="127.0.0.1"
PORT=XXXXX
socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, SOCKSIP , PORT)
socket.socket = socks.socksocket

Add config options to the listener.
And then add PySocks to the install.sh

It works very well with dbx.py.

I tested it with TOR and it correctly connected to dropbox via TOR SocksPort.
(tcpdump -i lo shows empire communicating with the remote agent)

(DNS leaking etc has yet to be monitored, but I think that should be fine if you use a local dns server and block certain stuff. Just in case some other module tries to ignore the socks.socket)

(I'd make a quick pullRequest but I tested with the ObfuscatedEmpire fork)

Many thanks in advance.

**Comment by xorrior** [comment]
This sounds like a great idea man and I'm going to strongly encourage you to do the leg work on the PR for this one. Thanks!

**Comment by IljaSchumacher** [comment]
Done, Submitted Pull Request #721.
Works like a charm on the dev branch, via TOR, with and w/o using SOCKS.
