### ISSUE TITLE
Kill Agent Confirmation Doesn't Work

### ISSUE THREAD

**Issue by metac0rtex** [EmpireProject/Empire#716]
## Empire Version
2.1

## OS Information (Linux flavor, Python version)
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie

$ python --version
Python 2.7.9

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When executing the "kill" command and enter "N" at the kill confirmation line, the agent shouldn't be killed.

## Screenshot of error, embedded text output, or Pastebin link to the error
(Empire: agents) > kill 6A1C78WZ
[>] Kill agent '6A1C78WZ'? [y/N] y
(Empire: agents) > kill 2BXFCGZV[!] Agent 6A1C78WZ exiting
[!] Agent 6A1C78WZ not active.

[>] Kill agent '2BXFCGZV'? [y/N] N
(Empire: agents) >
(Empire: agents) >
(Empire: agents) >
(Empire: agents) > [!] Agent 2BXFCGZV exiting
(Empire: agents) > list
[!] No agents currently registered

**Comment by 0x1c** [comment]
Confirmed, the logic is never checked in do_kill() in lib/common/empire.py.

**Comment by xorrior** [comment]
Now fixed.
