### ISSUE TITLE
How to fix sqlite3.OperationalError: no such table: config?

### ISSUE THREAD

**Issue by Deathlive** [EmpireProject/Empire#717]
OS Android 5.1, Termux 
I install all requirements, but shows this error.
![123](https://user-images.githubusercontent.com/29791715/30771416-9957fc80-a058-11e7-842e-df104e2a6973.png)

**Comment by Ibrahimous** [comment]
Hi @Deathlive, I ran into the same problem, how did you solve it ?
Thx

**Comment by DakotaNelson** [comment]
Have you run the [setup scripts](https://github.com/EmpireProject/Empire/wiki/Quickstart)?

**Comment by Ibrahimous** [comment]
Hi @DakotaNelson, yes of course.

I was able to reproduce the problem by doing the following (on Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux), as root:

```
#apt-get update && apt-get -y dist-upgrade
#git clone <empire repo>
#cd Empire
#git checkout dev
#./steup/install.sh
#./empire
```

Note that the empire installation breaks dependencies on my Kali, and that no matter how many times I install empire, it downloads a installs the powershell .deb every time.

**Comment by xorrior** [comment]
@Ibrahimous Can you please provide the error output from the install?

**Comment by Ibrahimous** [comment]
Hi @xorrior, sorry for the late answer, hereafter the process for the issue on a Kali 4.14.0-kali3-amd64.
It is repeatable, and let me solve another problem with the powershell package a colleague ran into:

1. Make a first install:
`~/Empire# ./setup/install.sh`

Setup is successful, but when Empire is launched, I get:

```
(Empire) > set Obfuscate True
[!] PowerShell is not installed and is required to use obfuscation, please install it first.
```

2. On a second install:
`~/Empire# ./setup/install.sh`

Setup is successful, but Empire fails to launch:

```
Traceback (most recent call last):
  File "./empire", line 1383, in <module>
    main = empire.MainMenu(args=args)
  File "/root/Empire/lib/common/empire.py", line 84, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable
```

During both installs, I got:
dpkg: error: cannot access archive 'libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb': No such file or directory
dpkg: error: cannot access archive 'powershell_6.0.0-rc.2-1.ubuntu.16.04_amd64.deb': No such file or directory

3. I removed the entire Empire directory, re-git cloned it, then:

```
~/Empire# git checkout dev
~/Empire# ./setup/install.sh
[...]
Saving in : « libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb »
libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb       100%[===========================================================================================>]   1022K  1,71MB/s    ds 0,6s 
[...]
The following packages will be installed:
  icu-devtools libicu-dev swig3.0
Suggested packages:
  icu-doc pkg-config swig-doc swig-examples swig3.0-examples swig3.0-doc
The NEW packages will be instaleld:
  icu-devtools libicu-dev libssl1.0-dev libxml2-dev swig swig3.0 zlib1g-dev
[...]
powershell_6.0.0-1.ubuntu.16.04_amd64.deb   100%[===========================================================================================>]  49,52M  7,37MB/s    ds 8,5s    
2018-03-07 11:47:48 (5,81 MB/s) — « powershell_6.0.0-1.ubuntu.16.04_amd64.deb » sauvegardé [51924664/51924664]
```

4. Empire dev fails then to launch:

```
~/Empire# ./empire 
Traceback (most recent call last):
  File "./empire", line 1418, in <module>
    main = empire.MainMenu(args=args)
  File "/root/Empire/lib/common/empire.py", line 87, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
  File "/root/Empire/lib/common/helpers.py", line 554, in get_config
    cur.execute("ALTER TABLE config ADD COLUMN %s BLOB" % (field))
sqlite3.OperationalError: no such table: config
```

5. I then removed the entire Empire directory, re-git cloned it, then:
```
~/Empire# ./setup/install.sh
~/Empire# ./empire 

(Empire) > set Obfuscate True
[*] Obfuscating all future powershell commands run on all agents.
```

**Comment by DakotaNelson** [comment]
I'm like 85% sure the `sqlite3.OperationalError` and `TypeError: 'NoneType' object is not iterable` problems are both solvable by running `./setup/reset.sh` to clean out the database. Not sure if that would actually prevent you having to do some of the later reinstalls, though.

**Comment by timothyleung1** [comment]
I got the same problem, I checked my db and the config table is empty.. Not sure why will that happen, but I started to get this error after running scan_port module.

**Comment by timothyleung1** [comment]
I have to reset the db at the end and lost the implants , make sure you generate session key without using randomised key.
