### ISSUE TITLE
How to fix this ERROR?

### ISSUE THREAD

**Issue by Deathlive** [EmpireProject/Empire#719]
## Empire Version
2.1

## OS Information (Linux flavor, Python version)
Android 5.1 , Termux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
In start written this error.
I install all requirements, but pyinstaller not install.

## Screenshot of error, embedded text output, or Pastebin link to the error
https://prnt.sc/gpbana

## Any additional information
How to fix this?

**Comment by utkusen** [comment]
@Deathlive are you root on the device?

**Comment by rvrsh3ll** [comment]
Not supported on android.
