### ISSUE TITLE
Empire Rest API can't work

### ISSUE THREAD

**Issue by ztencmcp** [EmpireProject/Empire#726]
## Empire Version
v2.1

## OS Information (Linux flavor, Python version)

Kali, python 2.7
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

When i create rest api for other applications then it jumps back to the banner screen.

**Comment by xorrior** [comment]
@ztencmcp please provide more detail. I highly suggest including a screenshot with a more thorough explanation.
