### ISSUE TITLE
data encoding in REST api

### ISSUE THREAD

**Issue by miked531** [EmpireProject/Empire#727]
## Empire Version
2.1

## OS Information (Linux flavor, Python version)
Ubuntu 16.04, python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

JSON input through the REST api is being stored as unicode data. when the unicode string is added to a normal string the result is a unicode string (at least with python 2.7). for an example create a listener through the REST api (POST /api/listeners/http) and set the Host option. 

the error manifests itself when trying to communicate with a stager (I was using osx/launcher)

**Comment by xorrior** [comment]
@miked531 can you provide more detail on this. Please post python stack trace if there is any. Also run empire with the debug 2 option and post that output as well.

**Comment by checkyfuntime** [comment]
![image](https://user-images.githubusercontent.com/26147220/31757700-0b12b206-b478-11e7-9f51-b46dbf3a4427.png)

I believe he's getting the same error that I was telling you about, here's a screenshot showing the response from the server when requesting agents that were created using osx/launcher.

**Comment by xorrior** [comment]
Fixed in #866
