### ISSUE TITLE
Unable to Download files with spaces

### ISSUE THREAD

**Issue by bkr32** [EmpireProject/Empire#729]
## Empire Version
2.1

## OS Information (Linux flavor, Python version)
kali 2017.2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
file name: "this is  a test file"
command: download this is a test file
result: downloaded "this"

## Any additional information
i've been unsuccessful downloading files which have spaces with them as above, however downloading files with no spaces works perfectly

**Comment by djhohnstein** [comment]
Try adding quotes around your file path, such as:

`download "this is a test file"`

**Comment by xorrior** [comment]
Quotes won't work, there is some flawed logic in the agent. It'll be updated today in the dev branch

**Comment by bkr32** [comment]
thanks for the update @xorrior its a real pain switching to meterpreter that sometimes works just to nab a file

**Comment by xorrior** [comment]
Fixed in 76c7d1b

**Comment by bkr32** [comment]
`"C:\Users\pie\Desktop\file with spaces`"
just keeping it as a reference @xorrior hope thats how it works

**Comment by xorrior** [comment]
@bkr32 Yup you got it!

**Comment by SuperXiaoxiong** [comment]
I met the same situation ，I try to  download a chrome login database ，and I have the administrator privilege，And the file exits， But can't download the "login data" file 
(Empire: H9NSLZKV) > download "C:\Users\Administrator\appdata\local\google\chrome\user data\default\login data"
[*] Tasked H9NSLZKV to run TASK_DOWNLOAD
[*] Agent H9NSLZKV tasked with task ID 90
(Empire: H9NSLZKV) > [!] Received error response from H9NSLZKV
[*] Agent H9NSLZKV returned results.
[!] File does not exist or cannot be accessed
[*] Valid results returned by 211.86.158.74
