### ISSUE TITLE
problem multi/launcher to bat

### ISSUE THREAD

**Issue by gearcapitan** [EmpireProject/Empire#732]
## Empire Version
last
## OS Information (Linux flavor, Python version)

kali 2017.2
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
if I copy and paste the command directly into the terminal, empire works, but if I want to copy it in an arhivo bat this is not executed and I tried to understand the code because I was accommodating so the powershell process is executed but only by an instant and is closed, however if I copy one by one each line of code in the terminal this if it connects
![captura de pantalla 66](https://user-images.githubusercontent.com/13740942/31050135-a52d5be0-a607-11e7-927d-b69a2f920112.png)

## Screenshot of error, embedded text output, or Pastebin link to the error
also the windows / launcher bat if this is obfuscated, does not connect!

**Comment by xorrior** [comment]
@gearcapitan please see #682
