### ISSUE TITLE
empire 3.0 errors

### ISSUE THREAD

**Issue by icekuku12** [EmpireProject/Empire#736]
## Empire Version
3.0

## OS Information (Linux flavor, Python version)

kali 2017 
4.12.0-kali2-amd64
python 2.7 , python3.5
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

root@kali:~/tools/Empire-3.0# ./empire 
  File "./empire", line 1330
    thread = helpers.KThread(target=thread_api, args(main,))
SyntaxError: non-keyword arg after keyword arg

## Screenshot of error, embedded text output, or Pastebin link to the error
root@kali:~/tools/Empire-3.0# ./empire 
  File "./empire", line 1330
    thread = helpers.KThread(target=thread_api, args(main,))
SyntaxError: non-keyword arg after keyword arg

## Any additional information
help.

**Comment by xorrior** [comment]
3.0 is still in development. You should always remain on the master branch.

**Comment by icekuku12** [comment]
Okay thx ^^  
-----Original Message-----
