### ISSUE TITLE
ERROR in app: Exception on /admin/get.php [POST] Traceback (most recent call last)

### ISSUE THREAD

**Issue by info9jf** [EmpireProject/Empire#755]
## Empire Version
[Version] 2.2 

## OS Information (Linux flavor, Python version)
kali linux 2017.2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

in http_com if agents active i have error :: 
[2017-10-14 01:01:46,365] ERROR in app: Exception on /admin/get.php [POST]

## Screenshot of error, embedded text output, or Pastebin link to the error

https://pastebin.com/raw/GMBpUau7

**Comment by jihadLkmaty218** [comment]
use rest.sh ! ::)  this problem on Empire Not of Module Or Stager !! this problem  in Products Empire/man

**Comment by xorrior** [comment]
Fixed in 32990df
