### ISSUE TITLE
all the syntax change .. can use anymore usestager and other 

### ISSUE THREAD

**Issue by mateo24xx** [EmpireProject/Empire#760]
## all the syntax change .. can use anymore usestager and other 

is there a new syntax to use in Empire version 2.2 ?
![error](https://user-images.githubusercontent.com/24534204/31681835-a72f9312-b378-11e7-9c03-2706aff76bce.PNG)

**Comment by mateo24xx** [comment]
to much problems in version 2.2 !!!! nothing work
when you put a command it gives always error message ..really dont now how people work with this version???

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Use [tab]
Please see #573 and all others issues related.
