### ISSUE TITLE
update question

### ISSUE THREAD

**Issue by PandoraSec** [EmpireProject/Empire#761]
## Empire Version
2.1

## OS Information (Linux flavor, Python version)
kali linux, python  2.7.13

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
how canh i update the empire without have to erase the past empire? its cuz when i do this i loose my listeners and all payloads that i done, how i use dns i have to change it constantly, there is a way to update without loose my information?
thanks

**Comment by xorrior** [comment]
@PandoraSec I would highly recommend NOT upgrading during an op. The database structure may or may not change. Hence you would have to reset the database and start fresh. The best suggestion would be to setup a new Empire server with the latest version. Setup a foreign listener and pass agents to the new server.
