### ISSUE TITLE
REST API for manually adding creds

### ISSUE THREAD

**Issue by mortymorty** [EmpireProject/Empire#764]
## Empire Version
version 2.1 (latest)

#39 references this but in API docs there is only option to view all creds (https://github.com/EmpireProject/Empire/wiki/RESTful-API#credentials)

**Comment by DakotaNelson** [comment]
I'll take a stab at this; expect a PR over the weekend.

**Comment by xorrior** [comment]
Done. Credit to @DakotaNelson
