### ISSUE TITLE
Necessary lines commented out in PyInstaller module?

### ISSUE THREAD

**Issue by wizzletuq** [EmpireProject/Empire#774]
## Empire Version
2.2 (and current dev branch)

## OS Information (Linux flavor, Python version)
Xubuntu 17.10, Python 3.6

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When trying to create a stager using the pyInstaller module, an error is given about installPath_Str not being defined.

## Screenshot of error, embedded text output, or Pastebin link to the error
This error is given immediately after running "execute" when creating the pyInstaller stager module:
[!] Exception: global name 'installPath_Str' is not defined

## Any additional information
The installPath_Str object is required for the pyInstaller script to run, but it seems like the two lines that retrieve it from the config table of the database have been commented out. This results in an error when attempting to generate a stager using the pyInstaller module.

Lines 115 and 116 in this commit: https://github.com/EmpireProject/Empire/commit/d0b2ba41b42e6139b223183e806ee2bbac465c9e

**Comment by xorrior** [comment]
Fixed in the dev branch. https://github.com/EmpireProject/Empire/commit/9093b3df9e04dbdc15de5cc28e3efb0cdaedda1e
