### ISSUE TITLE
No handlers could be found for logger "werkzeug"

### ISSUE THREAD

**Issue by mateo24xx** [EmpireProject/Empire#779]
##
![abababababab](https://user-images.githubusercontent.com/24534204/32033853-67f98f7a-ba0f-11e7-92aa-b1f6ecf62458.PNG)

**Comment by xorrior** [comment]
@mateo24xx This isn't an exception or error necessarily. Did this cause an issue for you in a module or when interacting with an agent.

**Comment by mateo24xx** [comment]
no it works normaly..but i dont now if this problem persist it will always work good..

**Comment by xorrior** [comment]
The output is from the logger module. It doesn't cause any exceptions or errors and I've only seen output like that once or twice. Kind of a outlier ¯\_(ツ)_/¯
