### ISSUE TITLE
what syntax can we use now because nothing work??

### ISSUE THREAD

**Issue by mateo24xx** [EmpireProject/Empire#780]
## i think this picture tell whats wrong !!
![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/24534204/32034918-f731c22e-ba15-11e7-816e-178062648487.PNG)

##

## IS THERE SOMEBODY WHO PLEASE CAN GIVE US THE FULL SYNTAX TO USE 
I SEARCH ALL THE INTERNET AND FIND NOTHING??THANK YOU

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
`set [tab] [tab]`

set listerner => set **L**istener(with capital L)
option => info

I think you have not 'search all the internet'....

**Comment by mateo24xx** [comment]
Thank you for your reply..i find this already here on github ..
but what i mean is that i can  find anything on internet about the hole syntax to use ,not only for Listener or usestage,but for everything to do on Empire.
if you now where i can find it ?? it will be very helpfull ..

**Comment by xorrior** [comment]
http://www.harmj0y.net/blog/empire/the-empire-strikes-back/
