### ISSUE TITLE
Listener authentication

### ISSUE THREAD

**Issue by qbiguenet** [EmpireProject/Empire#783]
Hi,

I would like to know if there is any trick/feature such as authentication mechanisme to protect my listeners from bad guys ? :-)

Thanks.

**Comment by xorrior** [comment]
@qbiguenet nothing natively built into Empire.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Is the staging key a kind of *authentication* ?  Because it prevents bad guys to forge agents. @qbiguenet what is your attack scenario by bad guys ?

**Comment by qbiguenet** [comment]
I jute would like to know if anybody could interract with my empire listeners without any authentication.
It could be great to implement something to allow only our agents to contact our listeners.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
> It could be great to implement something to allow only our agents to contact our listeners.

For me, this is done by the staging key. An attacker cannot interact with your listener without the correct staging key (maybe I'm wrong)
