### ISSUE TITLE
 Handle bind connection tru socat ?

### ISSUE THREAD

**Issue by nem0n** [EmpireProject/Empire#785]
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
  Hi there I think I describe little bit wrong in my older issue request. because what I am trying to do create a payload with using empire and setting the payload IP address to 127.0.0.1 and when the user opens it, I will create bind connection  with user, and I will use socat for redirecting connection but, what I am wondering is that, Is empire capable to do that?, 
         I am able to do that with Metasploit but in empire when trying to create listener it can be HTTP or any other it's starting to use port which is specified but also I am using same for socat too and because of that  socat is failing to set the port with same port but in Metasploit, It just attempting to connect instead of creating listener with payload bind_tcp, if empire not capable to do that how can i share Metasploit session to empire still over socat
      I hope I explained my situation well and sorry if it is a dumb question just trying to figure out find a way to do that. Thank you

**Comment by xorrior** [comment]
@nem0n Listeners can either bind to 0.0.0.0 for any interface/ip address or a specific IP address. Using the loopback address is not possible.
