### ISSUE TITLE
Key not found error

### ISSUE THREAD

**Issue by puniaze** [EmpireProject/Empire#786]
## Empire Version
2.2

## OS Information (Linux flavor, Python version)
Kali linux 2016.2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Dropbox payload not working as expected. It throws error when agent connects back.

## Screenshot of error, embedded text output, or Pastebin link to the error

(Empire) > Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/Desktop/Empire/lib/common/helpers.py", line 874, in __run
    self.__run_backup()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Desktop/Empire//lib/listeners/dbx.py", line 891, in start_server
    dataResults = self.mainMenu.agents.handle_agent_data(stagingKey, stageData, listenerOptions)
  File "/root/Desktop/Empire/lib/common/agents.py", line 1376, in handle_agent_data
    dataToReturn.append((language, self.handle_agent_staging(sessionID, language, meta, additional, encData, stagingKey, listenerOptions, clientIP)))
  File "/root/Desktop/Empire/lib/common/agents.py", line 1274, in handle_agent_staging
    sessionKey = self.agents[sessionID]['sessionKey']
KeyError: '1WKET7MC'

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Have you tried [this workaround](https://github.com/EmpireProject/Empire/issues/563#issuecomment-336529523)? I'm not sure if it's the same issue

**Comment by puniaze** [comment]
Actually I have found solution by removing everything inside dropbox application folder. Probably, developers forgot to add functionality to remove junk files in DBX app folder when victim exits or connection is lost. Resetting listener + deleting everything inside dropbox solved problem .

**Comment by xorrior** [comment]
@puniaze please see https://github.com/EmpireProject/Empire/issues/587
