### ISSUE TITLE
about obfuscation feature

### ISSUE THREAD

**Issue by backtoback1** [EmpireProject/Empire#791]
## Empire Version

2.3

## OS Information (Linux flavor, Python version)

kali linux 2017.2 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

there is no payload process on process manager 

## Any additional information
Hi 

i use the obfuscation feature of empire to obfuscate the launcher_bat 
i set Obfuscate true 
and set ObfuscateCommand launcher
then generate the stager 
but when i tried it i'm not receive a agent 

did i make mistake ?

target system windows 8 32bit 

powershell version 4

**Comment by backtoback1** [comment]
Hi now it's working i change the format to ps1 
but how can set the process noexit 
because when i close the powershell window i lose the agent

**Comment by xorrior** [comment]
@backtoback1 try to incorporate the windowstyle hidden option with your ObfuscateCommand.
