### ISSUE TITLE
API Get Agent Results returns nothing

### ISSUE THREAD

**Issue by Icon0clast** [EmpireProject/Empire#795]
## Empire Version
Empire Version 2.3

## OS Information (Linux flavor, Python version)
Ubuntu 16.04 Python 2.7.12

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I'm currently working on a python script to do simple host recon using the API, mainly for scripting practice.  I've been able to get the agent going, send a command to the agent and see it working in the console, even returning results in the console but when I poll the agent for results using the API it returns nothing.

At first I wasn't sure if I was doing it wrong but I found the same error in DeathStar when I tested that since it does the same operations I'm trying to.

I have also tested via the API documentation using curl and have the steps below to reproduce.

curl --insecure -i -H "Content-Type: application/json" https://localhost:1337/api/modules/powershell/situational_awareness/network/powerview/get_loggedon?token=peczinsv3mys2hgg6i5bekqfemn0hxzzyzd32yso -X POST -d '{"Agent":"test7"}'

curl --insecure -i -H "Content-Type: application/json" https://localhost:1337/api/agents/test7/results?token=peczinsv3mys2hgg6i5bekqfemn0hxzzyzd32yso

## Screenshot of error, embedded text output, or Pastebin link to the error

HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 148
Server: Werkzeug/0.12.2 Python/2.7.12
Date: Thu, 02 Nov 2017 14:29:33 GMT

{
  "msg": "tasked agent test7 to run module powershell/situational_awareness/network/powerview/get_loggedon",
  "success": true,
  "taskID": 2
}

HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 110
Server: Werkzeug/0.12.2 Python/2.7.12
Date: Thu, 02 Nov 2017 14:29:48 GMT

{
  "results": [
    {
      "AgentName": "6GYCRT1V",
      "AgentResults": [
        ""
      ]
    }
  ]
}

## Any additional information
I might be doing it wrong.. still new to Empire.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Have you try to `git pull` ? Because https://github.com/EmpireProject/Empire/commit/6a90084df8ad7d8f55dce5ed3c15cc3bc3013377 fixes a similar issue (#794)

**Comment by Icon0clast** [comment]
I have tried doing a full wipe and reinstall, sorry I should have mentioned that.  I was having the same issue as #794 which a pull did fix but this issue still remains.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
No problem :smile: Have you try to run empire with `--debug 2` ?

**Comment by Icon0clast** [comment]
I haven’t but I’ll try it in the morning and let you know the results

**Comment by Icon0clast** [comment]
Alright, I've performed the same steps and in the Debug I'm not seeing the GET request being processed by the agent, just the standard pinging occurring.

In the mean time I'm going to stand up a different host and see if I get different results.  I did notice in the DeathStar issues tracker (https://github.com/byt3bl33d3r/DeathStar/issues/37) that someone is having the same issue related to getting the TaskID from the results request which is the same error I'm having since the results request is not returning anything in the JSON.

**Comment by Icon0clast** [comment]
Well, I started up a new instance of Kali on AWS, git cloned empire, set everything back up and got results.


root@ip-172-31-4-139:~# curl --insecure -i -H "Content-Type: application/json" https://172.31.13.46:1337/api/agents/YH6P3NV1/results?token=el83ojdggs0j4nzml72x0m1a35e8j6kt8scdctbf
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 559
Server: Werkzeug/0.12.2-dev Python/2.7.13
Date: Fri, 03 Nov 2017 13:58:22 GMT

{
  "results": [
    {
      "AgentName": "YH6P3NV1",
      "AgentResults": [
        "[\"Job started: 27C9L5\", \"\\r\\nwkui1_username wkui1_logon_domain wkui1_oth_domains wkui1_logon_server ComputerName\\r\\n-------------- ------------------ ----------------- ------------------ ------------\\r\\nAdministrator  TEST-CORP                            DC01               localhost   \\r\\nWS01$          TEST-CORP                                               localhost   \\r\\n\\r\\n\\r\\n\\n\\r\\n\\nGet-NetLoggedon completed!\\r\\n\"]"
      ]
    }
  ]
}

Interesting...

**Comment by xorrior** [comment]
@Icon0clast So I will say once you have received results and viewed them in the console, they are removed from the DB and will not be shown when you use the API to fetch them. This may not be the case but its possible, depending on the order of execution in your testing.
