### ISSUE TITLE
ChromeDump Module

### ISSUE THREAD

**Issue by robertbhalla71** [EmpireProject/Empire#797]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Debian
python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

While taking the chromedump, one column is removed because it doesn't fit the display. while writing it out in a file, it doesn't work

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Have you tried this PR #734 ?

**Comment by xorrior** [comment]
@robertbhalla71 when writing out to a file, what specifically doesn't work? Are there errors? Is the file not created?

**Comment by OneDollarr** [comment]
don't work..

**Comment by OneDollarr** [comment]
Do not create out file with passwords

**Comment by robertbhalla71** [comment]
I found the problem was not with the OutFile. Even when i got to create a file with chromedump, the PWD column is empty as the module is not able to extract passwords out of it. Has anyone got any results with this module?

Also the module Invoke-FoxDump doesn't show anything even when you have admin high-integrity. any suggestions?

**Comment by robertbhalla71** [comment]
@xorrior There was a momentary error. tried the next day and the file got created. Thanks for help @ThePirateWhoSmellsOfSunflowers

**Comment by OneDollarr** [comment]
I'm sorry, I did not understand what I need to do to get passwords? I still do not create a document (

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
@OneDollarr The data files are locked while Chrome is running, you need to kill Chrome before using this module

**Comment by OneDollarr** [comment]
No!on the attacked machine 2 passwords are saved, the browser is chrome closed! An hour has passed, the process is started, but no file with passwords is created and nothing happens at all. I have the latest version of empire
I have a system privileges. 

![11](https://user-images.githubusercontent.com/32229776/32690307-c27aceb6-c705-11e7-89ad-1097c7ae7cee.png)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
You don't need SYSTEM because passwords are encrypted in the context of the current user. Try with without SYSTEM

**Comment by OneDollarr** [comment]
It does not work .. Am I the right way to point? For example, I want to save to my home directory. /root/amazon.tht I should have a document amazon.tht in the catalog. I tried with the rights of a normal user, it does not work. The browser is closed. The service starts and nothing happens. I waiting 10 min and nothing happend ( Maybe I need to replace the powershell script with another one?

![3333](https://user-images.githubusercontent.com/32229776/32690758-e85552f8-c70c-11e7-8470-f69b76fa8e06.png)

**Comment by xorrior** [comment]
The save path is referring to a directory on the comprised host, not locally..
