### ISSUE TITLE
launcher_bat Obfuscate Error

### ISSUE THREAD

**Issue by carms642** [EmpireProject/Empire#800]
## Empire Version
2.3
In the most current version
## OS Information (Linux flavor, Python version)
Kali 4.12.0 Python 2.7.14 
Obfuscate does not work when I do it.
![bbbb](https://user-images.githubusercontent.com/11415252/32432335-471a86a6-c2e8-11e7-895b-80556e320e82.png)

**Comment by xorrior** [comment]
hmmmmmmmmmmmmm. Is PowerShell installed?????????????????????

**Comment by carms642** [comment]
If not, how do I get an agent connection.Obfuscate module is not working.Do you work without problems Empire?

**Comment by xorrior** [comment]
You can't use any of the obfuscate commands without PowerShell. Since, you know, Invoke-Obfuscation is a powershell script.....
