### ISSUE TITLE
mimikatz 2.1.1

### ISSUE THREAD

**Issue by tecxx** [EmpireProject/Empire#801]
## Empire Version
[Version] 2.3 | [Web] https://github.com/empireProject/Empire

## OS Information (Linux flavor, Python version)
kali, latest updates

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

using mimikatz in empire prints version info
mimikatz 2.1 (x64) built on Dec 11 2016 18:05:17

when downloading the latest mimikatz native binary and starting it, it prints version info
mimikatz 2.1.1 (x64) built on Aug 13 2017 17:27:53

## Any additional information
on my windows 10 lab target mimikatz fails with ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list when running through empire (yes with system rights).
running through the native binary i get no error. i am therefore assuming the newer version of mimikatz is required. 

my assumption may be incorrect, but can the version in empire get an update nonetheless?

**Comment by xorrior** [comment]
@tecxx We are working on getting mimikatz updated. Thanks.

**Comment by xorrior** [comment]
@tecxx mimikatz has been updated.
