### ISSUE TITLE
Issues running mimikatz dcsync module

### ISSUE THREAD

**Issue by REPTILEHAUS** [EmpireProject/Empire#805]
## Empire Version
v2.3

## OS Information (Linux flavor, Python version)
kali latest rolling release - supplied by Offensive Security for PWK/OSCP

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Success running powershell/credentials/mimikatz/dcsync or a more helpful error

## Screenshot of error, embedded text output, or Pastebin link to the error
```
(Empire: powershell/credentials/mimikatz/dcsync) > 
Job started: LWTGS2

Hostname: master.thinc.local / authority\system-authority\system

  .#####.   mimikatz 2.1 (x64) built on Dec 11 2016 18:05:17
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 20 modules * * */

mimikatz(powershell) # lsadump::dcsync /user:master.thinc.local\Administrator /domain:master.thinc.local /dc:master.thinc.local
[DC] 'master.thinc.local' will be the domain
[DC] 'master.thinc.local' will be the DC server
[DC] 'master.thinc.local\Administrator' will be the user account
ERROR kull_m_rpc_drsr_getDomainAndUserInfos ; DomainControllerInfo: 0x0000208d (8333)
ERROR kull_m_rpc_drsr_CrackName ; CrackNames (name status): 0x00000002 (2) - ERROR_NOT_FOUND

```

PS: also in an unrelated issue, Im trying to run DeathStar and it appears the latest version of Empire is not compatable with it

**Comment by DakotaNelson** [comment]
Do you know if this is addressed in #801?

**Comment by xorrior** [comment]
@REPTILEHAUS Can you reproduce this issue with the mimikatz binary and the same command? Errors in your mimikatz output does not indicate issues with Empire. Believe it or not, mimikatz is not  always %100 successful :)

**Comment by xorrior** [comment]
@REPTILEHAUS Mimikatz has been updated to the latest version. Please re-test and feel free to open this back up if the problem still exists.
