### ISSUE TITLE
HTTPS Listener fails

### ISSUE THREAD

**Issue by passwordleak** [EmpireProject/Empire#806]
## Empire Version
Latest

## OS Information (Linux flavor, Python version)
Kali 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
https listener CertPath does not work. I set the CertPath to be "/opt/Empire/data/empire-chain.pem" which I checked and does exist, but when I try to start a http listener, it results in the error:
[!] Listener startup on port 8443 failed: [Errno 20] Not a directory

When I try to execute without the CertPath, it will create the listener, but trying to access it results in the following error, and agents can't connect:
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

## Screenshot of error, embedded text output, or Pastebin link to the error

(Empire: listeners/http) > execute
[*] Starting listener 'http1'
[!] Listener startup on port 8443 failed: [Errno 20] Not a directory
[!] Listener failed to start!
(Empire: listeners/http) >

**Comment by xorrior** [comment]
CertPath is a directory that contains both the pem and the private key.

**Comment by passwordleak** [comment]
Thanks! It works now. I wish it was more obvious or had a better error message however, as the previous Empire versions used a single .pem file.
