### ISSUE TITLE
what syntax ,command to use ??

### ISSUE THREAD

**Issue by mateo24xx** [EmpireProject/Empire#812]
## EMPIRE 2.3

##LINUX

## i now that this question already received answer but answer was not compleet ,thats why i ask again..
where can we find the commands or syntax to use in new Empire .;i already look in the empire stryke back and find nothing..
![asasasas](https://user-images.githubusercontent.com/24534204/32682979-220ca536-c678-11e7-8888-c7ba2961ffdb.PNG)

**Comment by xorrior** [comment]
You're missing the listener option....

**Comment by mateo24xx** [comment]
thank you
