### ISSUE TITLE
Invoke-Powerdump failing on Windows 10

### ISSUE THREAD

**Issue by Vokaysh** [EmpireProject/Empire#816]
## Empire Version
Latest

## OS Information (Linux flavor, Python version)
Windows 10

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Expecting to get user password hashes, instead getting empty password NTLM hashes (31D6CFE0D16AE931B73C59D7E0C089C0)

## Any additional information
It seems there was a change in the way the encryption used for the LSA key in Windows 10 (AES instead of RC4), here's a metasploit commit that seems to not have been ported:
https://github.com/thelightcosine/metasploit-framework/commit/27469f8fac4b9061cdaa58c6b4077956f8b8e1dd

**Comment by xorrior** [comment]
@Vokaysh I anxiously await your PR that ports the changes made in metasploit. If not, we can address this in the future.
