### ISSUE TITLE
Can you teach me how to mass execute payload please ?

### ISSUE THREAD

**Issue by zondaime13** [EmpireProject/Empire#819]
Excuse me but can you help me to execute a payload when I get agent ? I got 2 agent in my Empire and I want to mass upload and execute file to all agent. Using interact and shell is slowly. Thank you!

**Comment by xorrior** [comment]
@zondaime13 Your best bet is to use the REST api and automate something to do that. I don't know if the effort is worth it in your specific circumstance.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
As a workaround , you can use `set Agent all` when you use a module

**Comment by zondaime13** [comment]
@ThePirateWhoSmellsOfSunflowers  @xorrior  thank you for the reply to my post!
