### ISSUE TITLE
Unicode Decode Error in "Get Current Agents" REST API Call

### ISSUE THREAD

**Issue by utkusen** [EmpireProject/Empire#821]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Tried under macOS and Kali Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I got two active agents on Empire. Information regarding to these agents are listed below:
https://i.imgur.com/G4YyOkJ.png
https://i.imgur.com/3tGGSSv.png

When I execute "Get Current Agents" API call, I got following error:

```
UnicodeDecodeError('utf8', 'n\x91I/g\x05J\xfc\xdd\x01\xf1\xee>A\\\xeb\xe0\xe1\xee\xb9\xf537}\xa7\xb2\xfaK\xd2\x05\xc0Y', 1, 2, 'inval
id start byte')
```
I believe the problem is related with second agent's session_key. There are some characters shown as "?". Also, when I remove this agent and make the api call again, it works without a problem.

**Comment by xorrior** [comment]
@utkusen thanks for pointing this out.

**Comment by utkusen** [comment]
@xorrior for your information I fixed this by changing `"session_key":session_key` to `"session_key":session_key.decode('latin-1').encode("utf-8")` on empire file line 743

**Comment by xorrior** [comment]
@utkusen would you mind submitting a PR for the fix you implemented?

**Comment by utkusen** [comment]
@xorrior done

**Comment by xorrior** [comment]
@utkusen thanks!
