### ISSUE TITLE
"Get Agent Results" REST API Call Should Return "taskID" Variable

### ISSUE THREAD

**Issue by utkusen** [EmpireProject/Empire#822]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Both Kali Linux, macOS

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Let's say you triggered `whoami` command with "Task an Agent to run a Shell Command" API Call for 4 times on an agent. It produces an output like that for the last one:

`{  "success": true,  "taskID": 4}`

So "Get Agent Results" API Call will return something like that:

```
{
  "results": [
    {
      "AgentName": "AL8ZGMW7",
      "AgentResults": [
        "Utku", "Utku", "Utku", "Utku"
      ]
    }
  ]
}
```
When you trigger "Delete Agent Results" API Call, it deletes Agent Results but not taskID value. So if you trigger the "Task an Agent to run a Shell Command" again, response will be:

`{  "success": true,  "taskID": 5}`

When you trigger the "Get Agent Results" again, response will be:

```
{
  "results": [
    {
      "AgentName": "AL8ZGMW7",
      "AgentResults": [
        "Utku"
      ]
    }
  ]
}
```
So `taskID:5` is equal to `AgentResult[0]` When you trigger another `taskID:6` will equal to `AgentResult[1]`. Eventually, you will lose the track of which result belongs to which `taskID`

My suggestion is: "Get Agent Results" should include `taskID` as well so we can keep track which result belongs to which `taskID`

**Comment by crossmxn** [comment]
Any updates?

**Comment by utkusen** [comment]
no updates but I reverted the commit that removes taskid. I'm using it in that way for myself

**Comment by crossmxn** [comment]
Do you have a link to the commit? Thankss
