### ISSUE TITLE
when used * instead of non ascii characters, it misbehaves

### ISSUE THREAD

**Issue by robertbhalla71** [EmpireProject/Empire#824]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
non-ascii characters support is not there. when used *, it says the command is executed but it actually does nothing

## Any additional information
tried on download command

**Comment by xorrior** [comment]
@robertbhalla71 Can you elaborate on where the asterisk is used. Is that in a file path? Please post output from empire with --debug 2. Also, we are now on version 2.3 ..........

**Comment by robertbhalla71** [comment]
As empire is not catering for utf-16, i tried using * in place of those characters. It said the file is downloaded, but no file was downloaded. Never the less i used a workaround for that problem. but it would be cool if empire is able to support utf-16

**Comment by xorrior** [comment]
Unfortunately, that's not something we're going to support right now
