### ISSUE TITLE
Question: Using download/upload functionality on agents with Rest API

### ISSUE THREAD

**Issue by utkusen** [EmpireProject/Empire#828]
Running modules or shell commands are well documented in here: https://github.com/EmpireProject/Empire/wiki/RESTful-API

However, I couldn't find any references on how to use built-in agent functions like download and upload. Is there a way to do it with REST API directly?

**Comment by xorrior** [comment]
@utkusen Sorry for the delayed response. Currently there is only functionality to upload files to an agent but not download. Thanks

**Comment by utkusen** [comment]
@xorrior thanks for the info, but I couldn't find upload file section on API documentation. Could you please describe the required API call?

**Comment by xorrior** [comment]
@utkusen Sure: https://github.com/EmpireProject/Empire/blob/master/empire#L886

**Comment by utkusen** [comment]
@xorrior thank you! You should consider to add it to API documentation
