### ISSUE TITLE
setup_database.py fails to auto-calculate the correct INSTALL_PATH under some circonstances

### ISSUE THREAD

**Issue by uaksag** [EmpireProject/Empire#833]
## Empire Version
Master branch

## OS Information (Linux flavor, Python version)
Kali

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When Empire is cloned in a directory not named "Empire", but whose path contain "Empire" ("/root/Empire/git" for example), setup_database.py thinks INSTALL_PATH is "/root/Empire/" instead of "/root/Empire/git/". So, no modules are loaded.

## Screenshot of error, embedded text output, or Pastebin link to the error
```
root@kali:~# mkdir Empire
root@kali:~# cd Empire
root@kali:~/Empire/# git clone https://github.com/PowerShellEmpire/Empire git
[…]
root@kali:~/Empire/# cd git
root@kali:~/Empire/git/# ./setup/install.sh
[…]
root@kali:~/Empire/git/# sqlite3 data/empire.db 'select install_path from config;'
/root/Empire/
root@kali:~/Empire/git/# ./empire
[*] Loading stagers from: /root/Empire//lib/stagers/
[*] Loading modules from: /root/Empire//lib/modules/
[*] Loading listeners from: /root/Empire//lib/listeners/
[…]
0 modules currently loaded
[…]
```

## Any additional information
Workaround: manually set the correct install_path in the database:
```
root@kali:~/Empire/git/# sqlite3 data/empire.db 'update config set install_path = "/root/Empire/git/";'
root@kali:~/Empire/git/# ./empire
[*] Loading stagers from: /root/Empire/git//lib/stagers/
[*] Loading modules from: /root/Empire/git//lib/modules/
[*] Loading listeners from: /root/Empire/git//lib/listeners/
[…]
280 modules currently loaded
[…]
```

**Comment by xorrior** [comment]
@uaksag fixed in the dev branch. Sorry for the wait.
