### ISSUE TITLE
XAR fails to install on Kali

### ISSUE THREAD

**Issue by varnerac** [EmpireProject/Empire#834]
## Empire Version

`master`

## OS Information (Linux flavor, Python version)

```
root@kali:~/Empire# uname -a
Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux
```

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

```STAGING_KEY=dummy ./setup/install.sh```

## Screenshot of error, embedded text output, or Pastebin link to the error

```
checking openssl/evp.h presence... yes
checking for openssl/evp.h... yes
checking for OpenSSL_add_all_ciphers in -lcrypto... no
configure: error: Cannot build without libcrypto (OpenSSL)
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

## Any additional information

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
`apt install libssl-dev` ?

**Comment by varnerac** [comment]
I don’t think so. It finds other OpenSSL headers. I think the function was deprecated. May require an API compatibility flag at compile time to enable it.

**Comment by xorrior** [comment]
@varnerac see #720
