### ISSUE TITLE
Agent checkin error - Constantly signaling restaging

### ISSUE THREAD

**Issue by V1V1** [EmpireProject/Empire#837]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Debian 9, Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When using a HTTP listener, some agents that I've set persistence on have issues checking in.
They'll constantly signal restaging (see screenshot below) and eventually stop trying after some attempts.
I don't believe it's my listener configuration since it doesn't happen with every single agent on the assigned listener.

## Screenshot of error, embedded text output, or Pastebin link to the error
![empire_restaging_issue](https://user-images.githubusercontent.com/17599553/33254345-5e21c18a-d359-11e7-836c-043ec4d3ab99.png)

## Any additional information
I've noted that it happens with various persistence methods i.e. schtasks & wmi

**Comment by xorrior** [comment]
@V1V1 can you reproduce this and post the output given from running empire with the --debug 2 flag? I've address this problem in the latest release. You can force the issue by removing an agent from the database after it has checked in.

**Comment by V1V1** [comment]
Hey, @xorrior. I just reproduced it with debug output; it's still constantly restaging. The error I'm getting is:

Agents : [!] handle_agent_data(): sessionID ESZ8BCDU not present
listeners/http : [!] Error from agents.handle_agent_data() for URI_STRING from IP_ADDRESS: ERROR: sessionID ESZ8BCDU not in cache!

"ESZ8BCDU" is the agent I just removed.

**Comment by xorrior** [comment]
@V1V1 are you sure your using the latest version? I just tried to reproduce this on a Win10 host. 
![screenshot from 2017-11-30 00-09-27](https://user-images.githubusercontent.com/9156069/33420318-1a7f09a4-d57c-11e7-96ac-ff5e0daf9f96.png)

**Comment by V1V1** [comment]
Yeah. I'm using Empire 2.3. Below is a screenshot showing the behavior with a Win7 host.

![empire-restaging_issue2](https://user-images.githubusercontent.com/17599553/33476307-98d8aa78-d692-11e7-875f-d1337d27707e.png)


Thanks for the help. I'll close the issue, reinstall Empire and hope it doesn't happen again.
