### ISSUE TITLE
Autorun doesn't run until you interact with the agent

### ISSUE THREAD

**Issue by hampros2** [EmpireProject/Empire#838]
usemodule powershell/persistence/elevated/wmi
set Agent autorun
execute

After doing this I won't get the output that notifies me that persistence has been established until after I use the interact command. If this is the intended behaviour, is there any way to make a module autorun once you get a new connection?

**Comment by xorrior** [comment]
@hampros2 so for agent output this is intended. You will only receive output when interacting with the agent. For the execution of the module, it happens once a new agent is received.

**Comment by hampros2** [comment]
Oh I see. Is it possible to have multiple autoruns and what determines in what order they will be executed?

**Comment by dfirArch0n** [comment]
yes, use a resource file.  I followed this article www.blackhillsinfosec.com/empire-resource-files-auto-runs-docx/

**Comment by hampros2** [comment]
@dfirArch0n thanks
