### ISSUE TITLE
listener failed to start [Errno 98]

### ISSUE THREAD

**Issue by hellohaha2018** [EmpireProject/Empire#839]
## Empire Version
Master

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
listener failed to start
address already in use [Errno 98]

## Any additional information
how do i fix this

**Comment by xorrior** [comment]
No clue how to fix that without more information. Possibly another process occupying the port?

**Comment by zayedaljaberi** [comment]
to check the running ports in your box, type this command
let's take an example if the listener startup failed on port 80.

1- We list all services running on port 80 (IMG 1)
sudo lsof -t -i:80

<img width="601" alt="screen shot 2018-09-24 at 7 59 35 pm" src="https://user-images.githubusercontent.com/18141643/45963631-9e366f00-c034-11e8-9253-e0f72db1c7b0.png">

2- Then, we get the detail of the following process ID (IMG 2)
ps 13888

<img width="644" alt="screen shot 2018-09-24 at 7 59 57 pm" src="https://user-images.githubusercontent.com/18141643/45963749-eeadcc80-c034-11e8-9153-119ab768b3a2.png">

3- In my case, I was running Apache server on my box so I stopped it and execute the command again. (IMG 3)

<img width="709" alt="screen shot 2018-09-24 at 8 00 13 pm" src="https://user-images.githubusercontent.com/18141643/45963865-4a785580-c035-11e8-9318-dae6b2e1f47e.png">
