### ISSUE TITLE
Default Profile/Custom Profile setup ?

### ISSUE THREAD

**Issue by sadizane** [EmpireProject/Empire#840]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Ubuntu 16.04.3 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I'm trying to setup a custom profile however i can't no longer see the configuration setup in setup_database.py . Where do you set the profile  and how do you change the index.jsp, index.php, index.jsp ? 

Thanks,

**Comment by leoloobeek** [comment]
You shouldn't need to do anything to setup_database.py. When you are setting up your listener within Empire you can do the following to change those things:

```
listeners
uselistener http
set DefaultProfile url/one.php;urltwo.html;/content/url/three.jsp|Some User Agent|CustomHeader1:Value1|CustomHeader2:Value2
```

Above sets three custom pages, modifies the user agent to "Some User Agent", and adds on two Custom HTTP Request headers.

**Comment by sadizane** [comment]
Thanks for your help. 

Regards,
