### ISSUE TITLE
Anti-Virus causing Powerdump to show wrong hash

### ISSUE THREAD

**Issue by Maleus** [EmpireProject/Empire#846]
## Empire Version
current

## OS Information (Linux flavor, Python version)
Windows 7 testing against Mcafee Endpoint protection, Threat Protect

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When running PowerDump against a machine that has Mcafee Endpoint protection on it, the hash comes back incorrect. It looks like a legit hash, but the hash itself is wrong. I tested this against another machine that does not have Mcafee installed, and the hash comes back correct. 

Is there a setting to get around this functionality of the Mcafee defense?

**Comment by xorrior** [comment]
@Maleus We don't have information or capabilities to get around that. Sorry.
