### ISSUE TITLE
OSX keylogger is actually the webcam module

### ISSUE THREAD

**Issue by khast3x** [EmpireProject/Empire#852]
## Empire Version
Current

## OS Information (Linux flavor, Python version)
Kali

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

The file can be found [here](https://github.com/EmpireProject/Empire/blob/master/lib/modules/python/collection/osx/keylogger.py). It is named keylogger.  
```python
        # metadata info about the module, not modified during runtime
        self.info = {
            # name for the module that will appear in module menus
            'Name': 'Webcam',

```

**Comment by xorrior** [comment]
Thanks for pointing this out. We'll address it at some point.
