### ISSUE TITLE
Linux/OSX modules doesn't work with REST API

### ISSUE THREAD

**Issue by utkusen** [EmpireProject/Empire#859]
## Empire Version
Latest

## OS Information (Linux flavor, Python version)
Kali linux server, macOS high sierra host

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I could be able to execute native_screenshot_mss module via Empire's console without a problem. However, when I execute it via API like this:

`curl --insecure -i -H "Content-Type: application/json" https://localhost:1337/api/modules/python/collection/osx/native_screenshot_mss?token=aaftm0s.. -X POST -d '{"Agent":"J5.."}'`

I got following error:

```
HTTP/1.0 400 BAD REQUEST
Content-Type: application/json
Content-Length: 74
Server: Werkzeug/0.12.2-dev Python/2.7.14
Date: Mon, 11 Dec 2017 09:28:18 GMT

{
  "error": "exception: invalid literal for int() with base 10: '2.6'"
}

```

**Comment by utkusen** [comment]
It seems this error appears in all osx modules when you try to use them via REST API

**Comment by utkusen** [comment]
It seems this error appears in all linux modules also

**Comment by xorrior** [comment]
@utkusen Ah so the culprit was this https://github.com/EmpireProject/Empire/blob/master/empire#L431. For python, the language version is '2.6' as opposed to powershell the language version is just an int. Updated and fixed in the dev branch. Sorry for the wait.
