### ISSUE TITLE
AV detect :-(

### ISSUE THREAD

**Issue by SergANT85** [EmpireProject/Empire#860]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Debian 8; python 2.7.

########
Good day! I have a problem with AV, a few weeks ago on the powershell code worked very well. There are ideas to bypass AV?

Detect - NOD32 Avira Kasperskiy

http://www.nodistribute.com/result/bhaMkrKiJ6VguNxSd2Y3

**Comment by honeyfairy** [comment]
Have you tried setting Obfuscate to True

Example:
```

`(Empire) > usestager multi/launcher
(Empire: stager/multi/launcher) > set Obfuscate True`
```
