### ISSUE TITLE
can't run empire on blackarchlinux

### ISSUE THREAD

**Issue by sparta3407** [EmpireProject/Empire#862]
## Empire Version
2.3

**Comment by DakotaNelson** [comment]
@sparta3407 can you provide any details?

**Comment by sparta3407** [comment]
it seems it has  aproblem with M2crypto compiling it gives errors all time

**Comment by xorrior** [comment]
@sparta3407 we are only going to support debian, ubuntu, and kali in future versions.

**Comment by killswitch-GUI** [comment]
@sparta3407 I suggest you use docker on arch, docs are coming but jump over to dev branch for the updates
