### ISSUE TITLE
'module' object has no attribute 'rand'

### ISSUE THREAD

**Issue by bkr32** [EmpireProject/Empire#871]
## Empire Version
master branch git

## OS Information (Linux flavor, Python version)
kali

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
upon using ./empire, empire should open normally however after a update(update/upgrade/autoremove)
i get the following error
Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Desktop/123/Empire-master/lib/common/empire.py", line 31, in <module>
    import agents
  File "/root/Desktop/123/Empire-master/lib/common/agents.py", line 68, in <module>
    import encryption
  File "/root/Desktop/123/Empire-master/lib/common/encryption.py", line 62, in <module>
    random_function = OpenSSL.rand.bytes
AttributeError: 'module' object has no attribute 'rand'

**Comment by xorrior** [comment]
@bkr32 This has been changed in the dev branch. https://github.com/EmpireProject/Empire/blob/dev/lib/common/encryption.py#L63 . Version 2.4 will be out within a couple of weeks.

**Comment by bkr32** [comment]
```
Traceback (most recent call last):
  File "./empire", line 1381, in <module>
    main = empire.MainMenu(args=args)
  File "/root/Empire/lib/common/empire.py", line 79, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable
```

should i just switch to dev branch?
@xorrior

**Comment by DakotaNelson** [comment]
@bkr32 I believe that if you switch to the dev branch, this will be fixed. Alternately, you can wait a while (a few weeks, probably) and it will be fixed in the primary Empire release.
