### ISSUE TITLE
Are Empire modules available as .ps1 scripts?

### ISSUE THREAD

**Issue by honeyfairy** [EmpireProject/Empire#872]
As an example, I would like to execute a script (.ps1/.bat) that does the same action as the **userland/schtasks** persistence module would do when run successfully on an agent.

How would I do this?

**Comment by xorrior** [comment]
Running empire with the --debug flag will output the last module executed to a file (LastTask). This is essentially the powershell source for the module. You may need to modify it a bit to execute it as a standalone script.

**Comment by honeyfairy** [comment]
Yes this is what I am looking for, I'm sure. Except that I don't see the LastTask.ps1 being created. I looked for it in my Empire directory but it is not there.

```

root@edoll:~/Empire# ls
LICENSE    changelog    data       empire        lib
README.md  clickme.lnk  downloads  empire.debug  setup
```


My empire.debug log:
```

2017-12-21 14:04:59 Empire : [*] Empire starting up...
2017-12-21 14:21:28 Empire : [*] Set module powershell/persistence/userland/schtasks to be global script autorun.
2017-12-21 14:26:26 Empire : [*] Empire shutting down...

```

**Comment by xorrior** [comment]
@honeyfairy the file will only show up once the module has executed.

**Comment by honeyfairy** [comment]
Okay, I see it now. Thanks a million @xorrior

**Comment by xorrior** [comment]
No problem
