### ISSUE TITLE
Question about token manipulation and DLL injection.

### ISSUE THREAD

**Issue by CryptomaticSquirrel** [EmpireProject/Empire#873]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Host: Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux
Target machine: Windows 8.1 with patches up to 2014 November.

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Token manipulation with PowerShell doesn't work. No error seen.

DLL stager. With Invoke-DllInjection.ps1 the dll seems to be loaded but doesn't execute or connect back.

## Any additional information

I think the main problem is token manipulation. I don't seem to get any error but it just doesn't take the new stolen rights.
This I assume breaks use of PTH, golden ticket and probably more.

Is this normal or should a PowerShell agent be able to adopt new rights? I read about it being related to PowerShell threads taking initial login rights instead of new token rights. But just not sure.

To solve this. I assume I could use the DLL stager. Which is where the second problem comes.
I have used different injection modules to get an agent from the DLL stager by injecting the DLL into another process. But even if a process loads the DLL it doesn't seem to work or at least the agent doesn't connect back.

Any advice what would be welcome !
If PowerShell should work on its own. How to get the DLL to work or what to use instead of PowerShell and DLL to get token manipulation to work.

Only criteria is remaining on Empire framework.

Thanks!

**Comment by xorrior** [comment]
@CryptomaticSquirrel Re: the DLL stager. That dll is used with Invoke-ReflectivePEInjection for the psinject module. As of several weeks ago, both the dll and module function normally. I have not used the dll stager with Invoke-DllInjection and it was not developed for use with that script. I don't know if Invoke-Dllinjection provides the option for calling an exported function, but that is necessary for the empire stager to execute. 

As for your statement on token manipulation, are you referring to just the script Invoke-TokenManipulation? Or are you referring to the module within Empire?

**Comment by CryptomaticSquirrel** [comment]
Thank you very much for the reply. 

Good to know about Invoke-Dllinjection.

For token manipulation I have used the built in mimikatz 2.0. and Invoke-Tokenmanipulation modules. Both seem to succeed but the token rights are not transferred and creating a new agent or process with token rights doesn't stick. I have not yet tried to do it with .ps1 script alone.

I will test them both and get back to you.

**Comment by CryptomaticSquirrel** [comment]
OK... messed around quite a bit with  Invoke-ReflectivePEInjection.ps1 and it doesn't spawn anything. At first I think it crashed through csrss.exe with and error relating to: 

> %SystemRoot%\system32\csrss.exe ObjectDirectory=\Windows SharedSection=1024,20480,768 Windows=On SubSystemType=Windows ServerDll=basesrv,1 ServerDll=winsrv:UserServerDllInitialization,3 ServerDll=winsrv:ConServerDllInitialization,2 ServerDll=sxssrv,4 ProfileControl=Off MaxRequestThreads=16

I changed it to 1024,20480,8192 and that seemed to stop. But it still doesn't seem to spawn anything.

Tried the module through an agent and on command-line with: 
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\Users\Administrator\Downloads\Invoke-ReflectivePEInjection.ps1 -PEPath C:\Users\Administrator\Downloads\test.dll -ProcId 2632`

But still nothing.  Pure PowerShell connects back fine.

Stager used: windows/dll
Listener used: Default settings, IP:44445


Any feedback on how to get token manipulation or DLL injection to work would be awesome.


Target: Windows 8.1 Pro 64bit. Running on VirtualBox.


Put some pictures because I am not sure what would be the better way of describing the problem.

![image](https://user-images.githubusercontent.com/14925118/34321353-7bf3eb9a-e815-11e7-941c-8da5263afc6c.png)

![image](https://user-images.githubusercontent.com/14925118/34321359-c5d52558-e815-11e7-8400-48b49c709dbd.png)

![image](https://user-images.githubusercontent.com/14925118/34321374-624e6d22-e816-11e7-85c4-50808fcab501.png)

![image](https://user-images.githubusercontent.com/14925118/34321457-402a9d22-e818-11e7-86b7-4e9ea29e6f31.png)

**Comment by CryptomaticSquirrel** [comment]
**OK. Got the DLL working.** Probably did some kind of mistake loading the initial module. Just running the .ps1 with arguments doesn't work.  No idea why the built in empire command version didn't wanna run.

But I am still having my main problem with the **token rights not transferring**. Any suggestions?
I cannot use important modules like PTH, golden ticket and more. I assume it is due to the tokens not transferring.
Done for today will try again later.

**Comment by CryptomaticSquirrel** [comment]
I will close down this issue and start a new one on only the token manipulation part. Since there is to much distracting info here on DLL injection.

Hope this isn't a problem.
