### ISSUE TITLE
Obfuscation not detecting PowerShell install (because powershell is now pwsh)

### ISSUE THREAD

**Issue by jaredhaight** [EmpireProject/Empire#876]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Ubuntu 17.10
PowerShell 6.0 rc2
Python 2.7.14

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Installed latest version of PowerShell following the instructions here: https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1704

## Screenshot of error, embedded text output, or Pastebin link to the error
```
(Empire) > usestager windows/launcher_bat
(Empire: stager/windows/launcher_bat) > set Obfuscate True
(Empire: stager/windows/launcher_bat) > set Listener http_com1
(Empire: stager/windows/launcher_bat) > generate
[!] PowerShell is not installed and is required to use obfuscation, please install it first.
[!] Exception: cannot concatenate 'str' and 'NoneType' objects
```

## Any additional information
The helper "[is_powershell_installed](https://github.com/EmpireProject/Empire/blob/7031103caae075042a871a2962fd682bff1c0eee/lib/common/helpers.py#L845)" runs "which powershell" to see if PowerShell is installed. As of the [6.0 beta 9 release](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-beta.9), PowerShell is now "pwsh" not "powershell". I don't know why. 

As a work around, this issue can be resolved by linking pwsh to powershell
```
sudo ln -s /usr/bin/pwsh /usr/local/bin/powershell
```

**Comment by xorrior** [comment]
@jaredhaight We have this updated in the dev branch https://github.com/EmpireProject/Empire/pull/826

**Comment by jaredhaight** [comment]
Woot. Thanks!
