### ISSUE TITLE
uselisteners does not produce listeners listener of choices

### ISSUE THREAD

**Issue by buglessdr** [EmpireProject/Empire#878]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)

linux Kali GNU/Linux Rolling \n \l 
python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
 when typing uselisteners I expect a list of listeners as demonstrated: http://www.harmj0y.net/blog/empire/the-empire-strikes-back/

instead the following is returned:
(Empire: listeners) > listeners
[!] No listeners currently active 
(Empire: listeners) > uselistener
[!] Error: invalid listener module

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://user-images.githubusercontent.com/2553237/34317751-9cb32844-e772-11e7-9bc6-a43259160ed6.png)

## Any additional information
wiped and resinstalled twice to ensure there wasn't an issue during install

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
`uselistener [TAB] [TAB]` to see available listeners

example : `uselistener http`

**Comment by killswitch-GUI** [comment]
@buglessdr, @ThePirateWhoSmellsOfSunflowers is correct. Use tab to list them.
