### ISSUE TITLE
Starting --Rest 

### ISSUE THREAD

**Issue by securityhawk** [EmpireProject/Empire#879]
## Empire Version

2.3

## OS Information (Linux flavor, Python version)

Ubuntu 16.04

I cannot seem to be able to load the restful API with python empire --rest --username xxxxxx --password xxxxx

Empire loads fully with the Empire> command prompt

Any advice is appreciated.

**Comment by CryptomaticSquirrel** [comment]
I think what you are looking for is --headless

**Comment by CryptomaticSquirrel** [comment]
Rest should load the API with a token but you still get the console afterwards. --Headless start just the API and displays the token.

**Comment by securityhawk** [comment]
Perfect thank you @CryptomaticSquirrel !

**Comment by killswitch-GUI** [comment]
Sounds fixed! Thanks @CryptomaticSquirrel
