### ISSUE TITLE
cant start empire recieve errors

### ISSUE THREAD

**Issue by dan7ez** [EmpireProject/Empire#883]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Kali

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/pentest/powershell/empire-ps/lib/common/empire.py", line 31, in <module>
    import agents
  File "/pentest/powershell/empire-ps/lib/common/agents.py", line 68, in <module>
    import encryption
  File "/pentest/powershell/empire-ps/lib/common/encryption.py", line 62, in <module>
    random_function = OpenSSL.rand.bytes
AttributeError: 'module' object has no attribute 'rand'

## Screenshot of error, embedded text output, or Pastebin link to the error
Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/pentest/powershell/empire-ps/lib/common/empire.py", line 31, in <module>
    import agents
  File "/pentest/powershell/empire-ps/lib/common/agents.py", line 68, in <module>
    import encryption
  File "/pentest/powershell/empire-ps/lib/common/encryption.py", line 62, in <module>
    random_function = OpenSSL.rand.bytes
AttributeError: 'module' object has no attribute 'rand'

## Any additional information
I installed empire via the pentest framework

**Comment by CryptomaticSquirrel** [comment]
In my opinion the question might be better asked from the pentest framework guys. Nevertheless 
![image](https://user-images.githubusercontent.com/14925118/34339591-dc123396-e97e-11e7-9443-2993fcfebb42.png)
Not totally sure that the installation gets executed from the correct path. For me the install works about 50 % of time. But the error is different. 
Best of luck.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Maybe your issue is duplicated with #882. It seems to be a known bug.

**Comment by dan7ez** [comment]
Many thanks for the support!

I did an update through the pentest framework and now get the following error when trying to run empire.

Traceback (most recent call last):
  File "./empire", line 1381, in <module>
    main = empire.MainMenu(args=args)
  File "/pentest/powershell/empire-ps/lib/common/empire.py", line 79, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
try `./setup/reset.sh`

**Comment by CryptomaticSquirrel** [comment]
Still quite sure it is due to the unusual path. It didn't reach dependencies before. Now it isn't getting one of the main variables. 
Empire seems quite sensitive about it. But I'll give it a go and let you know what happens.

**Comment by CryptomaticSquirrel** [comment]
use modules/install_update_all
yes
...
Four hours later
out of disk space
Uuups. I make big mistake :)

This took a lot longer then expected. 
Got the same error as you. **Like @ThePirateWhoSmellsOfSunflowers mention ./setup/reset.sh fixed it.** Run ./install.sh and it breaks again and helpers.get_config won't get its variables.

**Comment by CryptomaticSquirrel** [comment]
OK... got this on my main branch as well. 
It seems this happens consistently if you run ./install.sh twice. After a clean git clone. The first time install works nice. Second time it gives the before-mentioned error.  ./reset.sh will fix it.

I'm guessing the pentest framework installed it before and you installed it a second time which caused the error.

**Comment by xorrior** [comment]
@dan7ez @CryptomaticSquirrel @ThePirateWhoSmellsOfSunflowers there is an update in the dev branch to catch changes in the database after an upgrade. Probably won't catch all corner cases, but should catch most of them. 
https://github.com/EmpireProject/Empire/commit/659b15f86cdcce5eb2513aba237d26cbb4a29bfa
