### ISSUE TITLE
DLL doesn't run an agent when using write_dllhijacker.py.

### ISSUE THREAD

**Issue by CryptomaticSquirrel** [EmpireProject/Empire#888]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Kali
Target machine: 64 bit Windows 10. 1703

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

The hijacked process usually crashes and the agent process doesn't spawn.

## Screenshot of error, embedded text output, or Pastebin link to the error

I can see the DLL getting loaded and read from process monitor. But never an agent. Haven't yet been able to pinpoint a specific error that might cause it. 
If I just run the .bat that gets created then I get an agent.

At the moment testing with SSHD process.

## Any additional information

Trying to test if I can get DLL hijacking to work. Is there a trick to this? Does it only work with some DLLs and some software or should I be able to replace  a random processes DLL and it should execute?

Any information or Empire/PowerShell alternatives very welcome!

**Comment by CryptomaticSquirrel** [comment]
I'll add a screenshot. In this case the hijacked dll is wincorlib.DLL. Same problem
![image](https://user-images.githubusercontent.com/14925118/34388158-c2f8d794-eb3a-11e7-983a-40ef957cb060.png)

**Comment by CryptomaticSquirrel** [comment]
**version.dll**
![image](https://user-images.githubusercontent.com/14925118/34389273-5b922252-eb41-11e7-8c19-b7afb37cf5da.png)

**Comment by xorrior** [comment]
What dll are you using? If you are using the empire dll, then i definitely cannot guarantee success. Even so, there are other issues to consider with dll hijacks. For one, the dll you are hijacking may export a function needed by the application. The the attacker dll fires not provide that function, the application may crash.

**Comment by CryptomaticSquirrel** [comment]
Thank you for the reply!

I am using the DLL created by write-dllhijack.py or a function with the same name from PowerUp.ps1.
Both create a .bat file. Which should run and delete itself. But it never gets executed.

I will mess around with it a bit more tomorrow before testing MSF version for dll hijacking.

If you can point me towards an alternative way to get DLL hijacking to work, it would be great.
Or a suggestion what you would use instead of it would be great as well.

**Comment by xorrior** [comment]
@CryptomaticSquirrel I would start by writing a simple DLL that will just pop a message box when loaded. Test that out first to determine if there is an issue with required exports or something else entirely. There could be many reasons why the dll is not working.
