### ISSUE TITLE
[feature] search through agents

### ISSUE THREAD

**Issue by d2-d2** [EmpireProject/Empire#892]
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

search <item> where <item> is Name, Lang, Internal IP, Machine Name, Username, Process

## Screenshot of error, embedded text output, or Pastebin link to the error
N/A

## Any additional information
Hey Dev! First of all, thank you for this tool. It's really usefull. What I'm reporting here is not really a bug, but feature (both close to eachother, no? :) )

Anyways, I just thought it would be nice if user could search through agents. Especially useful when working on screen session with hundreds of agents. What do you think?

**Comment by DakotaNelson** [comment]
#409 is relevant to this, and #763 is an attempt to address that seems in-progress.

**Comment by xorrior** [comment]
@d2-d2 I've reopened #763. If you have time to test it, please do so. I'm closing this out.
