### ISSUE TITLE
Ubuntu repository

### ISSUE THREAD

**Issue by cegi** [EmpireProject/Empire#894]
## Empire Version
From Dev Branch today(because i get "rand" error)

## OS Information (Linux flavor, Python version)
Debian testing, Python 2.7.14+,Python 3.6.4rc1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I don't understand why Empire add Ubuntu 14 repository in source list to download Powershell instead of just downloading it from Github ? Even downloading the binary release is fine. So any change to the install script possible ? Adding repository break things in my case. 
 Thanks for the great work

**Comment by xorrior** [comment]
So what errors are you specifically receiving when running the install script? Can you post those errors please?

**Comment by cegi** [comment]
Thanks  for the answer. I dont have any error while running the scripts, the problem comes from the Ubuntu Source being added which create problems on my system, and i'm asking if it's possible to change =>

**# Install Powershell on Linux
function install_powershell() {
	if uname | grep -q "Darwin"; then
		brew install openssl
		brew install curl --with-openssl
		brew tap caskroom/cask
		brew cask install powershell
	else
		# Deb 9.x
		if cat /etc/debian_version | grep 9.* ; then
			# Install system components
			sudo apt-get update
			sudo apt-get install -y apt-transport-https curl
			# Import the public repository GPG keys
			curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
			# Register the Microsoft Product feed
			sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-jessie-prod jessie main" > /etc/apt/sources.list.d/microsoft.list'
			# Update the list of products
			sudo apt-get update
			# Install PowerShell
sudo apt-get install -y powershell**

And replace it with a git clone of powershell, or wget the latest binary release and install it ?

**Comment by cegi** [comment]
Also for those that get the "rand" error when launching Empire, i found a workaround, go in setup folder and run 'pip2 install --upgrade -r requirements.txt' ,i think the install.sh script does not install the requirements correctly on certains systems.

**Comment by xorrior** [comment]
The rand error should be resolved on the master branch

**Comment by cegi** [comment]
Thanks, if you can change the installation script for debian if no one see any issues about it, it would be greatly appreciated.

**Comment by DakotaNelson** [comment]
You can always change it on just your system - have you tried that yet to
make sure it works?

**Comment by cegi** [comment]
Yes i did, with git clone and wget binary release, it worked fine.

**Comment by xorrior** [comment]
@cegi you can just install macholib with pip. Not sure why it wasn't installed.

**Comment by cegi** [comment]
@xorrior, i installed with pip macholib which did not fix the issue, so i tried 'aptitude install python-macholib' which worked, but now i get :  

Traceback (most recent call last):
  File "./empire", line 1393, in <module>
    main = empire.MainMenu(args=args)
  File "/home/user/Empire/lib/common/empire.py", line 103, in __init__
    self.listeners = listeners.Listeners(self, args=args)
  File "/home/user/Empire/lib/common/listeners.py", line 35, in __init__
    self.load_listeners()
  File "/home/user/Empire/lib/common/listeners.py", line 60, in load_listeners
    self.loadedListeners[listenerName] = imp.load_source(listenerName, filePath).Listener(self.mainMenu, [])
  File "/home/user/Empire//lib/listeners/http.py", line 19, in <module>
    from lib.common import obfuscation
  File "/home/user/Empire/lib/common/obfuscation.py", line 10, in <module>
    from pyminifier import token_utils as py_tokenizer
ImportError: No module named pyminifier

**Comment by DakotaNelson** [comment]
The tl;dr on pip is that to install globally, you need to use sudo, and to install locally (either just for you using the `--user` flag, or in a virtual environment) you don't need sudo.

I know globally works with Empire, I suspect (but don't know) `--user` won't since you'll be running it as sudo, and a virtualenv will also work but requires some setup and maintenance.

**Comment by cegi** [comment]
@DakotaNelson Thanks i appreciate the answer,yes thats what i thought, for example if i use as user "pip2 install shodan" i won't be able to use it even if i sudo, i had to use "sudo pip2 install shodan" for it to work. I will try with --user flag but i know it is sometime tricky and won't work so it's unreliable.

**Comment by DakotaNelson** [comment]
If you look at #771 you can set things up using virtualenvs, which will solve the global install problem, but it'll take some work to set up and maintain. Alternately, I think Docker is live now; see https://blog.obscuritylabs.com/docker-command-controll-c2/ to use that instead.

**Comment by cegi** [comment]
Yes, i made a script to set up a virtual environnement for pip on Empire and Deathstar and managed to make both works without any problems and without using the installer script. So i don't have the Ubuntu repository anymore, and no dependencies error, everything is fine now thanks.

**Comment by cegi** [comment]
So, anyone knows why Empire install Powershell ? I don't understand the reason.

**Comment by xorrior** [comment]
@cegi It's necessary for the use of Invoke-obfuscation
