### ISSUE TITLE
Launcher.bat not working ( code runs infinetly in cmd)

### ISSUE THREAD

**Issue by warhawk23** [EmpireProject/Empire#896]
## OS Information (Linux flavor, Python version)
Kali Linux 2017.3 Rolling

## Any additional information
Respected Developers, I would first like to thank you all for making such an amazing tool and your effort is truly admirable. Recently i've been having some issues with empire. In my initial testing i used the meterpreter listener and along with it used the windows/launcher_bat stager. Everything seemed to work normally but when i launched the launcher.bat on the target machine ( running windows 10), an error popped on the screen which stated that windows cannot find 'function'  and so i didnt get any agent. In order to tackle this i killed the existing listener and repeated the above mentioned procedure several times but to no avail. At every attempt i received the same error. I assumed that this listener was not compatible with this stager and so i used the http listener instead and again used the windows/launcher_bat stager and this time the problem was different. When i launched the .bat file on target system, the command prompt appeared on the screen and the powershell code ran in it as expected but it didnt seem to end. The code ran infinitely in cmd and it did not seem to stop. I did not close the cmd though hoping that the code might stop running after a few minutes and i may get an agent but this did not happen. After five minutes i had to close the cmd myself which was still running the powershell code. I am unable to understand this problem. Can anyone help me out with this?

**Comment by honeyfairy** [comment]
From which location are you running the launcher.bat? 
Try moving launcher.bat to a new folder and run in from there

**Comment by xorrior** [comment]
@warhawk23 What branch were you using? Was the bat file generated with or without obfuscation enabled?

**Comment by warhawk23** [comment]
Before leaving this comment here i again created the listener to check if the problem persisted and i'm surprised that the issue vanished overnight even though i didnt even use it again until today. I dont clearly understand though what was wrong back then but for now it's working like a charm and i can successfully interact with the agent. @xorrior i was generating the .bat file without obfuscation. @honeyfairy i was launching the .bat file from the downloads folder in the users folder in c drive. Even today i launched it from the same location. Anyway, can't thank you guys enough for responding to this issue. I'll keep you updated if anything goes wrong. Keep up the good work guys. Kindly close this issue

**Comment by xorrior** [comment]
👍
