### ISSUE TITLE
work wrong

### ISSUE THREAD

**Issue by heascle** [EmpireProject/Empire#898]
## Empire Version
 [Version] 2.3 

## OS Information (Linux flavor, Python version)
kali ( Debian 4.9.18)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I follow a viedo to learn,but seems mime empire has something wrong.Just see the image and you get it.
Thank you.

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://user-images.githubusercontent.com/26065283/34507254-47781636-f06f-11e7-88a5-21826dc453fe.png)

**Comment by xorrior** [comment]
When in doubt, you can always refer to the help command.
1. uselistener http [or whatever]
2. set Name [name]
