### ISSUE TITLE
Launch error `TypeError: 'NoneType' object is not iterable`

### ISSUE THREAD

**Issue by bkr32** [EmpireProject/Empire#901]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)

kali 2017.2
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
./empire or python empire.py should launch empire

i get this error instead 

```
Traceback (most recent call last):
  File "./empire", line 1393, in <module>
    main = empire.MainMenu(args=args)
  File "/root/Empire/lib/common/empire.py", line 84, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable
```

@xorrior

**Comment by xorrior** [comment]
If you upgrade empire without a fresh install, you will need run reset.sh

**Comment by bkr32** [comment]
sigh done
