### ISSUE TITLE
dbx listener crash

### ISSUE THREAD

**Issue by alex-bergman** [EmpireProject/Empire#904]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)
Linux 16 3.13.0-87-generic #133-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

(Empire: listeners/dbx) > execute
[*] Starting listener 'dropbox'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/root/emp2.4/lib/common/helpers.py", line 892, in __run
    self.__run_backup()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/emp2.4//lib/listeners/dbx.py", line 858, in start_server
    stagerCodepy = self.generate_stager(listenerOptions=listenerOptions, language='python')
  File "/root/emp2.4//lib/listeners/dbx.py", line 436, in generate_stager
    template = eng.get_template('dropbox.py')
  File "/root/emp2.4/lib/common/templating.py", line 46, in get_template
    return self.env.get_template(filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: dropbox.py

**Comment by xorrior** [comment]
@DakotaNelson any idea why it's not finding the dropbox stager, I reviewed the logic and everything looks correct. It's identical to the http listener. Can't really debug any further with pdb since the start_server function is threaded.

**Comment by DakotaNelson** [comment]
If it's not in Docker, the hardcoded Docker-specific paths won't work. Thinking of a fix...

**Comment by DakotaNelson** [comment]
Ok, got something.

See: http://jinja.pocoo.org/docs/2.10/api/#jinja2.FileSystemLoader

> The loader takes the path to the templates as string, or if multiple locations are wanted a list of them which is then looked up in the given order:

```
>>> loader = FileSystemLoader('/path/to/templates')
>>> loader = FileSystemLoader(['/path/to/templates', '/other/path'])
```

So we can change https://github.com/EmpireProject/Empire/blob/a0234bd195f4f69ba2137b6372eadcb9602311c9/lib/listeners/dbx.py#L434-L435

to have both the possible template paths (absolute - Docker style - first, then relative) then it should work for either environment. I think I'll have to fiddle with the `TemplateEngine` init as well, but this shouldn't take long.

**Comment by DakotaNelson** [comment]
Oh, yeah, though @alex-bergman as a hotfix you can go here:

https://github.com/EmpireProject/Empire/blob/a0234bd195f4f69ba2137b6372eadcb9602311c9/lib/listeners/dbx.py#L434

If you change `/data/agent/stagers/` to `./data/agent/stagers` I believe it should work.

**Comment by xorrior** [comment]
@DakotaNelson thanks. I saw that doc for using the FileSystemLoader but I wasn't sure if that would resolve the issue.

**Comment by xorrior** [comment]
@alex-bergman fixed.
