### ISSUE TITLE
AttributeError on --rest & --headless commandline argument

### ISSUE THREAD

**Issue by ChaitanyaHaritash** [EmpireProject/Empire#906]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)
BackBox 4.6

## Issued command (didn't had any right word lol)
./empire --rest --username abc --password abc

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
should have got my empire session started 

## Screenshot of error, embedded text output, or Pastebin link to the error

Error 
![error](https://user-images.githubusercontent.com/16261173/34621468-4640c00e-f26f-11e7-9f9b-2086f88f2b09.PNG)

Code 
![code](https://user-images.githubusercontent.com/16261173/34622541-961d760e-f273-11e7-8327-ffbb73754500.PNG)

## Any additional information

I think using [load_cert_chain](https://docs.python.org/2/library/ssl.html#ssl.SSLContext.load_cert_chain) would be better :/

**Comment by xorrior** [comment]
So I was not able to reproduce this issue on a Ubuntu 17 image after a fresh install. Both the rest and headless options worked.
<img width="980" alt="ubuntu-headless-empire" src="https://user-images.githubusercontent.com/9156069/34660800-cd02b92a-f40a-11e7-875f-ec4c3acf2cd4.png">

My first hunch would be the version of python you are using or there were errors during the install. For any OS outside of Ubuntu, Debian, or Kali, I would suggest using the docker image.

**Comment by ChaitanyaHaritash** [comment]
weird, i was using ubuntu 14 based os with python 2.7, ill try again..

**Comment by xorrior** [comment]
@ChaitanyaHaritash was this a VPS?

**Comment by ChaitanyaHaritash** [comment]
Nope, im testing all locally
