### ISSUE TITLE
Install issues on Kali Linux

### ISSUE THREAD

**Issue by SadProcessor** [EmpireProject/Empire#910]
## Empire Version
2.4

## OS Information
Fresh Kali 2017.3 + full updates

## Expected behavior and description of the error
./setup/install.sh does not complete as expected

A. Install of **Powershell** fails when using current method
- **libicu55** has no install candidate
- wget for **libssl1.0.0** fails at http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb

> Installing via debian 9 .deb + dpkg seems to work for powershell install issue (and has less dependencies)

... but 

B. Error during ./configure linked to **libcrypto (openssl)** 
see screenshot

## Screenshot
![libcryptoerror](https://user-images.githubusercontent.com/15706849/34629189-363f6440-f25f-11e7-8cf6-65c543fe072c.png)

## Any additional info
Strangely enough after that I still could start Empire, execute http listener, generate stager...
but then on agent 1st call back to http listener I get following 

![agtllbck](https://user-images.githubusercontent.com/15706849/34629290-867ce52c-f25f-11e7-9be5-4e1edfc5c47b.png)

have asked google for help the whole day but no success... :(

**Comment by SadProcessor** [comment]
Just adding some info on possible fixes the powershell install (A):

## Powershell install - method 1 (Kali)
> tried this method first
```bash
#Install libunwind8
apt-get install libunwind8 -y

#Install libsll1.0.0
wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
dpkg -i libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb

#Install libicu55
wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7ubuntu0.3_amd64.deb
dpkg -i libicu55_55.1-7ubuntu0.3_amd64.deb

#Install liblttng-ust0
apt-get install liblttng-ust0 -y

#Install PowerShell
wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc.2/powershell_6.0.0-rc.2-1.ubuntu.16.04_amd64.deb
dpkg -i powershell_6.0.0-rc.2-1.ubuntu.16.04_amd64.deb
```
> seemed to work, but was getting following error

![kaliposherror](https://user-images.githubusercontent.com/15706849/34631805-1951064e-f26a-11e7-9604-ca7122717b41.png)

> @cobbr mentionned fix for this via empire slack (thx!)
```bash
#Fix for *segmentation_fault* error in **pwsh**
rm /opt/microsoft/powershell/*/DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY
```


## Powershell install - method 2 (debian9)
> less dependencies, no segmentation_fault error
> not official, but powershell github info is out-of-date date for Kali so...
> gave it a go, as Kali 2017.3 is based on stretch (if I am not mistaking), and it seems to work!!

```bash
#Install debian 9 package
wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc.2/powershell_6.0.0-rc.2-1.debian.9_amd64.deb
dpkg -i powershell_6.0.0-rc.2-1.debian.9_amd64.deb

#fix dependency error
apt-get install -f

```
hoping this might help...

**Comment by xorrior** [comment]
@SadProcessor can you try installing  libssl1.0-dev ?

**Comment by SadProcessor** [comment]
@xorrior  I found the following older issues on same error
https://github.com/EmpireProject/Empire/issues/521
https://github.com/EmpireProject/Empire/issues/720
https://github.com/EmpireProject/Empire/pull/811

So I installed **libssl1.0-dev**, then was complaining about zlib, so I installed **zlib1g-dev** as well
-> No more error during xar ./configure but now giving warnings for unused vars during xar make...

![empiremake](https://user-images.githubusercontent.com/15706849/34640946-24d4e118-f2f4-11e7-99f7-30f83a5fb782.png)

not sure I'm going the right direction here...
Still get same error down the line when agent calls back to http listener

![agtllbck](https://user-images.githubusercontent.com/15706849/34641051-e88881ae-f2f5-11e7-9284-1c2eedacfca9.png)

  Will have another go later tonight...

**Comment by SadProcessor** [comment]
@xorrior, while googling around for the error I am getting during make,
I landed on https://github.com/EmpireProject/Empire/issues/855
I tried **pyopenssl<17.1** via requirements.txt but still get same error.
Any idea on what I should try next?

![libeasig](https://user-images.githubusercontent.com/15706849/34644785-2b65f45e-f335-11e7-92a9-29c96b8a4e20.png)

(also tried combined with **cryptography<1.7** as per https://pyopenssl.readthedocs.io/en/latest/install.html but still same error during make) 😠

**Comment by xorrior** [comment]
@SadProcessor I would ignore the warnings in the xar build. I've received those same warnings for every successful build of xar. Most of them are in reference to unused variables anyway.

**Comment by SadProcessor** [comment]
@xorrior, 
Ok, fair enough. I'm happy to not have to worry about that one, because I tried a few distros (Debian/Ubuntu/Kali) and was always getting it.
So Kali install should work with Powershell install using debian9 method (2 above) with libssl1.0-dev and zlib1g-dev ...

In the meanwhile, I went the docker way on Kali and it works. Didn't see the Dockerfile at first, but it was there... :smile:
Pulling 2.4 was as easy as removing `-b dev` from the `git clone ...` on line 55 (as in comments).
Awesome stuff...
(Now trying to figure out how to hit container on API... but that's another story).

Thanks for support.
Will retest on Kali to confirm.

**Comment by xorrior** [comment]
@SadProcessor if you want to have docker available on the same networking stack for the host OS, just use the --net=host flag. Any ports made available on the host will be available for the container. To be more specific, you can use -p .

**Comment by SadProcessor** [comment]
@xorrior 
made some more tests... 
I still get to same error on kali 2017.3 | Ubuntu 16.04 | Debian 9.3 😢 
The error I get points to **encryption.py** line 133
I checked history and found this...
https://github.com/EmpireProject/Empire/commit/6932decba35cf17e39b5ab489fd28444b73db07b#diff-370843e5a7e8191e8a6d612c8ec4d5e0
Do you this this change could cause this error? (same on 3 OS)

![agtcllbck](https://user-images.githubusercontent.com/15706849/34689094-3f443fd0-f4ac-11e7-9936-9015d9529b02.png)
![deb9](https://user-images.githubusercontent.com/15706849/34689095-3f6d0f28-f4ac-11e7-92ee-ac359471cd5c.png)
![ubu16](https://user-images.githubusercontent.com/15706849/34689096-3f91da92-f4ac-11e7-95f4-0718a0622d5a.png)

tried reverting this change but didn't help (got other error, probably broke it even more...)
What can I do next? I'm running out of idea here...

**Comment by xorrior** [comment]
@SadProcessor So I'm not able to reproduce this on the master branch with either Ubuntu 17 or the latest Kali rolling release. Both installs finish without issue and I can stage a powershell and python agent successfully. Just curious, how are you executing the stagers?

**Comment by SadProcessor** [comment]
W(TF)!? That's it... I need a day off... 
From my testing, install fails on Kali without changes to install.sh (powershell not installed)...
And no matter what, I get this error on staging...
I am trying all this over REST API (all other commands work) and it works on 2.3...
... I think I'm gonna do something else for a couple of days and come back to it. I'm obviously doing something wrong...
Thanks for checking for me @xorrior ... 👍

**Comment by xorrior** [comment]
@SadProcessor No worries. I'll merge your PR into dev shortly and your stress levels should decrease 😄

**Comment by cobbr** [comment]
@xorrior I'm also experiencing the same PowerShell install issue as @SadProcessor on the latest Kali.

Taking a quick glance at the updated install.sh script [here](https://github.com/EmpireProject/Empire/blob/master/setup/install.sh), it looks like the Kali install instructions are not using the apt repo anymore. Install instructions [here](https://github.com/cobbr/ObfuscatedEmpire/blob/empire-dev/setup/install.sh#L56-L64) may help.

Haven't had a chance to dig in yet to be sure, but once I get a chance I'll submit a PR.

**Comment by whoot** [comment]
I really dont know why you changed the install script to use libssl1.0.0 again.
This seems to be an issue since Empire 2.0 (see #521 ). You changed it to libssl1.0-dev and then changed it back to libssl1.0.0

I´m experiencing the same error as @SadProcessor and the only way to fix this is to use libssl1.0-dev.

**Comment by xorrior** [comment]
@whoot just to confirm, libssl-dev should be changed to libssl1.0.0-dev? 
https://github.com/EmpireProject/Empire/blob/dev/setup/install.sh#L142

**Comment by whoot** [comment]
I could get rid of the "error during ./configure linked to libcrypto (openssl)" the same way as @SadProcessor mentioned in his previous posts by installing libssl1.0-dev
Otherwise it seems that Empire does not support HTTPS connections.

**Comment by xorrior** [comment]
@whoot it should, are you having issues with HTTPS because of libssl1.0-dev or is this a separate issue??

**Comment by DanMcInerney** [comment]
Here's everything I did to fix the compilation errors in xar which is part of Empire's install.sh script in Kali 2017.3:

apt-get install libssl1.0-dev libxml2-dev zlib1g-dev

**Comment by xorrior** [comment]
I've updated the kali install dependencies with the suggestion from @DanMcInerney. The install for kali will now include libssl1.0.0-dev and libssl-dev.
