### ISSUE TITLE
Empire 2.4 - No agent checkins 

### ISSUE THREAD

**Issue by honeyfairy** [EmpireProject/Empire#919]
## Empire Version
2.4 Latest
## OS Information (Linux flavor, Python version)
Kali 2017 Latest

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

After doing a git pull on my Empire 2.3 I received some errors that included the word 'Obfuscation' and line 104 i think. Anyway after the update no check ins after the pull so i reset database, re set up... no luck.
I rage rm -r /Empire 
and git clone empire again.

After a new installation I executed a http listener on port 80 and another http listener on port 465
Used multi/launcher and windows//launcher_xml and launcher_bat - No agent checkin

**Comment by xorrior** [comment]
@honeyfairy can you provide some more information? What OS were you targeting? Can you elaborate on the Obfuscation error? Provide the output from that or a screenshot? The more information you can provide, the easier it is to troubleshoot. With the information you have provided so far, there is no way for anyone to determine what happened....

**Comment by xorrior** [comment]
@honeyfairy feel free to re-open once you can provide some additional information.
