### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by KorayAgaya** [EmpireProject/Empire#921]
## Empire Version
I have Empire last version

## OS Information (Linux flavor, Python version)

DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

uname -m = x86_64
uname -r = 4.14.0-kali3-amd64
uname -s = Linux
uname -v = #1 SMP Debian 4.14.12-2kali1 (2018-01-08)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I try install via ./setup/install.sh and I tried to load 10 times same error

Traceback (most recent call last):
  File "./empire", line 1368, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/TOOLS/Empire/lib/common/empire.py", line 84, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

THAN SECOND ERROR

./setup/setup_database.py 

 [>] Enter server negotiation password, enter for random generation: **************
Traceback (most recent call last):
  File "./setup/setup_database.py", line 120, in <module>
    )''')
sqlite3.OperationalError: table "agents" already exists

**Comment by xorrior** [comment]
@KorayAgaya running reset.sh in the setup folder should resolve this issue.
