### ISSUE TITLE
' error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 '

### ISSUE THREAD

**Issue by bkr32** [EmpireProject/Empire#924]
## Empire Version
git version master

## OS Information (Linux flavor, Python version)
kali installed on WSL as per https://www.kali.org/tutorials/kali-on-the-windows-subsystem-for-linux/

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
while running setup i get the error `' error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 '` on M2Crypto

## Any additional information
just trying to get empire to work on this WSL kali version

**Comment by DakotaNelson** [comment]
Can you provide more context around the error message? A screenshot or more console output?

**Comment by bkr32** [comment]
hey @DakotaNelson was trying to run empire on a kali installation of WSL 
https://www.kali.org/tutorials/kali-on-the-windows-subsystem-for-linux/
however it seems some dependencies are missing causing `pip install m2crypto`
to give this error `' error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 '`

**Comment by DakotaNelson** [comment]
I think you have the same problem as #920.

**Comment by xorrior** [comment]
@bkr32 For operating systems outside of Kali, Debian, Ubuntu I would highly suggest using the docker build. In your case, I'm not sure if that would be a solution for you but the dependencies required for empire have become a massive headache to maintain in order to support every linux distro and OS. It just isn't feasible.

**Comment by bkr32** [comment]
understood @xorrior

**Comment by nvondad** [comment]
FYI, after fighting with it for a couple of hours I now have Empire running on Kali via WSL. I had to install a bunch of the dependencies manually, too many to remember here. But with persistence it is possible.

**Comment by Nihsa** [comment]
Can you write us which dependencies ? I have the same problem
