### ISSUE TITLE
configuration of empire with public ip

### ISSUE THREAD

**Issue by killercoderz4** [EmpireProject/Empire#925]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)

ubuntu 16.04 64 bit linux
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

i would like to know understand how to hook it up using my public ip , i have portforwardded some ports. the things is both listener and launcher would use either local or public, how do i configure it to use my public ip.Thanks
## Any additional information
#

**Comment by DakotaNelson** [comment]
Hey @killercoderz4, I could use a little more clarity - is the problem that you don't know which IPs to bind to, or there's an issue getting the listener and launcher to point to the right IPs (or something else)?

A read of http://www.ipprimer.com/#/nat might help you out in either case, but I don't think the Empire dev team is going to be of much help, this is fairly specific to your network configuration.

**Comment by killercoderz4** [comment]
i use public ip in metasploit to build my payload and portforward ,this enables my system access my remote vps server. in empire it different it automatically uses my local ip althrough which means its stuck in my lan, i cant use it to acess my vps, to achieve that i need my public ip to be configured in empire that why i ask

**Comment by DakotaNelson** [comment]
Ahhhhh, alright.

When you're setting up a listener/stager/etc. you can use the `info` command to see the current settings and the `set` command to configure them. That should let you set your IP and ports settings to be what you need them to be.

You can always use `help` or tab-completion to see what commands you can run.

**Comment by killercoderz4** [comment]
@DakotaNelson Thank you sir for your input would give it a try.just want to ask although it kind of diffrent from the topic at hand. i built a powershell oneliner payload and saved it as .bat for easy testing by just clicks, but  iset amnd updated my windows defender on my vmware it dirupting my bat file which is kind of surprising becuase i also setup avast and it bypasses it. i came across a tool invoke obfuscation. the challenge i have is it works on.ps1 files but whenever i obfuscate and save it as .bat it doesnt report. do you have any clues how to implement advanced obfuscation for.bat launchers.Thanks

**Comment by DakotaNelson** [comment]
There should be an obfuscation option in the launcher (I think...).

Otherwise, that's a question for the Invoke-Obfuscation team, unfortunately I don't know enough about that to give you an answer.
