### ISSUE TITLE
urllib

### ISSUE THREAD

**Issue by wtf123000** [EmpireProject/Empire#929]
## Empire Version
Latest (git clone)

## OS Information (Linux flavor, Python version)
Ubuntu 14.04 vps (fresh install)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
type ./empire to start program and gets dependency errors.

## Screenshot of error, embedded text output, or Pastebin link to the error

![capture](https://user-images.githubusercontent.com/35235800/34911095-a00f7d1c-f87f-11e7-8c99-1b7aa1d8ab67.PNG)

I should say that Empire 1.5 works fine on the VPS.

**Comment by DakotaNelson** [comment]
Looks like the same problem as [this](https://stackoverflow.com/questions/44927351/importerror-cannot-import-name-dependencywarning) and [this](https://github.com/dropbox/dropbox-sdk-python/issues/112), some of those solutions might help you.

**Comment by xorrior** [comment]
Yea, the VPS builds all seem to have this issue. Should be fixed with pip install -U urllib3 and pip install -U requests.
