### ISSUE TITLE
available listeners can't be found

### ISSUE THREAD

**Issue by samirimtiaz1996** [EmpireProject/Empire#932]
Empire Version:2.4

OS Information :kLinux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.10-1kali2 (2017-11-08) x86_64 GNU/Linux

I can not find available listener types. Sample screenshot is below.Sorry for my poor English .It's not my native language

![screenshot from 2018-01-15 18-46-18](https://user-images.githubusercontent.com/29258282/34943743-1b03ecee-fa27-11e7-9652-96f017dd148e.png)

**Comment by DakotaNelson** [comment]
Try hitting the space bar, *then* tab tab.

So: `uselistener [space] [tab] [tab]`

Got me the first time too. :)

**Comment by samirimtiaz1996** [comment]
Thanks a lot
