### ISSUE TITLE
[FEATURE] Ability to retrieve information about Agent Jobs

### ISSUE THREAD

**Issue by djhohnstein** [EmpireProject/Empire#935]
## Empire Version
Whenever it's added

## OS Information (Linux flavor, Python version)
For any implementation of Empire, probably a database enhancement

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I'd like the ability (either from the Empire interactive console launched from ./empire, searching a log or otherwise) to retrieve all information surrounding a Job issued to an agent.

For example, if I issue an invoke_psexec on a remote machine, a job is started on my agent. In the agent.log, I know that a job was started involving psexec, but I don't know:

- Module Options
- Output from the Job
- Relating to PSEXEC directly, if a connect back was received.

This becomes helpful when say reporting comes into play. The only way I can do this now is by correlating similar timestamps

## Screenshot of error, embedded text output, or Pastebin link to the error
n/a

## Any additional information
n/a

**Comment by DakotaNelson** [comment]
I've started on this in #933: once that PR is merged agent tasks will give you something like this from the REST API's `/api/reporting` endpoints:

`{"task":"ls","task_name":"TASK_SHELL"}`
or
`{"task":"print(\"hello\")","task_name":"TASK_CMD_WAIT"}`

(along with a timestamp and agent name, of course)

That said, I'd like to add to that PR to include more detail and more events as part of a general event system overhaul; this is a great idea!

**Comment by bneg** [comment]
Following other implementations in Empire I can see it as a serialized object (pickle) in the DB. Write out the params in a new field in the DB

**Comment by xorrior** [comment]
@bneg So for the jobs table, the first few lines of the module are saved in the db. IIRC the entire contents of the module is stored in the agents table under taskings.

**Comment by bneg** [comment]
Unfortunately @xorrior, that data appears to be truncated

Having the module name would be nice for reporting, at least for me :)

**Comment by xorrior** [comment]
@bneg roger

**Comment by bneg** [comment]
From a database dump

__Task:__  function Invoke-EventVwrBypass {
    [CmdletBinding(SupportsShouldProcess = $True, ConfirmImpact = '
__Results:__
Job started: G68VTY[!] Current user not a local administrator!

**Comment by xorrior** [comment]
@djhohnstein @bneg #933 has been merged. Hopefully that provides the information you guys are looking for.
