### ISSUE TITLE
Powerview and other situational awareness network modules not working on multiple versions. 

### ISSUE THREAD

**Issue by wbbigdave** [EmpireProject/Empire#940]
Empire Versions 2.2, 2.3, 2.4

Ubuntu 16.04 Python 2.7

The modules for powerview do not return any details. Using Wireshark I am able to confirm that the client does not even appear to execute any commands. I have downloaded the powerview module from data/module_source/Situaltional_awareness/Network/powerview.ps1 and imported it manually, so i know the code source in these releases works correctly. 

I rolled back to 2.1 and the all modules executed as expected.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Same problem here. Unfortunately I don't have the time to perform some debug.

**Comment by wbbigdave** [comment]
@ThePirateWhoSmellsOfSunflowers what's the best way to debug this? There is nothing in the --debug logs which would indicate what the issue is.

**Comment by strikeoncmputrz** [comment]
I am having the same issue, e.g. /situational_awareness/network/powerview/get_user immediately completes. I thought that it was operator error.

**Comment by xorrior** [comment]
@wbbigdave @ThePirateWhoSmellsOfSunflowers @strikeoncmputrz I'll look into this shortly

**Comment by wbbigdave** [comment]
@xorrior The problem appears to have manifested in version 2.2 where the dynamic code generated for these modules changed. I echoed the output from the module script as it builds the code and there was a huge difference in the 2.1 code and 2.2.

Running this generated code locally, the >2.2 versions failed whilst parsing the dynamic parameters.

**Comment by bkr32** [comment]
@wbbigdave is find_local_adminaccess part of those modules that aren't working correctly?

**Comment by wbbigdave** [comment]
@bkr32 Yea, it seems anything which uses the Powerspolit module is failing.

**Comment by xorrior** [comment]
@wbbigdave The issue is with the generate_dynamic_powershell_script function in the helpers class. It will grab the source for the target function and all of it's dependencies. For some reason it does not properly strip the comments.

**Comment by xorrior** [comment]
Fixed.
