### ISSUE TITLE
problem in install

### ISSUE THREAD

**Issue by wisuri** [EmpireProject/Empire#941]
## Empire Version
version 2.4

## OS Information (Linux flavor, Python version)
ubuntu python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
problem in install package libssl1.0.0 not available 

## Screenshot of error, embedded text output, or Pastebin link to the error
https://image.ibb.co/b1P91m/2018_01_18_203302.png
https://image.ibb.co/dpeL7R/2018_01_18_203331.png

**Comment by DakotaNelson** [comment]
See #910, I believe that should help.
