### ISSUE TITLE
persistence failur in empire 2.1

### ISSUE THREAD

**Issue by killercoderz4** [EmpireProject/Empire#946]
## Empire Version

2.1
## OS Information (Linux flavor, Python version)
latest

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

i tested version 2.1 ,that one seem to have the only functional keylogger that works. but persistence just fails in many modules. i tried skeleton key persist ,job started but when urestart machine no agent session is created. this project seem to be ridden with lots and lots of modules that just dont work. coming from cobalt strike, i say empire has a long way to go. there are too many bugs ,instability and takes ages to get basic stuff flowing which cobalt strike handles with ease

**Comment by DakotaNelson** [comment]
Just a heads-up that Cobalt Strike is a commercial product while Empire is open-source and maintained by volunteers - not exactly a 1:1 comparison.

You're right that it does suck when Empire doesn't work - of course it would be better if it did! But alas, the people who work on this don't have the time to make everything work as well as they'd like on top of their day jobs.

As you noted, there are plenty of problems that could use some work - I'm sure I can speak for @xorrior in saying that contributions are welcome!

**Comment by xorrior** [comment]
@killercoderz4 So a couple things. 
- The latest version is 2.4. Please use a fresh empire install.
- You already have created an issue in regards to the keylogger. No need to mention that here.
- Which modules aren't working? Please review the current issues to ensure that there isn't already an issue for the module your having problems with. Complaining about the project certainly doesn't motivate devs who use their time, outside of work, to fix your issue any faster. Keep that in mind.

**Comment by killercoderz4** [comment]
@DakotaNelson @xorrior thanks for your input. i did a clean install on a new vm and got persistence to work. only slight challenge is when i restart and empire generates new session for an agent keylogger doesnt work or log to the keylog.txt file . even after i run the keylogger job.Thanks

**Comment by xorrior** [comment]
@killercoderz4 Any persistence you install will result in a new agent session for empire once the host has restarted and triggered the persistence mechanism. Lets track the keylogger issue in #939 .
