### ISSUE TITLE
inability to load the framework

### ISSUE THREAD

**Issue by eqhaleel** [EmpireProject/Empire#948]
## Empire Version
the following error is displayed.
![screenshot from 2018-01-20 19-59-20](https://user-images.githubusercontent.com/29148605/35189618-7d20ec88-fe46-11e7-9629-ef01fbc392ba.png)
 help offered would be very much appreciated

**Comment by elitest** [comment]
Have you run the install script as outlined in the ["Install"](https://github.com/EmpireProject/Empire#install) section of the Readme?

**Comment by eqhaleel** [comment]
yes,i installed it as outlined in the install section

**Comment by DakotaNelson** [comment]
This should be solved by running reset.sh. There are several other issues
with this same problem.

**Comment by eqhaleel** [comment]
it did solve the problem,i am very grateful to @DakotaNelson @elitest for your aid. thank you

**Comment by DakotaNelson** [comment]
Happy to help!
