### ISSUE TITLE
[!] Exception: [Errno 2] No such file or directory: 'launcher.pkg', Fresh Kali linux

### ISSUE THREAD

**Issue by Arvanaghi** [EmpireProject/Empire#951]
## Empire Version
Latest commit as of 1/21/18

## OS Information (Linux flavor, Python version)
Kali 3.26.2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
No .pkg file generated under osx/pkg, instead get `[!] Exception: [Errno 2] No such file or directory: 'launcher.pkg'`

**Comment by xorrior** [comment]
@Arvanaghi were there any install errors for xar? If xar isn't available then creating a the pkg launcher will not work. Sorry for the late response.

**Comment by xorrior** [comment]
@Arvanaghi please let me know if you are able to provide any additional information. Until then, this will be closed.
