### ISSUE TITLE
Fix Circle-CI

### ISSUE THREAD

**Issue by elitest** [EmpireProject/Empire#952]
Would it be possible to put a timeout in the setup_database.py so that Circle-CI doesn't timout?

**Comment by xorrior** [comment]
@elitest No need to worry about the Circle-Ci failures. The database script shouldn't pause at all as the environment variable to use a random key is set in CI. I had a great testing script setup until I ran into an issue on the docker containers and sockets used by CI. This became a major roadblock so I am still looking for another testing solution. I'll remove CI completely soon.
