### ISSUE TITLE
Empire threading with autorun

### ISSUE THREAD

**Issue by W33v3ly** [EmpireProject/Empire#955]
## Empire Version

2.4

## OS Information (Linux flavor, Python version)

Ubuntu 16.04 
Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Hello i have thousand machines but when i remove all this machines and they loop again reconnect and then I use autorun then after 1 minute the Empire says : Python threading errors can t start new thread and this is infinite loop..is possible to reconnect all with autorun enabled but without any errors? Any Advice? Thanks for reply sorry for my grammar.

**Comment by xorrior** [comment]
I don't believe I've ever seen someone with a thousand agents in Empire. I imagine the server is hanging by a thread (haha ). I imagine removing all those hosts at once and then initiate key renegotiation places a significant load on the server. My best advice would be to kill hosts in batches. We don't have the ability to do stress testing with such a large number of agents. This is not something that normally occurs.
