### ISSUE TITLE
How to use EmpirePowershell 2.4 over the internet  

### ISSUE THREAD

**Issue by kashanpak** [EmpireProject/Empire#956]

**Comment by xorrior** [comment]
@kashanpak, If I'm understanding you correctly, all you need to do is your host in the listener options to http://externalIP:Port and then set the bind Port to the port being used internally. As long as your port forwarding rules are correct, that should work.

**Comment by kashanpak** [comment]
Duplicate of #956 

As you told that put externalip:Port(Port=>4443) to listener host. I have done the same as you told. For the BindIp I leave it as 0.0.0.0 and for the Port i set it to 4443. and in the router I also set it 4443 and check the connection from canyouseeme.org. The result shows service is running on port 4443 success. but i didnt get a response back from different computer except the one which is on the same network.

I will be thankful to you if show me a screenshot of what to put. Thanks
