### ISSUE TITLE
Agents get detected by AV.

### ISSUE THREAD

**Issue by CryptomaticSquirrel** [EmpireProject/Empire#960]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
Host: Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux
Windows 2016. Fully patched Windows Defender with AMSI.
8.1 with patched Windows Defender and detected with ATA and ASC which isn't much of a problem for me.

## Screenshot of error, embedded text output, or Pastebin link to the error
Windows Defender directly says if found malicious PowerShell or I get a response marked with AMSI that it thinks that a .dll is Mimikatz even though it is a Empire stager

## Additional information
I have tried .bat .vbs .dll and the regular PowerShell oneliner. None of them worked. Clean or obfuscated. Vbs didn't work at all when obfuscated.
PowerShell successfully passed detection after a high amount of manual obfuscation through invoke-obfuscation. But currently on PowerShell 6.0 core Invoke-Obfuscation doesn't work well enough for me to automate it.
I used the .dll with Invoke-ReflectivePEInjection. I did not obfuscate it other then using the WString function. Also the attack with the remote parameter. I am not sure if I need to obfuscate both the .ps1 or .dll for it to work.

#### Any suggestions on what should be done to evade AV or keep a foothold would be very much appreciated.  
Also letting me know what I am doing wrong would be great as well.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
I think you should take a look at #938.
🌻

**Comment by CryptomaticSquirrel** [comment]
Damn... That make things more difficult for me. Thanks a lot for the reply.
