### ISSUE TITLE
windows/ducky

### ISSUE THREAD

**Issue by kiberzoid** [EmpireProject/Empire#969]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)
kali linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

When I generate stager/windows/ducky I get:
DELAY 3000
GUI r
DELAY 1000
STRING powershell
ENTER
DELAY 2000
STRING powershell -W Hidden -nop -noni -enc -Force 
ENTER

EncodedCommand is missing...
It looks as if only the last element remained from the command
What am I doing wrong?

**Comment by tortureau** [comment]
Wheres -Force coming from?? The only thing you need to set from default to have a working stager for that module is the listener.

**Comment by kiberzoid** [comment]
Listener was set
![screenshot from 2018-02-04 10-48-08](https://user-images.githubusercontent.com/8117086/35776708-7721c0b0-0999-11e8-92de-b16ef8ad7d82.png)
![screenshot from 2018-02-04 10-48-34](https://user-images.githubusercontent.com/8117086/35776730-ce31b284-0999-11e8-9631-c1f57e548d0f.png)

**Comment by xorrior** [comment]
Fixed. @kiberzoid Sorry for the inconvenience.
