### ISSUE TITLE
Missing PyCrypto package in Docker image

### ISSUE THREAD

**Issue by Martyx00** [EmpireProject/Empire#970]
## Empire Version
2.3.0 docker image at https://hub.docker.com/r/empireproject/empire/ 

## OS Information (Linux flavor, Python version)
Kali

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Current release of docker image seems to be missing pycrypto package.

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://user-images.githubusercontent.com/20481897/35805160-1317386a-0a7b-11e8-96cb-b5ffa801f2ff.png)

## Any additional information
N/A

**Comment by xorrior** [comment]
@Martyx00 were there any errors during the docker build? Also can you see if you can reproduce this on the 2.4 container? Just build a new container with the latest version of empire.

**Comment by Martyx00** [comment]
I got the one from Dockerhub and everything went fine without any issues.  Previous version worked like a charm.

**Comment by Martyx00** [comment]
I have verified on clean install of Fedora and it seems to be fine. Probably issue with my Kali instance. Closing the issue.
