### ISSUE TITLE
Question. Is it possible to automatically answer a prompt?

### ISSUE THREAD

**Issue by wbbigdave** [EmpireProject/Empire#976]
Empire Version 2.4 Ubuntu 16.04 Python 2.7

Hello,

I am currently writing tools for automating empire using plugins and resource files and I have a couple of questions. 

1: Is it possible, using a resource file to answer a y/n prompt on modules which are not OpsecSafe? I am running this in a test environment over a long period to simulate attacker behaviour and would like to not have to interact with the  process at all. 
2: Is it possible to make plugins globally available? At the moment I have to use my resource file to jump back to the main menu each time I want to use the plugin. 

I know this would all probably be better served by the API, and in the future for more complex automation / simulation I will be using it, but I was looking for a quick win.

**Comment by xorrior** [comment]
@wbbigdave to answer prompts you would need to send the response to stdin, within that particular menu class. Not sure how to do that.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
For the question 1) : Have you try with the REST API ?

**Comment by wbbigdave** [comment]
@ThePirateWhoSmellsOfSunflowers that's my today project.
