### ISSUE TITLE
Can't communicate with agents connected to 127.0.0.1 in Empire 2.4

### ISSUE THREAD

**Issue by Strazzom** [EmpireProject/Empire#980]
## Empire Version
2.4 (have not tested on latest dev commit, will follow).

## OS Information (Linux flavor, Python version)
Kali Rolling, Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Expected behavior: If a listener is created with Host set to 127.0.0.1, then a stager started on the same machine should be able to connect back to 127.0.0.1.

Actual behavior: Listener receives initial agent connection, but any commands (such as `sysinfo`) are not executed on agent. It connects back and registers in the database, but after that there either aren't any other connections, or it attempts to connect but does not do so successfully.

## Screenshot of error, embedded text output, or Pastebin link to the error

https://gist.github.com/Strazzom/e95341da18aafe85ed7465325c8a5d00

## Any additional information

Bit of context: there are certain kinds of "proxies" (not really proxies in the true sense) that forward connections from a remote server to a local port. Think `ssh -R <rport>:<host>:<lport>`. SSH tunnels are one example, however there are multiple technologies that do this.

Ngrok and Serveo do this, (ngrok have their own tool, serveo just uses plain SSH). The reason for using such tools is to avoid paying for a VPS, and just hosting the listener on your own computer with remote port forwarding. There are multiple reasons this is desirable, but the main ones are low cost (free) and lack of complex setup to achieve basically the same result as using a VPS.

Both of these tools forward connections to 127.0.0.1. I configured them to forward connections to the port Empire is running the listener on.

The issue is, the agent will connect back initially, accessing the /admin/get.php, /news.php, and /login/process.php scripts on the web server, and displaying the `Initial agent [...] now active` text. I have looked at the built in logging utility in ngrok to confirm that the agent is accessing those PHP scipts. After this however, there are no further connections (as would be expected at whatever interval the `DefaultDelay` option is set to), and any commands issued to the agent hang indefinitely, presumably because there are no further connections from the agent.

Initially, I thought this was an issue with the remote port forwarding tools themselves, however when I configure a listener with `set Host 127.0.0.1` and run a stager on the same host, the same issue occurs. Hence, there must be a bug in Empire, where it can't receive from stagers connecting from 127.0.0.1.

**Comment by Strazzom** [comment]
Here is a log from --debug 2:
https://gist.github.com/Strazzom/69ff06b6d25431bc6988597384a5e923

**Comment by Strazzom** [comment]
I have confirmed that this is not a platform dependent issue, having performed the exact same procedure on the docker image. As with when empire is running in a VM, the initial agent connection occurs, and then it doesn't continue to check in when running on the same machine as the listener.

I confirmed this after fixing the issues in #994. I thought that this might be an issue with my Kali VM, however if the same issue occurs when empire is running in a docker container, the bug must in fact be in empire.

**Comment by xorrior** [comment]
@Strazzom, I can't seem to reproduce this issue you're having. I've tried this on a debian host. There doesn't seem to be any errors in the debug output either. Can you try this on another host and see if it's reproducible? :man_shrugging: 
![selection_004](https://user-images.githubusercontent.com/9156069/36356822-9b29273c-14c5-11e8-8c91-6a6d34134c50.png)
![selection_005](https://user-images.githubusercontent.com/9156069/36356823-9e37026e-14c5-11e8-82b5-77ea061c3b04.png)
![selection_006](https://user-images.githubusercontent.com/9156069/36356824-9fe052aa-14c5-11e8-86ee-22ec6a9a2635.png)
![selection_007](https://user-images.githubusercontent.com/9156069/36356825-a15c3d60-14c5-11e8-8b0f-c2ef445a12e1.png)

**Comment by Strazzom** [comment]
The dev branch does not install correctly on Debian 10, so I can't test it there. I will have to report that as a separate issue.

You seem to be using Debian 8. I will test it on Debian 8/9 and report back.

**Comment by Strazzom** [comment]
So, update:

I dealt with dependency hell on the Debian 8/9 docker images, so I gave up on that approach. Unfortunately, I have not had the time to set up a VM to test this on.

To avoid dealing with dependencies, I pulled the docker image for 2.4 (the base image of which is Ubuntu) and git cloned the dev branch there. The same issue is reproduced exactly when I attempt to reproduce the issue.

In the near future I will get ahold of a Debian 8 VM, so that I can more or less exactly reproduce your setup, and confirm whether this issue persists there.

**Comment by xorrior** [comment]
@Strazzom I'm not sure why the docker image is even in play. In my test, I was just using a home grown Debian image. No docker install.

**Comment by xorrior** [comment]
@Strazzom did you ever figure what the root cause was for this issue?

**Comment by xorrior** [comment]
@Strazzom if you're able to track down the root cause of this, please feel free to comment and I'll reopen this.
