### ISSUE TITLE
503 Server Unavailable error on stage execution

### ISSUE THREAD

**Issue by urban-moniker** [EmpireProject/Empire#985]
## Empire Version

Latest (git clone 10th Feb)

## OS Information (Linux flavor, Python version)

Kali 2018.1

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Created a http listener, executed a test agent using multi\launcher & windows\launcher, code runs, I can see traffic on the wire but no agent installed.  Tweaked the PS code so it runs on-screen and does not auto-close, and can see the following PS error: 

**Exception calling "DownloadData" with "1" argument(s).  "The remote server returned an error: (503) Server Unavailable"** 

If I browse to the Empire listener I can see the fake IIS graphic.  I have tweaked the ports and IP addresses and I get different errors if I try to connect to the wrong IP\port etc so def only shown this error when the Empire listener handles the request.

**Comment by urban-moniker** [comment]
![screenshot at 2018-02-11 18-22-09](https://user-images.githubusercontent.com/23149626/36076798-112d4da4-0f59-11e8-920d-417b2a895dad.png)

**Comment by urban-moniker** [comment]
Closed in error!

Note that reviewing some aspects it looks like PowerShell didn't install as part of the setup; not sure if this is relevant.

**Comment by xorrior** [comment]
@urban-moniker Not sure why you would receive a 503 unless the listener crashed. Can you try running empire with the --debug 2 flag and post the output here when the error occurs? Thanks and I apologize for the late response.

**Comment by xorrior** [comment]
@urban-moniker When you have the chance to debug further, feel free to post the output here and I'll re-open this.
