### ISSUE TITLE
shell command doesn't work with some characters

### ISSUE THREAD

**Issue by 0ca** [EmpireProject/Empire#991]
## Empire Version
Current

## OS Information (Linux flavor, Python version)
Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
This work:
```
shell echo aaa | cat
```

But this doesn't work:
```
shell /bin/bash -c 'echo aaa | cat'
```

This doesn't work neither:
```
shell echo bbb | cat > /tmp/file
shell /bin/bash -c 'echo aaa | cat > /tmp/file'
```

**Comment by xorrior** [comment]
Merged PR to address this issue.
