### ISSUE TITLE
problem with powershell/privesc/bypassuac_tokenmanipulation

### ISSUE THREAD

**Issue by sash322** [EmpireProject/Empire#996]
## Empire Version
2.4

## OS Information (Linux flavor, Python version)
Kali Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Hello, Noob question, but how can i properly use powershell/privesc/bypassuac_tokenmanipulation module? What type of stager i should host ?

**Comment by xorrior** [comment]
@sash322 This should just be a normal empire launcher, un-encoded. Hope this answers your question.
