### ISSUE TITLE
Empire Command not working

### ISSUE THREAD

**Issue by Jakanath** [EmpireProject/Empire#997]
hi 
i was using empire 1.4 version
the command that i use previously not working in latest version 2.4
Is there the command has change?
Can i get the list of command that i can use from setting up listeners, usestagger, interact ..
Thank you

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
To create a listener:
`listeners`
`uselistener [tab] [tab]` (display available listeners)

To generate a stager
`usestager [tab] [tab]` (display stagers)

To interact with agent:
`agents`
`list`
`interact XXXXXXX`

To sum up, press `[tab] [tab]`, if you're lost.
:sunflower:

**Comment by Jakanath** [comment]
Hi thank you for your response..
But Im still lose half way doing it.
May I get video or steps to  create stagger and listener and how to
interact with agents..
Thank you

**Comment by xorrior** [comment]
@Jakanath You may also use the help command. Currently, our documentation is out of date. We hope to have that resolved soon.
